package com.adalbert;
import java.util.*;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.*;

@State(Scope.Benchmark)
public class J_Profile4AllMaps_JTreeMap_20220429190540119 {
	java.util.TreeMap<Character, Character> collection = new java.util.TreeMap<>();
	@Setup(Level.Invocation)
	public void setupJTreeMap() {
		collection = new java.util.TreeMap<>();
		collection.put('Ć', 'ť');
		collection.put('ğ', 'ķ');
		collection.put('ƅ', 'Ò');
		collection.put('Ñ', 'ŧ');
		collection.put('Ŗ', 'ţ');
		collection.put('ƀ', 'ł');
		collection.put('Ə', 'š');
		collection.put('Ś', 'Ĝ');
		collection.put('û', 'Ř');
		collection.put('Ð', 'Ɔ');
		collection.put('ń', 'Ĭ');
		collection.put('ŉ', 'ş');
		collection.put('č', 'Ā');
		collection.put('Ŋ', 'ž');
		collection.put('ř', 'ð');
		collection.put('ē', 'Ǝ');
		collection.put('ŝ', 'í');
		collection.put('Ŧ', 'í');
		collection.put('ã', 'ű');
		collection.put('œ', 'Ê');
		collection.put('Ɔ', 'ŋ');
		collection.put('Õ', 'Ɗ');
		collection.put('Ŗ', 'à');
		collection.put('Ù', 'ŭ');
		collection.put('Ə', 'Ž');
		collection.put('Ħ', 'Ę');
		collection.put('î', 'É');
		collection.put('Č', 'đ');
		collection.put('Ƈ', 'ē');
		collection.put('Ú', 'Ü');
		collection.put('Ļ', 'ź');
		collection.put('ë', 'Đ');
		collection.put('ę', 'ĳ');
		collection.put('Ɖ', 'Ú');
		collection.put('ð', 'ž');
		collection.put('ö', 'ó');
		collection.put('Ī', 'Ċ');
		collection.put('ý', 'Ú');
		collection.put('ĵ', 'Ý');
		collection.put('Į', 'ĭ');
		collection.put('Ū', 'Ŗ');
		collection.put('į', 'Ƅ');
		collection.put('Ŭ', 'ť');
		collection.put('Ê', 'ŵ');
		collection.put('Ð', 'Ɖ');
		collection.put('ħ', 'Ĳ');
		collection.put('ū', 'Ŀ');
		collection.put('Ü', 'Ƅ');
		collection.put('Ŋ', 'ķ');
		collection.put('Ę', 'ŧ');
		collection.put('ó', 'ç');
		collection.put('ö', 'Ɓ');
		collection.put('ŗ', 'ġ');
		collection.put('Į', 'Ģ');
		collection.put('È', 'ŝ');
		collection.put('ĝ', 'ŀ');
		collection.put('ő', 'Ŗ');
		collection.put('Ľ', 'å');
		collection.put('Ś', 'Ø');
		collection.put('Ě', 'č');
		collection.put('ĝ', 'Š');
		collection.put('ġ', 'Ċ');
		collection.put('ī', 'ŀ');
		collection.put('Ó', 'å');
		collection.put('ğ', 'Ė');
		collection.put('Ƃ', 'ô');
		collection.put('ŋ', 'Û');
		collection.put('ŕ', 'ƌ');
		collection.put('Ģ', 'ŋ');
		collection.put('ĩ', 'Ĭ');
		collection.put('Œ', 'Ő');
		collection.put('ñ', 'ƈ');
		collection.put('Ũ', 'ğ');
		collection.put('ģ', 'Ę');
		collection.put('È', 'ę');
		collection.put('ë', 'û');
		collection.put('ĕ', 'ķ');
		collection.put('Ă', 'ñ');
		collection.put('Ě', 'Ė');
		collection.put('ü', 'Ő');
		collection.put('Ĺ', 'í');
		collection.put('Ņ', 'ń');
		collection.put('Ĳ', 'Ŏ');
		collection.put('Ĥ', 'ó');
		collection.put('ā', 'Ɖ');
		collection.put('ş', 'ö');
		collection.put('ą', 'Ļ');
		collection.put('Č', 'ê');
		collection.put('Í', 'ï');
		collection.put('ü', 'ƍ');
		collection.put('Ɔ', 'Î');
		collection.put('ŀ', 'Ŀ');
		collection.put('Ý', 'Ō');
		collection.put('ł', '×');
		collection.put('Ā', 'Ø');
		collection.put('Ĭ', 'ā');
		collection.put('Ê', 'Ô');
		collection.put('Ƅ', 'Ą');
		collection.put('Õ', 'ă');
		collection.put('Ċ', 'ą');
		collection.put('š', 'ś');
		collection.put('ĵ', 'Ċ');
		collection.put('Ƃ', 'Ó');
		collection.put('ü', 'Þ');
		collection.put('Ķ', 'þ');
		collection.put('Ì', 'Ĵ');
		collection.put('æ', 'ŉ');
		collection.put('Õ', '×');
		collection.put('Ð', 'Ũ');
		collection.put('İ', 'Ē');
		collection.put('ý', 'ú');
		collection.put('Ò', 'Ģ');
		collection.put('Ĉ', 'à');
		collection.put('Ŵ', 'ć');
		collection.put('ľ', 'Ð');
		collection.put('ŉ', 'Ĥ');
		collection.put('ĉ', 'ŉ');
		collection.put('ò', 'Ŋ');
		collection.put('ä', 'Ɓ');
		collection.put('ŷ', 'ŋ');
		collection.put('á', 'Ý');
		collection.put('ç', 'Ż');
		collection.put('Û', 'Ģ');
		collection.put('Î', 'Ŕ');
		collection.put('É', 'Ė');
		collection.put('ŉ', 'Ě');
		collection.put('Î', 'Ø');
		collection.put('Ý', 'ŧ');
		collection.put('Ŝ', 'ì');
		collection.put('Ġ', 'È');
		collection.put('ė', 'ģ');
		collection.put('Ě', 'ĝ');
		collection.put('Ŗ', 'ŵ');
		collection.put('ő', 'ƃ');
		collection.put('ŗ', 'å');
		collection.put('Ĺ', 'ž');
		collection.put('Ŧ', 'ú');
		collection.put('Ļ', 'č');
		collection.put('ď', 'ĩ');
		collection.put('ř', 'Ŀ');
		collection.put('ŋ', 'ò');
		collection.put('õ', 'Ŕ');
		collection.put('Ť', 'ĉ');
		collection.put('Ö', 'ŭ');
		collection.put('ƍ', 'É');
		collection.put('Ë', 'ò');
		collection.put('Õ', 'Ń');
		collection.put('ê', 'Ĳ');
		collection.put('Ú', 'Č');
		collection.put('Ê', 'Ă');
		collection.put('Ŷ', 'Ĕ');
		collection.put('ð', 'Ę');
		collection.put('Ž', 'Ę');
		collection.put('÷', 'È');
		collection.put('Ģ', 'ŝ');
		collection.put('ċ', 'ý');
		collection.put('Ĳ', 'Ù');
		collection.put('à', 'Ħ');
		collection.put('ŉ', 'Í');
		collection.put('ï', 'Ų');
		collection.put('ġ', 'ĩ');
		collection.put('ņ', 'Ɗ');
		collection.put('é', 'Ų');
		collection.put('Ņ', 'œ');
		collection.put('Ñ', 'ſ');
		collection.put('ħ', 'Ð');
		collection.put('Û', 'ô');
		collection.put('đ', 'ƈ');
		collection.put('ŷ', 'ŉ');
		collection.put('ł', 'ī');
		collection.put('Ɖ', 'ú');
		collection.put('ģ', 'Ŗ');
		collection.put('ŝ', 'Ž');
		collection.put('Ħ', 'Ë');
		collection.put('è', 'Ï');
		collection.put('Ì', 'ő');
		collection.put('ō', 'Ů');
		collection.put('Û', 'ô');
		collection.put('Ĩ', 'Ƅ');
		collection.put('Ě', 'Ś');
		collection.put('ĸ', 'ƃ');
		collection.put('Ņ', 'ß');
		collection.put('œ', 'Į');
		collection.put('ŀ', 'Ŷ');
		collection.put('ï', 'Ł');
		collection.put('ã', 'ç');
		collection.put('ó', 'õ');
		collection.put('ı', 'ġ');
		collection.put('ý', 'ē');
		collection.put('Đ', 'ĩ');
		collection.put('Ə', 'â');
		collection.put('ŝ', 'Ô');
		collection.put('ę', 'ù');
		collection.put('ƅ', 'Ð');
		collection.put('đ', 'ē');
		collection.put('ġ', 'ì');
		collection.put('Ġ', 'Ð');
		collection.put('Ŷ', 'ĥ');
		collection.put('ĳ', 'Ņ');
		collection.put('Ñ', 'ã');
		collection.put('Ű', 'ğ');
		collection.put('è', 'Ö');
		collection.put('ė', 'è');
		collection.put('Ƃ', 'ę');
		collection.put('ŋ', 'Ô');
		collection.put('ø', 'Č');
		collection.put('ņ', 'ą');
		collection.put('ũ', 'ç');
		collection.put('ě', 'ž');
		collection.put('ė', 'ŋ');
		collection.put('Ƈ', 'Ű');
		collection.put('ſ', 'Ą');
		collection.put('Ɗ', 'Ô');
		collection.put('Ó', 'Ĕ');
		collection.put('ň', 'ŝ');
		collection.put('ŋ', 'Ĭ');
		collection.put('Ĳ', 'Ŧ');
		collection.put('Ű', 'ů');
		collection.put('ų', 'Ģ');
		collection.put('Ŋ', 'Ė');
		collection.put('í', 'ŧ');
		collection.put('đ', 'ŝ');
		collection.put('Ĩ', 'ž');
		collection.put('Ü', 'Ļ');
		collection.put('ũ', 'ð');
		collection.put('ĸ', 'ŗ');
		collection.put('ĭ', 'ö');
		collection.put('Ř', 'ß');
		collection.put('á', 'Ŗ');
		collection.put('Ÿ', 'ĩ');
		collection.put('û', 'Ɓ');
		collection.put('ğ', 'Ø');
		collection.put('ľ', 'ŋ');
		collection.put('Ŋ', 'ø');
		collection.put('û', 'ƅ');
		collection.put('Ź', 'ń');
		collection.put('ƌ', 'Ŗ');
		collection.put('ß', 'Ɖ');
		collection.put('ā', 'ú');
		collection.put('ļ', 'ŕ');
		collection.put('ƍ', 'Ò');
		collection.put('Ā', 'ƀ');
		collection.put('Ļ', 'ä');
		collection.put('Ì', 'á');
		collection.put('Ŀ', 'ż');
		collection.put('Č', 'Ē');
		collection.put('ž', 'Ķ');
		collection.put('÷', 'Đ');
		collection.put('Ů', 'Ð');
		collection.put('ĺ', 'ū');
		collection.put('Ţ', 'Š');
		collection.put('Ó', 'é');
		collection.put('ŋ', 'å');
		collection.put('Ǝ', 'Ŷ');
		collection.put('Ļ', 'ø');
		collection.put('ċ', 'ě');
		collection.put('ű', 'ƈ');
		collection.put('Š', 'Ø');
		collection.put('õ', 'Ş');
		collection.put('ŀ', 'æ');
		collection.put('Ĉ', 'ĸ');
		collection.put('ŀ', 'ì');
		collection.put('ĕ', 'ı');
		collection.put('ŋ', 'Ķ');
		collection.put('Ś', 'Ť');
		collection.put('Ŧ', 'Ğ');
		collection.put('ŕ', 'Ħ');
		collection.put('ŝ', 'â');
		collection.put('ž', 'Û');
		collection.put('œ', 'Ė');
		collection.put('ř', 'ƀ');
		collection.put('ŵ', 'ń');
		collection.put('Õ', 'Ō');
		collection.put('Ÿ', 'Ĵ');
		collection.put('Ĩ', 'ź');
		collection.put('Ô', 'Ɔ');
		collection.put('Ø', 'Ż');
		collection.put('û', 'ŏ');
		collection.put('Ô', 'ç');
		collection.put('ƀ', 'ĝ');
		collection.put('Ħ', 'Ô');
		collection.put('ě', 'ó');
		collection.put('ĵ', 'æ');
		collection.put('Ă', 'Î');
		collection.put('Ŗ', 'ä');
		collection.put('ġ', 'ĵ');
		collection.put('ê', 'ĭ');
		collection.put('ř', 'ë');
		collection.put('ĺ', 'ū');
		collection.put('Ĵ', 'Ā');
		collection.put('Ö', 'ť');
		collection.put('į', 'ū');
		collection.put('Ħ', 'Ÿ');
		collection.put('ş', 'ý');
		collection.put('Ů', 'Ñ');
		collection.put('Ű', 'ł');
		collection.put('ŕ', 'Ă');
		collection.put('Ŧ', 'Ĕ');
		collection.put('Ģ', 'ŉ');
		collection.put('Ŷ', 'Ř');
		collection.put('Ó', 'ĉ');
		collection.put('å', 'ŏ');
		collection.put('Ñ', 'Ɔ');
		collection.put('Ɗ', 'ů');
		collection.put('á', 'ă');
		collection.put('Ē', 'Ř');
		collection.put('ż', 'ĩ');
		collection.put('ô', 'Ļ');
		collection.put('Ĉ', 'Ú');
		collection.put('Ā', 'ũ');
		collection.put('ń', 'ŵ');
		collection.put('ť', 'Ĵ');
		collection.put('ĭ', 'Ɔ');
		collection.put('Š', 'Ŷ');
		collection.put('ï', 'Ø');
		collection.put('è', 'Í');
		collection.put('Ɓ', 'Û');
		collection.put('Ħ', 'ť');
		collection.put('Ŗ', 'ŷ');
		collection.put('è', 'Ō');
		collection.put('Ŧ', 'þ');
		collection.put('ç', 'ň');
		collection.put('Ł', 'ĸ');
		collection.put('ſ', 'Ř');
		collection.put('ě', 'ź');
		collection.put('Ĺ', 'ƌ');
		collection.put('İ', 'ě');
		collection.put('Ÿ', 'ľ');
		collection.put('Č', 'Ň');
		collection.put('ó', 'Ņ');
		collection.put('õ', 'Ų');
		collection.put('Ž', 'ò');
		collection.put('Ë', 'Ɓ');
		collection.put('Ə', 'ã');
		collection.put('ē', 'Š');
		collection.put('ť', 'è');
		collection.put('ß', 'ë');
		collection.put('ſ', 'ĵ');
		collection.put('ĳ', 'Ś');
		collection.put('É', 'Ģ');
		collection.put('Ú', 'ŕ');
		collection.put('Ï', 'ă');
		collection.put('İ', 'ò');
		collection.put('Ĳ', 'ê');
		collection.put('Ö', 'É');
		collection.put('ſ', 'Ê');
		collection.put('Ƈ', 'ï');
		collection.put('Ś', 'ý');
		collection.put('ĉ', 'đ');
		collection.put('Ü', 'ƀ');
		collection.put('ď', 'Þ');
		collection.put('Ū', 'ĥ');
		collection.put('Č', 'Ż');
		collection.put('Đ', 'Ŝ');
		collection.put('ŉ', 'Ř');
		collection.put('÷', 'î');
		collection.put('Œ', 'ĝ');
		collection.put('ŷ', 'ø');
		collection.put('ė', 'Ķ');
		collection.put('ŋ', 'Ĝ');
		collection.put('Ŋ', 'Ō');
		collection.put('ť', 'ļ');
		collection.put('ā', 'ŭ');
		collection.put('â', 'Ċ');
		collection.put('ä', 'ä');
		collection.put('Ā', 'Ũ');
		collection.put('Ĉ', 'Ɔ');
		collection.put('Ƈ', 'é');
		collection.put('ň', 'ū');
		collection.put('ē', 'ś');
		collection.put('Ź', 'Ĵ');
		collection.put('Ċ', 'ľ');
		collection.put('Ü', 'ų');
		collection.put('ù', 'ø');
		collection.put('Í', 'Ŭ');
		collection.put('Ù', 'ņ');
		collection.put('Ž', 'â');
		collection.put('ï', 'Ƅ');
		collection.put('Ğ', 'Ř');
		collection.put('ā', 'į');
		collection.put('Ť', 'ū');
		collection.put('å', 'ű');
		collection.put('Ě', 'Ġ');
		collection.put('ť', 'ń');
		collection.put('ƈ', 'Ť');
		collection.put('ř', 'Ŏ');
		collection.put('Ċ', 'Ū');
		collection.put('Ō', 'Ţ');
		collection.put('ĥ', 'ò');
		collection.put('Õ', 'Ċ');
		collection.put('Ë', 'Ļ');
		collection.put('Ł', 'Ɖ');
		collection.put('Ŵ', 'å');
		collection.put('Ď', 'Ć');
		collection.put('Ġ', 'Ĥ');
		collection.put('Ŕ', 'Ÿ');
		collection.put('Ŏ', 'Ŕ');
		collection.put('Î', 'ê');
		collection.put('ŋ', 'Ú');
		collection.put('þ', 'ž');
		collection.put('Ƃ', 'ę');
		collection.put('ħ', 'û');
		collection.put('Ñ', 'ņ');
		collection.put('Ŋ', 'ų');
		collection.put('Ÿ', 'ų');
		collection.put('Ġ', 'ĵ');
		collection.put('ņ', 'ź');
		collection.put('ļ', 'ę');
		collection.put('ů', 'ŗ');
		collection.put('Ŀ', 'ź');
		collection.put('×', 'ý');
		collection.put('Õ', 'Ɖ');
		collection.put('Ē', 'Ù');
		collection.put('Õ', 'ĸ');
		collection.put('Ŕ', 'ľ');
		collection.put('Ă', 'ř');
		collection.put('ő', 'Ž');
		collection.put('Ž', 'ƅ');
		collection.put('Ĥ', 'Ɓ');
		collection.put('Ţ', 'Ġ');
		collection.put('Ħ', 'ġ');
		collection.put('İ', 'Ÿ');
		collection.put('ş', 'Ü');
		collection.put('Ê', 'ž');
		collection.put('î', 'Ľ');
		collection.put('Ŷ', 'ź');
		collection.put('Ď', 'Ĺ');
		collection.put('Î', 'Ƅ');
		collection.put('ū', 'Ş');
		collection.put('Ā', 'ų');
		collection.put('Ð', 'Ð');
		collection.put('Ö', 'Ô');
		collection.put('í', 'œ');
		collection.put('Ĉ', 'Ŋ');
		collection.put('Ĭ', 'í');
		collection.put('ŗ', 'ſ');
		collection.put('Ɓ', 'Ţ');
		collection.put('ż', 'ė');
		collection.put('ć', 'Ò');
		collection.put('ś', 'ŧ');
		collection.put('ø', 'Ţ');
		collection.put('Ĳ', 'é');
		collection.put('Ɔ', 'Ũ');
		collection.put('ě', 'Ų');
		collection.put('ý', 'Ƌ');
		collection.put('Í', 'ā');
		collection.put('ą', 'ć');
		collection.put('ƍ', 'ſ');
		collection.put('Ş', 'É');
		collection.put('Ê', 'ŕ');
		collection.put('ĺ', 'ſ');
		collection.put('ů', 'Ż');
		collection.put('Ő', 'á');
		collection.put('Ɗ', 'Ĺ');
		collection.put('ğ', 'Þ');
		collection.put('ſ', 'Ƌ');
		collection.put('Ž', 'ň');
		collection.put('ģ', 'Š');
		collection.put('å', 'Ŵ');
		collection.put('Ĩ', 'û');
		collection.put('Ũ', 'ĸ');
		collection.put('Ň', 'ą');
		collection.put('Ý', 'Ą');
		collection.put('İ', 'Ű');
		collection.put('Ɔ', 'ĳ');
		collection.put('į', 'ą');
		collection.put('Ƃ', 'ï');
		collection.put('Ƌ', 'É');
		collection.put('ł', 'Ƅ');
		collection.put('Đ', 'Ľ');
		collection.put('ã', 'Ŕ');
		collection.put('İ', 'î');
		collection.put('ĉ', 'ă');
		collection.put('ŉ', 'Ï');
		collection.put('ø', 'ñ');
		collection.put('È', 'İ');
		collection.put('ź', 'Ě');
		collection.put('ā', 'Ü');
		collection.put('â', 'Ú');
		collection.put('Ũ', 'Ŭ');
		collection.put('Ý', 'ë');
		collection.put('ĸ', 'ç');
		collection.put('Ŭ', 'Ɓ');
		collection.put('Ñ', 'ç');
		collection.put('ĸ', 'Ƅ');
		collection.put('ĩ', 'ę');
		collection.put('ĥ', 'ģ');
		collection.put('ŷ', 'Ü');
		collection.put('ú', 'ł');
		collection.put('×', 'Ô');
		collection.put('ř', 'ŏ');
		collection.put('ý', 'ŀ');
		collection.put('ı', 'đ');
		collection.put('Ž', 'Ĥ');
		collection.put('Đ', 'ă');
		collection.put('Ê', 'ż');
		collection.put('ĳ', 'Ñ');
		collection.put('Ĵ', 'Ł');
		collection.put('Ê', 'Ő');
		collection.put('ý', 'ć');
		collection.put('ê', 'ł');
		collection.put('Ŋ', 'ÿ');
		collection.put('Ƈ', 'Ë');
		collection.put('ũ', 'ħ');
		collection.put('Ă', 'ě');
		collection.put('ĵ', 'ř');
		collection.put('Ű', 'ś');
		collection.put('Î', 'Ŕ');
		collection.put('ľ', 'ż');
		collection.put('ŷ', 'Ć');
		collection.put('Ÿ', 'ĉ');
		collection.put('ń', 'ŕ');
		collection.put('Þ', 'Ĉ');
		collection.put('Ŷ', 'ŉ');
		collection.put('Ĵ', 'ÿ');
		collection.put('Í', 'Ź');
		collection.put('Û', 'Ň');
		collection.put('Ê', 'Ŋ');
		collection.put('Ğ', 'ò');
		collection.put('Ļ', 'ť');
		collection.put('ƍ', 'Č');
		collection.put('ğ', 'Ų');
		collection.put('ś', 'ƈ');
		collection.put('â', 'Ý');
		collection.put('Ƃ', 'ě');
		collection.put('Ò', 'ì');
		collection.put('ż', 'æ');
		collection.put('Ĥ', 'š');
		collection.put('Ɓ', 'ą');
		collection.put('ă', 'ŵ');
		collection.put('â', 'ę');
		collection.put('ó', 'ū');
		collection.put('ć', 'ź');
		collection.put('Ċ', 'Ò');
		collection.put('Ę', 'ä');
		collection.put('Ğ', 'č');
		collection.put('č', 'Ľ');
		collection.put('Ī', 'ê');
		collection.put('ņ', 'û');
		collection.put('þ', 'ÿ');
		collection.put('ĉ', 'á');
		collection.put('ë', 'Ţ');
		collection.put('ğ', 'ŷ');
		collection.put('Ĳ', 'å');
		collection.put('ý', 'ù');
		collection.put('Õ', 'Ė');
		collection.put('Ő', 'ķ');
		collection.put('Ö', 'ő');
		collection.put('á', 'ü');
		collection.put('ō', 'ſ');
		collection.put('š', 'Ģ');
		collection.put('ħ', 'é');
		collection.put('û', 'Ů');
		collection.put('Ï', 'ű');
		collection.put('Ĕ', 'Ɖ');
		collection.put('ĭ', 'Ɔ');
		collection.put('Į', 'Ú');
		collection.put('ù', 'ū');
		collection.put('ñ', 'ř');
		collection.put('Ń', 'ĭ');
		collection.put('Þ', 'Ð');
		collection.put('İ', 'Č');
		collection.put('ų', 'ı');
		collection.put('ţ', 'ő');
		collection.put('Č', 'ă');
		collection.put('į', 'č');
		collection.put('à', 'Ś');
		collection.put('Ê', 'Ş');
		collection.put('đ', 'Ħ');
		collection.put('Č', 'ſ');
		collection.put('ć', 'ě');
		collection.put('Ƌ', 'Ū');
		collection.put('Ľ', 'Ğ');
		collection.put('ń', 'æ');
		collection.put('Ď', 'Ķ');
		collection.put('ÿ', 'ƅ');
		collection.put('ŋ', 'ğ');
		collection.put('Ř', 'ú');
		collection.put('ĝ', 'ĸ');
		collection.put('Ý', 'ř');
		collection.put('Ŋ', 'ñ');
		collection.put('Ě', 'ų');
		collection.put('č', 'İ');
		collection.put('ŵ', 'Ë');
		collection.put('Ģ', 'ň');
		collection.put('Ĝ', 'Ā');
		collection.put('Ƅ', 'Ĥ');
		collection.put('ŗ', 'ġ');
		collection.put('ã', '×');
		collection.put('ö', 'ì');
		collection.put('ŷ', 'Ŷ');
		collection.put('Ø', 'ě');
		collection.put('Ĉ', 'è');
		collection.put('ŗ', 'â');
		collection.put('ſ', 'ş');
		collection.put('š', 'Ƈ');
		collection.put('Ĕ', 'Ē');
		collection.put('þ', 'Ö');
		collection.put('à', 'Š');
		collection.put('Ɓ', 'ï');
		collection.put('Ƅ', 'ë');
		collection.put('Ɔ', 'ú');
		collection.put('Ĝ', 'œ');
		collection.put('Ə', 'à');
		collection.put('ŝ', 'Ɗ');
		collection.put('ř', 'Ŕ');
		collection.put('ŭ', 'Ñ');
		collection.put('Ŀ', 'Ŵ');
		collection.put('đ', 'Ō');
		collection.put('ć', 'Ķ');
		collection.put('ó', 'Ţ');
		collection.put('ċ', 'Ś');
		collection.put('ó', 'ń');
		collection.put('â', 'ţ');
		collection.put('ļ', 'Ķ');
		collection.put('Ú', 'ś');
		collection.put('š', 'ŭ');
		collection.put('ā', 'ş');
		collection.put('ĥ', 'Ƈ');
		collection.put('è', 'î');
		collection.put('ĥ', 'Ÿ');
		collection.put('ę', 'Ŗ');
		collection.put('Ź', 'Ĉ');
		collection.put('Ė', 'Ģ');
		collection.put('ƀ', 'ū');
		collection.put('ō', 'â');
		collection.put('Ž', 'Ĕ');
		collection.put('ĭ', 'Ɗ');
		collection.put('į', 'ő');
		collection.put('ğ', 'œ');
		collection.put('ā', 'È');
		collection.put('ô', 'Œ');
		collection.put('Ĕ', 'ŀ');
		collection.put('ū', 'ď');
		collection.put('ŕ', 'ƈ');
		collection.put('Ƌ', 'Č');
		collection.put('ñ', 'ò');
		collection.put('ž', 'Ă');
		collection.put('ƅ', 'Ň');
		collection.put('ď', 'Ò');
		collection.put('Ħ', 'į');
		collection.put('Ɗ', 'Ó');
		collection.put('ı', 'Ţ');
		collection.put('î', 'Ð');
		collection.put('ũ', 'ƍ');
		collection.put('ű', 'ħ');
		collection.put('ì', 'Ğ');
		collection.put('Ń', 'Ô');
		collection.put('ƃ', 'Ĵ');
		collection.put('ũ', 'Ú');
		collection.put('Ů', 'á');
		collection.put('ä', 'Č');
		collection.put('Ø', 'Ď');
		collection.put('š', 'Ā');
		collection.put('Ƌ', 'Ĺ');
		collection.put('Ū', 'Ú');
		collection.put('ł', 'Ǝ');
		collection.put('œ', 'í');
		collection.put('õ', 'Ƌ');
		collection.put('É', 'ġ');
		collection.put('ą', 'Ĝ');
		collection.put('ã', 'Ť');
		collection.put('õ', 'ì');
		collection.put('ü', 'Ú');
		collection.put('ű', 'Ļ');
		collection.put('ï', 'Ŗ');
		collection.put('ő', 'Đ');
		collection.put('ä', 'ė');
		collection.put('Ņ', 'ƍ');
		collection.put('Ċ', 'Î');
		collection.put('Ÿ', 'Ň');
		collection.put('ć', 'ł');
		collection.put('į', 'ĝ');
		collection.put('ö', 'ï');
		collection.put('Ì', 'Ý');
		collection.put('ç', 'İ');
		collection.put('ź', 'ŝ');
		collection.put('ƍ', 'Ď');
		collection.put('ß', 'Ñ');
		collection.put('Ŏ', 'â');
		collection.put('û', 'Ə');
		collection.put('×', 'Ũ');
		collection.put('ŧ', 'ď');
		collection.put('Ķ', 'ö');
		collection.put('é', 'ī');
		collection.put('Ż', 'ũ');
		collection.put('ÿ', 'ĳ');
		collection.put('Ĺ', 'ð');
		collection.put('Ŵ', 'Ă');
		collection.put('ý', 'ċ');
		collection.put('Ō', 'È');
		collection.put('Ŭ', 'Ę');
		collection.put('ć', 'é');
		collection.put('÷', 'ù');
		collection.put('č', 'ť');
		collection.put('ù', 'ſ');
		collection.put('Ļ', 'ŭ');
		collection.put('ì', 'ľ');
		collection.put('ô', 'ų');
		collection.put('Ĕ', 'Ë');
		collection.put('Ü', 'Ÿ');
		collection.put('Ŝ', 'ž');
		collection.put('ù', 'ő');
		collection.put('Ę', 'ù');
		collection.put('Ƈ', 'Ĥ');
		collection.put('ÿ', 'Ǝ');
		collection.put('ì', 'ň');
		collection.put('×', 'ƀ');
		collection.put('×', 'ť');
		collection.put('Ö', 'ō');
		collection.put('ĩ', 'Ģ');
		collection.put('ì', 'š');
		collection.put('ć', 'ī');
		collection.put('ŝ', 'ñ');
		collection.put('ŵ', 'ŋ');
		collection.put('ľ', 'ě');
		collection.put('Ň', 'Ŗ');
		collection.put('Ë', 'ő');
		collection.put('ū', 'Ŗ');
		collection.put('ƈ', 'ö');
		collection.put('Þ', 'é');
		collection.put('Ċ', 'Ĝ');
		collection.put('ť', 'Ō');
		collection.put('ô', 'Ų');
		collection.put('ċ', 'Ò');
		collection.put('Č', 'Ŭ');
		collection.put('Ƈ', 'Ƃ');
		collection.put('Ŭ', 'Ú');
		collection.put('Ě', 'ē');
		collection.put('ü', 'Œ');
		collection.put('ŵ', 'Ü');
		collection.put('Ž', 'Ě');
		collection.put('ù', 'Ĝ');
		collection.put('Ə', 'Ô');
		collection.put('ř', 'ƅ');
		collection.put('ĳ', 'Ű');
		collection.put('ů', 'ĉ');
		collection.put('Ĭ', 'ħ');
		collection.put('Ķ', 'Ľ');
		collection.put('ć', 'ô');
		collection.put('ò', 'ě');
		collection.put('Ą', 'ĸ');
		collection.put('Ś', 'Ľ');
		collection.put('ô', 'Ð');
		collection.put('Ċ', 'Ō');
		collection.put('ƅ', 'Ŭ');
		collection.put('Ì', 'Ł');
		collection.put('Ų', 'ĭ');
		collection.put('Ŕ', 'ū');
		collection.put('ê', 'Ŋ');
		collection.put('Ë', 'ø');
		collection.put('ö', 'ô');
		collection.put('Ǝ', 'Ī');
		collection.put('ľ', 'Ø');
		collection.put('ţ', 'Ŷ');
		collection.put('ƈ', 'ċ');
		collection.put('Ū', 'ŝ');
		collection.put('Ů', 'Ƌ');
		collection.put('ħ', 'Ó');
		collection.put('ç', 'Ž');
		collection.put('Õ', 'ŝ');
		collection.put('į', 'Ø');
		collection.put('ũ', 'Ľ');
		collection.put('ô', 'õ');
		collection.put('Ũ', 'ö');
		collection.put('Ú', 'Ð');
		collection.put('ů', 'à');
		collection.put('÷', 'õ');
		collection.put('Ħ', 'ļ');
		collection.put('Ĺ', 'ĥ');
		collection.put('Ü', 'É');
		collection.put('ƀ', 'ĉ');
		collection.put('Ŋ', 'ĕ');
		collection.put('Ň', 'ć');
		collection.put('ħ', 'Ū');
		collection.put('ţ', 'ú');
		collection.put('ŀ', 'ŵ');
		collection.put('Ķ', 'Ń');
		collection.put('Ð', 'Ŕ');
		collection.put('è', 'Ý');
		collection.put('Ð', 'č');
		collection.put('ŀ', 'é');
		collection.put('ŗ', 'ž');
		collection.put('Ì', 'ƀ');
		collection.put('ż', 'Ƅ');
		collection.put('ã', 'ƍ');
		collection.put('Ğ', 'ŕ');
		collection.put('Ľ', 'Ĉ');
		collection.put('ā', 'ã');
		collection.put('ř', 'ā');
		collection.put('ħ', 'ƈ');
		collection.put('Ĩ', 'Ŭ');
		collection.put('Ù', 'ň');
		collection.put('ž', 'ů');
		collection.put('ı', 'õ');
		collection.put('ņ', 'Ö');
		collection.put('â', 'Ĥ');
		collection.put('ġ', 'Ø');
		collection.put('č', 'ŷ');
		collection.put('ť', 'ş');
		collection.put('ô', 'Ŗ');
		collection.put('Ű', 'Ď');
		collection.put('Ą', 'Ƌ');
		collection.put('ū', 'ű');
		collection.put('Î', 'ŷ');
		collection.put('ŝ', 'ŧ');
		collection.put('ũ', 'ƃ');
		collection.put('Ĵ', 'Ɖ');
		collection.put('Ô', 'Ƈ');
		collection.put('Ō', 'å');
		collection.put('ğ', 'ū');
		collection.put('à', 'ì');
		collection.put('ç', 'Ģ');
		collection.put('Ō', 'Ĭ');
		collection.put('ň', 'ă');
		collection.put('ņ', 'ƍ');
		collection.put('ă', 'ÿ');
		collection.put('Ĕ', 'ó');
		collection.put('ť', 'ŕ');
		collection.put('Ĭ', 'Ŗ');
		collection.put('æ', 'Ë');
		collection.put('ô', 'ż');
		collection.put('é', 'ĵ');
		collection.put('ü', 'ŕ');
		collection.put('ņ', 'Ƈ');
		collection.put('Ğ', 'å');
		collection.put('ř', 'Č');
		collection.put('ņ', 'ĩ');
		collection.put('Ŀ', 'ž');
		collection.put('Û', 'ð');
		collection.put('Ĕ', 'í');
		collection.put('ł', 'ĺ');
		collection.put('ë', 'ą');
		collection.put('Ɔ', 'Ñ');
		collection.put('Ē', 'ě');
		collection.put('ï', 'ũ');
		collection.put('ć', 'Ē');
		collection.put('Ê', 'ć');
		collection.put('ā', 'Ɗ');
		collection.put('Ę', 'Ť');
		collection.put('Ɗ', 'Ģ');
		collection.put('Ň', 'Ś');
		collection.put('Ű', 'č');
		collection.put('į', 'ĺ');
		collection.put('È', 'û');
		collection.put('Ƈ', 'Ê');
		collection.put('ō', 'ē');
		collection.put('ē', 'ſ');
		collection.put('ı', 'Ń');
		collection.put('ã', 'ĩ');
		collection.put('Ű', 'ľ');
		collection.put('Û', 'õ');
		collection.put('ħ', 'ż');
		collection.put('Ë', 'Ű');
		collection.put('Ť', 'Ĩ');
		collection.put('ķ', 'ń');
		collection.put('Ò', 'ĥ');
		collection.put('Ċ', 'é');
		collection.put('Ï', 'ì');
		collection.put('ƃ', 'ĵ');
		collection.put('Ð', 'ġ');
		collection.put('×', 'ĩ');
		collection.put('á', 'Ğ');
		collection.put('ċ', 'Ù');
		collection.put('ĉ', 'ł');
		collection.put('Ĩ', 'å');
		collection.put('ů', 'Ŋ');
		collection.put('Ǝ', 'ķ');
		collection.put('Ɗ', 'Ž');
		collection.put('ů', 'ã');
		collection.put('ë', 'Ķ');
		collection.put('Ň', 'Ň');
		collection.put('ø', 'ƍ');
		collection.put('ž', 'Ġ');
		collection.put('Ï', 'ĭ');
		collection.put('Í', 'È');
		collection.put('Ź', 'Ů');
		collection.put('ĺ', 'ŷ');
		collection.put('Ö', 'ń');
		collection.put('č', 'ƍ');
		collection.put('ż', 'ğ');
		collection.put('Ð', 'ü');
		collection.put('ƅ', 'ô');
		collection.put('Ŷ', 'ė');
		collection.put('ŕ', 'Ö');
		collection.put('ſ', 'Ě');
		collection.put('ƍ', 'Ƈ');
		collection.put('Š', 'Ō');
		collection.put('ƀ', 'Ï');
		collection.put('ţ', 'Ï');
		collection.put('ç', 'ő');
		collection.put('ĕ', 'Ħ');
		collection.put('ł', 'Ĩ');
		collection.put('Ů', 'ƃ');
		collection.put('ŀ', 'Ĭ');
		collection.put('ī', 'â');
		collection.put('Ŵ', 'ś');
		collection.put('Õ', 'ò');
		collection.put('ű', 'Ņ');
		collection.put('Ć', 'ŵ');
		collection.put('ó', 'Ĕ');
		collection.put('ĺ', 'Ý');
		collection.put('Ě', 'ä');
		collection.put('Ľ', 'Ų');
		collection.put('Ì', 'Ų');
		collection.put('Į', 'æ');
		collection.put('į', 'ý');
		collection.put('Ż', 'ū');
		collection.put('Ð', 'Ə');
		collection.put('Ū', 'Ĉ');
		collection.put('đ', 'ķ');
		collection.put('Ř', 'Ŧ');
		collection.put('Ą', 'Ă');
		collection.put('ĕ', 'È');
		collection.put('Ō', 'İ');
		collection.put('ŭ', 'ĵ');
		collection.put('Ŋ', 'ŵ');
		collection.put('é', 'Ŏ');
		collection.put('æ', 'Ƅ');
		collection.put('ð', 'î');
		collection.put('Œ', 'ř');
		collection.put('ë', 'Ş');
		collection.put('ó', 'Ħ');
		collection.put('ŏ', 'Ŧ');
		collection.put('Ĝ', 'ĝ');
		collection.put('ë', 'ß');
		collection.put('Î', 'ż');
		collection.put('ũ', 'ŭ');
		collection.put('ƍ', 'ŕ');
		collection.put('ŝ', 'ų');
		collection.put('ũ', 'ë');
		collection.put('ţ', 'ĕ');
		collection.put('Ô', 'ŕ');
		collection.put('Œ', 'ň');
		collection.put('Ē', 'č');
		collection.put('ė', 'ĭ');
		collection.put('÷', 'Ĳ');
		collection.put('Ï', 'Ĭ');
		collection.put('ń', 'ŵ');
		collection.put('ĥ', 'Ŝ');
		collection.put('ÿ', 'Ũ');
		collection.put('ê', 'į');
		collection.put('ŵ', 'Ā');
		collection.put('ĩ', 'Ė');
		collection.put('Þ', 'Ħ');
		collection.put('ą', 'Ğ');
		collection.put('ŷ', 'Ź');
		collection.put('Û', 'Ń');
		collection.put('Ħ', 'İ');
		collection.put('Û', 'ī');
		collection.put('Ì', 'ŵ');
		collection.put('ĳ', 'ĉ');
		collection.put('î', 'ļ');
		collection.put('ƌ', 'Ę');
		collection.put('ť', 'Ñ');
		collection.put('Ó', 'ŷ');
		collection.put('ó', 'Ø');
		collection.put('ã', 'Ƃ');
		collection.put('ń', 'Ģ');
		collection.put('Ƈ', 'Đ');
		collection.put('ğ', 'Ó');
		collection.put('÷', 'ç');
		collection.put('þ', 'Ɓ');
		collection.put('à', 'Ŭ');
		collection.put('ö', 'Ŭ');
		collection.put('ġ', 'Ľ');
		collection.put('å', 'ő');
		collection.put('õ', 'į');
		collection.put('ŷ', 'ø');
		collection.put('Ĕ', 'Ý');
		collection.put('Ŋ', 'Ƈ');
		collection.put('ĥ', 'Ý');
		collection.put('ō', 'Ø');
		collection.put('ŉ', '÷');
		collection.put('ő', 'ĝ');
		collection.put('ü', 'Ĝ');
		collection.put('ŗ', 'ř');
		collection.put('ê', 'ű');
		collection.put('Ł', 'Ľ');
		collection.put('Ǝ', 'Ì');
		collection.put('ĥ', 'ƌ');
		collection.put('ò', 'Ý');
		collection.put('ť', 'ß');
		collection.put('ò', 'Ĉ');
		collection.put('ĭ', 'Ɗ');
		collection.put('ā', 'Ķ');
		collection.put('Ĉ', 'ž');
		collection.put('Ō', 'Ÿ');
		collection.put('ę', 'ĭ');
		collection.put('Ö', 'ƃ');
		collection.put('Ɓ', 'Č');
		collection.put('Ľ', 'å');
		collection.put('Ş', 'Ă');
		collection.put('ĭ', 'Ə');
		collection.put('ğ', 'Ā');
		collection.put('ŗ', 'ñ');
		collection.put('Ò', 'ĥ');
		collection.put('ô', 'Č');
		collection.put('Č', 'ſ');
		collection.put('ø', 'ō');
		collection.put('Ƌ', 'è');
		collection.put('Ŋ', 'Ę');
		collection.put('ĭ', 'Ĥ');
		collection.put('÷', 'ī');
		collection.put('ý', 'Ĭ');
		collection.put('ķ', 'ī');
		collection.put('ū', 'Č');
		collection.put('ç', 'Ũ');
		collection.put('ď', 'ü');
		collection.put('÷', 'Ý');
		collection.put('Ŝ', 'Ĉ');
		collection.put('Ł', 'û');
		collection.put('ō', 'Ŷ');
		collection.put('Ť', 'É');
		collection.put('í', 'ƃ');
		collection.put('ă', 'â');
		collection.put('ì', 'ü');
		collection.put('×', 'Ą');
		collection.put('ā', 'ŕ');
		collection.put('ń', 'Ņ');
		collection.put('ŵ', 'Ù');
		collection.put('Ļ', 'Ī');
		collection.put('ĥ', 'Ì');
		collection.put('ă', 'Ĥ');
		collection.put('á', 'ŗ');
		collection.put('Ŀ', 'ì');
		collection.put('Ĳ', 'ň');
		collection.put('č', 'Ĵ');
		collection.put('ğ', 'Ü');
		collection.put('Ǝ', 'Ŗ');
		collection.put('ı', 'Ī');
		collection.put('ƃ', 'ũ');
		collection.put('Ċ', 'É');
		collection.put('Î', 'Ľ');
		collection.put('ƃ', 'ĥ');
		collection.put('Ǝ', 'ş');
		collection.put('Ž', 'Ċ');
		collection.put('û', 'ē');
		collection.put('ţ', 'Ő');
		collection.put('ł', 'Ɗ');
		collection.put('Ŕ', 'â');
		collection.put('Ó', 'ű');
		collection.put('ſ', 'ı');
		collection.put('ă', 'Ü');
		collection.put('ľ', 'Ö');
		collection.put('Ė', 'Ď');
		collection.put('Ï', 'Ġ');
		collection.put('ĝ', 'â');
		collection.put('ģ', 'Ė');
		collection.put('Ĝ', 'ƃ');
		collection.put('Ŕ', 'Ô');
		collection.put('Ŋ', 'é');
		collection.put('ĸ', 'Ƃ');
		collection.put('Į', 'Ê');
		collection.put('Ū', 'à');
		collection.put('Ŏ', 'ę');
		collection.put('İ', 'õ');
		collection.put('Ý', '÷');
		collection.put('Ā', 'ƍ');
		collection.put('Ŗ', 'Ɓ');
		collection.put('Ž', 'Ļ');
		collection.put('Ŏ', 'Ń');
		collection.put('Ƃ', 'Ă');
		collection.put('Ş', 'ĳ');
		collection.put('È', 'ě');
		collection.put('ū', 'ĉ');
		collection.put('ô', 'ĳ');
		collection.put('Ĺ', 'ĉ');
		collection.put('Ž', 'Ĩ');
		collection.put('Ô', 'ŕ');
		collection.put('Ĩ', 'Ě');
		collection.put('Õ', 'ô');
		collection.put('Ƈ', 'Ì');
		collection.put('ě', 'ď');
		collection.put('ġ', 'ñ');
		collection.put('œ', 'Ô');
		collection.put('Ò', 'Ú');
		collection.put('ë', 'Ɔ');
		collection.put('å', 'š');
		collection.put('ī', 'ė');
		collection.put('ñ', 'ö');
		collection.put('â', 'Ă');
		collection.put('ĺ', 'ņ');
		collection.put('é', 'ï');
		collection.put('Ġ', 'ĝ');
		collection.put('ŕ', 'ö');
		collection.put('É', 'Ɖ');
		collection.put('Ɓ', 'Ŵ');
		collection.put('ĵ', 'Ė');
		collection.put('ş', 'Ŗ');
		collection.put('Ć', 'ë');
		collection.put('Ö', 'ţ');
		collection.put('ĸ', 'Ƌ');
		collection.put('Ń', 'ż');
		collection.put('è', 'ś');
		collection.put('İ', 'ê');
		collection.put('ú', 'Œ');
		collection.put('ũ', 'ł');
		collection.put('ſ', 'ē');
		collection.put('ø', 'ù');
		collection.put('Ÿ', 'Ð');
		collection.put('ƍ', 'Ĥ');
		collection.put('ė', 'Ŵ');
		collection.put('ƈ', 'å');
		collection.put('į', 'ĉ');
		collection.put('ų', 'ı');
		collection.put('ĉ', 'į');
		collection.put('ì', 'ĺ');
		collection.put('ĩ', 'Ö');
		collection.put('ń', 'õ');
		collection.put('ħ', 'í');
		collection.put('ļ', 'Ů');
		collection.put('þ', 'Ť');
		collection.put('û', 'Ĥ');
		collection.put('Ÿ', 'ê');
		collection.put('Ì', 'ö');
		collection.put('ƃ', 'Ż');
		collection.put('ø', 'ĭ');
		collection.put('İ', 'Ə');
		collection.put('ä', 'ù');
		collection.put('ŷ', 'Š');
		collection.put('ĉ', 'ż');
		collection.put('ŭ', 'Ō');
		collection.put('ń', 'Š');
		collection.put('Ľ', 'ł');
		collection.put('ĝ', 'ž');
		collection.put('ž', 'Ū');
		collection.put('Ə', 'ë');
		collection.put('Þ', 'İ');
		collection.put('Ÿ', 'ƍ');
		collection.put('Ś', 'Ś');
		collection.put('Ɓ', 'ŗ');
		collection.put('Š', 'ä');
		collection.put('ļ', 'Þ');
		collection.put('Ɗ', 'Ť');
		collection.put('Ķ', 'å');
		collection.put('Ģ', 'Ł');
		collection.put('Ē', 'ŭ');
		collection.put('Ƅ', 'ſ');
		collection.put('ù', 'ń');
		collection.put('ĕ', 'Ø');
		collection.put('Ŗ', 'ŀ');
		collection.put('Ň', 'ę');
		collection.put('Ğ', 'ŭ');
		collection.put('è', 'ĉ');
		collection.put('ſ', '×');
		collection.put('Ć', 'Ő');
		collection.put('ĸ', 'Č');
		collection.put('Ŀ', 'Ż');
		collection.put('ĕ', 'ľ');
		collection.put('Ó', 'ć');
		collection.put('Ŧ', 'ŀ');
		collection.put('Ŗ', 'ƍ');
		collection.put('ä', 'Ó');
		collection.put('Ð', 'è');
		collection.put('ħ', 'Õ');
		collection.put('Ž', 'Ŭ');
		collection.put('Ÿ', 'Ɖ');
		collection.put('Ų', 'İ');
		collection.put('ì', 'Ƌ');
		collection.put('ĉ', 'Ş');
		collection.put('Ų', 'å');
		collection.put('Ă', 'ŉ');
		collection.put('ó', 'ã');
		collection.put('ÿ', 'ŉ');
		collection.put('û', 'Ø');
		collection.put('ě', 'Ů');
		collection.put('Ċ', 'Ċ');
		collection.put('ë', 'Ź');
		collection.put('ą', 'ģ');
		collection.put('Ð', 'ù');
		collection.put('ū', 'ř');
		collection.put('Ĵ', 'ç');
		collection.put('ų', 'Ŭ');
		collection.put('ŋ', 'Ľ');
		collection.put('ş', 'ş');
		collection.put('ű', 'Ģ');
		collection.put('þ', 'Ĉ');
		collection.put('Ę', 'Ĩ');
		collection.put('ĉ', 'ż');
		collection.put('Č', 'Ɗ');
		collection.put('ć', 'Ĝ');
		collection.put('Ĵ', 'â');
		collection.put('Ŏ', 'Ē');
		collection.put('Õ', 'ś');
		collection.put('ķ', 'Ė');
		collection.put('Ū', 'ê');
		collection.put('Ú', 'Į');
		collection.put('ê', 'Ŝ');
		collection.put('Ś', 'Ģ');
		collection.put('ð', 'Ť');
		collection.put('Ŵ', 'Ũ');
		collection.put('ł', 'å');
		collection.put('ķ', 'ń');
		collection.put('è', 'Ž');
		collection.put('õ', 'å');
		collection.put('×', 'ĭ');
		collection.put('×', 'č');
		collection.put('Ĺ', 'è');
		collection.put('ō', 'Ī');
	}
	@Benchmark
	@Fork(1)
	@Warmup(time=3)
	@Measurement(time=3,iterations=10)
	public void JTreeMap(Blackhole bh) {
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ô'));
		bh.consume(collection.containsKey('ů'));
		bh.consume(collection.remove('ļ'));
		bh.consume(collection.get('ř'));
		bh.consume(collection.get('Ē'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('î', 'È'));
		bh.consume(collection.replace('Ğ', 'ë'));
		bh.consume(collection.remove('þ'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ŷ', 'č'));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ĕ', 'Ó'));
		bh.consume(collection.get('ō'));
		bh.consume(collection.replace('ň', 'ĝ'));
		bh.consume(collection.get('è'));
		bh.consume(collection.replace('ş', 'ĳ'));
		bh.consume(collection.replace('Ż', 'ħ'));
		bh.consume(collection.replace('ƈ', 'ø'));
		bh.consume(collection.get('ž'));
		bh.consume(collection.values());
		bh.consume(collection.remove('œ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ì'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey('ĵ'));
		bh.consume(collection.containsKey('Ý'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get('ł'));
		bh.consume(collection.get('š'));
		bh.consume(collection.replace('Ĝ', 'Ĵ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('Ť'));
		bh.consume(collection.replace('ĕ', 'ď'));
		bh.consume(collection.containsKey('ı'));
		bh.consume(collection.get('ă'));
		bh.consume(collection.containsKey('õ'));
		bh.consume(collection.remove('Ə'));
		bh.consume(collection.remove('Ş'));
		bh.consume(collection.get('Ĉ'));
		bh.consume(collection.remove('Ľ'));
		bh.consume(collection.containsKey('Ź'));
		bh.consume(collection.containsKey('ƃ'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('Õ'));
		bh.consume(collection.replace('ƈ', 'Ŷ'));
		bh.consume(collection.get('×'));
		bh.consume(collection.containsKey('ħ'));
		bh.consume(collection.containsKey('ë'));
		bh.consume(collection.remove('ù'));
		bh.consume(collection.replace('ź', 'ą'));
		bh.consume(collection.containsKey('ğ'));
		bh.consume(collection.remove('Ō'));
		bh.consume(collection.replace('Ě', 'Ģ'));
		bh.consume(collection.containsKey('ƃ'));
		bh.consume(collection.get('ģ'));
		bh.consume(collection.replace('Ê', 'Ÿ'));
		bh.consume(collection.containsKey('í'));
		bh.consume(collection.replace('Ɖ', 'ó'));
		bh.consume(collection.containsKey('å'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('ł'));
		bh.consume(collection.replace('ņ', 'Ó'));
		bh.consume(collection.replace('Ź', 'Ï'));
		bh.consume(collection.containsKey('ä'));
		bh.consume(collection.containsKey('ŏ'));
		bh.consume(collection.replace('Ŵ', 'Ú'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ļ', 'þ'));
		bh.consume(collection.containsKey('ê'));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('ű', 'ő'));
		bh.consume(collection.remove('Ā'));
		bh.consume(collection.containsKey('ť'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ƈ', 'È'));
		bh.consume(collection.replace('Ñ', 'ţ'));
		bh.consume(collection.containsKey('ű'));
		bh.consume(collection.containsKey('ã'));
		bh.consume(collection.remove('ā'));
		bh.consume(collection.replace('ć', 'ě'));
		bh.consume(collection.remove('Œ'));
		bh.consume(collection.remove('ł'));
		bh.consume(collection.get('×'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Ə', 'Ë'));
		bh.consume(collection.containsKey('Ń'));
		bh.consume(collection.containsKey('ś'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ł', 'Ĺ'));
		bh.consume(collection.replace('Ĕ', 'Ŕ'));
		bh.consume(collection.remove('į'));
		bh.consume(collection.containsKey('ú'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ů', 'Ē'));
		bh.consume(collection.replace('ÿ', 'ō'));
		bh.consume(collection.get('ģ'));
		bh.consume(collection.get('Ù'));
		bh.consume(collection.get('Ƃ'));
		bh.consume(collection.replace('Ž', 'ĝ'));
		bh.consume(collection.remove('į'));
		bh.consume(collection.get('Ÿ'));
		bh.consume(collection.replace('ĕ', 'Ĕ'));
		bh.consume(collection.replace('ŝ', 'Ő'));
		bh.consume(collection.get('í'));
		bh.consume(collection.containsKey('û'));
		bh.consume(collection.replace('ż', 'Ą'));
		bh.consume(collection.containsKey('ě'));
		bh.consume(collection.containsKey('Ě'));
		bh.consume(collection.containsKey('Ţ'));
		bh.consume(collection.get('Ć'));
		bh.consume(collection.remove('ó'));
		bh.consume(collection.replace('Ġ', 'Ą'));
		bh.consume(collection.values());
		bh.consume(collection.replace('Õ', 'Ź'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ŷ', 'Ĝ'));
		bh.consume(collection.values());
		bh.consume(collection.replace('Ě', 'ď'));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.get('Ŏ'));
		bh.consume(collection.replace('ã', 'đ'));
		bh.consume(collection.replace('Ƅ', 'Þ'));
		bh.consume(collection.get('ƈ'));
		bh.consume(collection.get('Ý'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('œ'));
		bh.consume(collection.containsKey('ç'));
		bh.consume(collection.replace('Ŕ', 'Č'));
		bh.consume(collection.remove('Ň'));
		bh.consume(collection.remove('Ų'));
		bh.consume(collection.remove('ſ'));
		bh.consume(collection.keySet());
		bh.consume(collection.remove('ŧ'));
		bh.consume(collection.replace('÷', 'ų'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ģ', 'ģ'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('ű'));
		bh.consume(collection.replace('Đ', 'Ĺ'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('Õ'));
		bh.consume(collection.replace('ą', 'Ő'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ĕ'));
		bh.consume(collection.remove('Ŭ'));
		bh.consume(collection.get('Ų'));
		bh.consume(collection.containsKey('ſ'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.get('ñ'));
		bh.consume(collection.replace('Ž', 'ż'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ų', 'Í'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ź'));
		bh.consume(collection.containsKey('Ę'));
		bh.consume(collection.containsKey('Š'));
		bh.consume(collection.replace('ŋ', 'Ŵ'));
		bh.consume(collection.containsKey('ŵ'));
		bh.consume(collection.replace('Ƌ', 'ï'));
		bh.consume(collection.containsKey('Ŀ'));
		bh.consume(collection.values());
		bh.consume(collection.get('Č'));
		bh.consume(collection.remove('ŵ'));
		bh.consume(collection.replace('ď', 'Č'));
		bh.consume(collection.get('ć'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('ď'));
		bh.consume(collection.replace('Ű', 'È'));
		bh.consume(collection.containsKey('ź'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Đ', 'â'));
		bh.consume(collection.get('Ō'));
		bh.consume(collection.replace('í', 'Ġ'));
		bh.consume(collection.remove('ķ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ı'));
		bh.consume(collection.containsKey('č'));
		bh.consume(collection.remove('×'));
		bh.consume(collection.replace('Ƃ', 'ô'));
		bh.consume(collection.replace('ŗ', 'ÿ'));
		bh.consume(collection.containsKey('Ó'));
		bh.consume(collection.get('ƌ'));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ñ'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Ë', 'Õ'));
		bh.consume(collection.get('ŵ'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ĩ', 'ß'));
		bh.consume(collection.get('ę'));
		bh.consume(collection.get('ň'));
		bh.consume(collection.get('Ń'));
		bh.consume(collection.containsKey('Ş'));
		bh.consume(collection.containsKey('İ'));
		bh.consume(collection.get('Ď'));
		bh.consume(collection.remove('Ă'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ć', 'ę'));
		bh.consume(collection.replace('Ɗ', 'æ'));
		bh.consume(collection.containsKey('Û'));
		bh.consume(collection.remove('Ð'));
		bh.consume(collection.replace('Ÿ', 'ī'));
		bh.consume(collection.get('Ə'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Š', 'ŕ'));
		bh.consume(collection.containsKey('ĉ'));
		bh.consume(collection.containsKey('Ŋ'));
		bh.consume(collection.remove('ú'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ů', 'Ż'));
		bh.consume(collection.containsKey('ï'));
		bh.consume(collection.remove('Š'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('Ƈ'));
		bh.consume(collection.replace('ś', 'Ş'));
		bh.consume(collection.replace('ņ', 'Ÿ'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ŭ', 'Ű'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ç'));
		bh.consume(collection.get('Ĉ'));
		bh.consume(collection.replace('Ĕ', 'ì'));
		bh.consume(collection.get('Ô'));
		bh.consume(collection.replace('Ş', 'Ü'));
		bh.consume(collection.replace('Ñ', 'ů'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ŀ', 'ĥ'));
		bh.consume(collection.get('ņ'));
		bh.consume(collection.replace('þ', 'ů'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ž', 'Ÿ'));
		bh.consume(collection.replace('Į', 'ğ'));
		bh.consume(collection.containsKey('Ó'));
		bh.consume(collection.containsKey('æ'));
		bh.consume(collection.values());
		bh.consume(collection.remove('ď'));
		bh.consume(collection.containsKey('ī'));
		bh.consume(collection.replace('Ŭ', 'Ă'));
		bh.consume(collection.containsKey('Ą'));
		bh.consume(collection.replace('Đ', 'ē'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.remove('Û'));
		bh.consume(collection.get('Õ'));
		bh.consume(collection.replace('ğ', 'Ǝ'));
		bh.consume(collection.containsKey('Ɗ'));
		bh.consume(collection.containsKey('Ə'));
		bh.consume(collection.get('ť'));
		bh.consume(collection.containsKey('ŉ'));
		bh.consume(collection.get('Ó'));
		bh.consume(collection.replace('ō', 'ħ'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.remove('ħ'));
		bh.consume(collection.get('Ü'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ÿ'));
		bh.consume(collection.remove('ā'));
		bh.consume(collection.containsKey('ś'));
		bh.consume(collection.containsKey('Ů'));
		bh.consume(collection.replace('ı', 'Ō'));
		bh.consume(collection.containsKey('Ƅ'));
		bh.consume(collection.containsKey('Ġ'));
		bh.consume(collection.containsKey('ÿ'));
		bh.consume(collection.values());
		bh.consume(collection.get('í'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ŕ'));
		bh.consume(collection.replace('Ĕ', 'ù'));
		bh.consume(collection.containsKey('Ɓ'));
		bh.consume(collection.containsKey('Û'));
		bh.consume(collection.values());
		bh.consume(collection.get('Œ'));
		bh.consume(collection.replace('Í', 'Ė'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ƈ', 'è'));
		bh.consume(collection.containsKey('ì'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('œ', 'ŏ'));
		bh.consume(collection.containsKey('Û'));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.get('Ł'));
		bh.consume(collection.keySet());
		bh.consume(collection.remove('Ł'));
		bh.consume(collection.get('Ě'));
		bh.consume(collection.containsKey('÷'));
		bh.consume(collection.containsKey('ç'));
		bh.consume(collection.replace('ŀ', 'į'));
		bh.consume(collection.get('Ż'));
		bh.consume(collection.get('Ę'));
		bh.consume(collection.remove('ß'));
		bh.consume(collection.get('ś'));
		bh.consume(collection.replace('ň', 'Ž'));
		bh.consume(collection.containsKey('š'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('č', 'ŏ'));
		bh.consume(collection.values());
		bh.consume(collection.get('ő'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ŋ'));
		bh.consume(collection.remove('î'));
		bh.consume(collection.values());
		bh.consume(collection.get('ð'));
		bh.consume(collection.values());
		bh.consume(collection.get('ý'));
		bh.consume(collection.get('ŭ'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.get('Ż'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ğ', 'ŭ'));
		bh.consume(collection.get('ù'));
		bh.consume(collection.replace('ƃ', 'ē'));
		bh.consume(collection.values());
		bh.consume(collection.replace('ı', 'ű'));
		bh.consume(collection.values());
		bh.consume(collection.replace('Ù', 'Û'));
		bh.consume(collection.containsKey('Ð'));
		bh.consume(collection.replace('ģ', 'Ő'));
		bh.consume(collection.get('Œ'));
		bh.consume(collection.replace('Ą', 'Ĭ'));
		bh.consume(collection.containsKey('È'));
		bh.consume(collection.replace('Ë', 'â'));
		bh.consume(collection.containsKey('ī'));
		bh.consume(collection.get('Ɓ'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Ɓ', 'ƌ'));
		bh.consume(collection.containsKey('Ŭ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ĕ'));
		bh.consume(collection.containsKey('ġ'));
		bh.consume(collection.remove('ś'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('ę'));
		bh.consume(collection.containsKey('Õ'));
		bh.consume(collection.containsKey('à'));
		bh.consume(collection.replace('Ž', 'ï'));
		bh.consume(collection.replace('Į', 'Ƅ'));
		bh.consume(collection.replace('Ĉ', 'ļ'));
		bh.consume(collection.replace('Ŧ', 'å'));
		bh.consume(collection.values());
		bh.consume(collection.replace('Ă', 'Ļ'));
		bh.consume(collection.values());
		bh.consume(collection.remove('Ý'));
		bh.consume(collection.replace('ė', 'Œ'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('Ņ'));
		bh.consume(collection.containsKey('Ă'));
		bh.consume(collection.replace('ƀ', 'Ż'));
		bh.consume(collection.containsKey('Ņ'));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get('ł'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get('×'));
		bh.consume(collection.replace('ħ', 'ó'));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace('ē', 'Ņ'));
		bh.consume(collection.replace('Ü', 'ò'));
		bh.consume(collection.replace('Ł', 'Ɗ'));
		bh.consume(collection.values());
		bh.consume(collection.replace('į', 'ũ'));
		bh.consume(collection.containsKey('į'));
		bh.consume(collection.containsKey('Õ'));
		bh.consume(collection.containsKey('ƈ'));
		bh.consume(collection.containsKey('ä'));
		bh.consume(collection.get('Į'));
		bh.consume(collection.containsKey('ĕ'));
		bh.consume(collection.replace('ŀ', 'ů'));
		bh.consume(collection.get('Ġ'));
		bh.consume(collection.containsKey('Ű'));
		bh.consume(collection.containsKey('Č'));
		bh.consume(collection.replace('Į', 'Ë'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ì', 'Ñ'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Ġ', 'Ŷ'));
		bh.consume(collection.remove('Ñ'));
		bh.consume(collection.get('ļ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('à'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('Ö', 'ě'));
		bh.consume(collection.replace('ż', 'ĳ'));
		bh.consume(collection.get('Ü'));
		bh.consume(collection.values());
		bh.consume(collection.replace('Ō', 'ï'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ĵ'));
		bh.consume(collection.containsKey('ū'));
		bh.consume(collection.containsKey('ĵ'));
		bh.consume(collection.replace('ť', 'ŵ'));
		bh.consume(collection.containsKey('ů'));
		bh.consume(collection.containsKey('ŵ'));
		bh.consume(collection.remove('Ł'));
		bh.consume(collection.remove('ŧ'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ă'));
		bh.consume(collection.get('è'));
		bh.consume(collection.values());
		bh.consume(collection.remove('ö'));
		bh.consume(collection.values());
		bh.consume(collection.remove('ƈ'));
		bh.consume(collection.containsKey('ŀ'));
		bh.consume(collection.containsKey('Ď'));
		bh.consume(collection.replace('ū', 'ų'));
		bh.consume(collection.remove('Š'));
		bh.consume(collection.keySet());
		bh.consume(collection.get('Ü'));
		bh.consume(collection.get('Ű'));
		bh.consume(collection.get('â'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.remove('ö'));
		bh.consume(collection.replace('Č', 'Ó'));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace('ĝ', 'ē'));
		bh.consume(collection.remove('Ë'));
		bh.consume(collection.replace('Ł', 'î'));
		bh.consume(collection.containsKey('Ą'));
		bh.consume(collection.containsKey('Ů'));
		bh.consume(collection.get('Ũ'));
		bh.consume(collection.get('Ĺ'));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ï'));
		bh.consume(collection.replace('Ġ', 'Ę'));
		bh.consume(collection.values());
		bh.consume(collection.containsKey('š'));
		bh.consume(collection.containsKey('Ý'));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace('ý', 'è'));
		bh.consume(collection.replace('ū', 'Ū'));
		bh.consume(collection.replace('Ý', 'â'));
		bh.consume(collection.keySet());
		bh.consume(collection.remove('ő'));
		bh.consume(collection.containsKey('ź'));
		bh.consume(collection.remove('Š'));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.containsKey('Ï'));
		bh.consume(collection.keySet());
		bh.consume(collection.replace('Ţ', 'Ř'));
		bh.consume(collection.containsKey('Ì'));
		bh.consume(collection.replace('Ĉ', 'Ð'));
		bh.consume(collection.replace('ô', 'Ő'));
		bh.consume(collection.get('ğ'));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey('ť'));
		bh.consume(collection.containsKey('ű'));
		bh.consume(collection.replace('ş', 'ā'));
		bh.consume(collection.replace('Ņ', 'Ğ'));
		bh.consume(collection.replace('Œ', 'ī'));
	}
}
