package com.adalbert;
import java.util.*;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.*;

@State(Scope.Benchmark)
public class J_Profile1AllMaps_JHashMap_20220429190539160 {
	java.util.HashMap<String, String> collection = new java.util.HashMap<>();
	@Setup(Level.Invocation)
	public void setupJHashMap() {
		collection = new java.util.HashMap<>();
		collection.put("ÖÖÖÖÖÖÖÖÖÖ", "ƌƌƌƌƌƌƌƌƌƌ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ŏŏŏŏŏŏŏŏŏŏ");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ľľľľľľľľľľ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ňňňňňňňňňň", "ææææææææææ");
		collection.put("īīīīīīīīīī", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ſſſſſſſſſſ", "űűűűűűűűűű");
		collection.put("ĪĪĪĪĪĪĪĪĪĪ", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ıııııııııı", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "ÑÑÑÑÑÑÑÑÑÑ");
		collection.put("õõõõõõõõõõ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ïïïïïïïïïï");
		collection.put("îîîîîîîîîî", "ĀĀĀĀĀĀĀĀĀĀ");
		collection.put("ķķķķķķķķķķ", "ääääääääää");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("įįįįįįįįįį", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("śśśśśśśśśś", "ăăăăăăăăăă");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "úúúúúúúúúú");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "èèèèèèèèèè");
		collection.put("áááááááááá", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ČČČČČČČČČČ", "èèèèèèèèèè");
		collection.put("ſſſſſſſſſſ", "āāāāāāāāāā");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "õõõõõõõõõõ");
		collection.put("óóóóóóóóóó", "ßßßßßßßßßß");
		collection.put("øøøøøøøøøø", "įįįįįįįįįį");
		collection.put("ìììììììììì", "ŬŬŬŬŬŬŬŬŬŬ");
		collection.put("šššššššššš", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ġġġġġġġġġġ", "œœœœœœœœœœ");
		collection.put("îîîîîîîîîî", "îîîîîîîîîî");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ĦĦĦĦĦĦĦĦĦĦ", "ââââââââââ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("ïïïïïïïïïï", "ŒŒŒŒŒŒŒŒŒŒ");
		collection.put("ġġġġġġġġġġ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("ÙÙÙÙÙÙÙÙÙÙ", "ƃƃƃƃƃƃƃƃƃƃ");
		collection.put("ÈÈÈÈÈÈÈÈÈÈ", "úúúúúúúúúú");
		collection.put("ìììììììììì", "ÓÓÓÓÓÓÓÓÓÓ");
		collection.put("ĶĶĶĶĶĶĶĶĶĶ", "ŀŀŀŀŀŀŀŀŀŀ");
		collection.put("üüüüüüüüüü", "ħħħħħħħħħħ");
		collection.put("łłłłłłłłłł", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ţţţţţţţţţţ", "ØØØØØØØØØØ");
		collection.put("õõõõõõõõõõ", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ĉĉĉĉĉĉĉĉĉĉ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ÓÓÓÓÓÓÓÓÓÓ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("āāāāāāāāāā", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ƁƁƁƁƁƁƁƁƁƁ", "îîîîîîîîîî");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ŶŶŶŶŶŶŶŶŶŶ", "ûûûûûûûûûû");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ĒĒĒĒĒĒĒĒĒĒ");
		collection.put("ſſſſſſſſſſ", "ġġġġġġġġġġ");
		collection.put("ċċċċċċċċċċ", "òòòòòòòòòò");
		collection.put("ĞĞĞĞĞĞĞĞĞĞ", "ëëëëëëëëëë");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ôôôôôôôôôô");
		collection.put("ŎŎŎŎŎŎŎŎŎŎ", "ęęęęęęęęęę");
		collection.put("ØØØØØØØØØØ", "ľľľľľľľľľľ");
		collection.put("ÉÉÉÉÉÉÉÉÉÉ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("űűűűűűűűűű", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ťťťťťťťťťť", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("ŇŇŇŇŇŇŇŇŇŇ", "××××××××××");
		collection.put("űűűűűűűűűű", "õõõõõõõõõõ");
		collection.put("ČČČČČČČČČČ", "ìììììììììì");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "øøøøøøøøøø");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "įįįįįįįįįį");
		collection.put("ĉĉĉĉĉĉĉĉĉĉ", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "òòòòòòòòòò");
		collection.put("ľľľľľľľľľľ", "ÓÓÓÓÓÓÓÓÓÓ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ňňňňňňňňňň");
		collection.put("ìììììììììì", "óóóóóóóóóó");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ďďďďďďďďďď", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("øøøøøøøøøø", "òòòòòòòòòò");
		collection.put("ťťťťťťťťťť", "ĴĴĴĴĴĴĴĴĴĴ");
		collection.put("ĉĉĉĉĉĉĉĉĉĉ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ÖÖÖÖÖÖÖÖÖÖ");
		collection.put("ļļļļļļļļļļ", "űűűűűűűűűű");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "××××××××××");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ãããããããããã");
		collection.put("þþþþþþþþþþ", "ââââââââââ");
		collection.put("čččččččččč", "ƃƃƃƃƃƃƃƃƃƃ");
		collection.put("ØØØØØØØØØØ", "ľľľľľľľľľľ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ŴŴŴŴŴŴŴŴŴŴ", "èèèèèèèèèè");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ûûûûûûûûûû");
		collection.put("ĸĸĸĸĸĸĸĸĸĸ", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("śśśśśśśśśś", "ƅƅƅƅƅƅƅƅƅƅ");
		collection.put("ŭŭŭŭŭŭŭŭŭŭ", "òòòòòòòòòò");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ŀŀŀŀŀŀŀŀŀŀ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ťťťťťťťťťť", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ťťťťťťťťťť", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "āāāāāāāāāā");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ïïïïïïïïïï");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ĚĚĚĚĚĚĚĚĚĚ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "öööööööööö");
		collection.put("ŧŧŧŧŧŧŧŧŧŧ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ħħħħħħħħħħ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "çççççççççç");
		collection.put("ųųųųųųųųųų", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ųųųųųųųųųų", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ŸŸŸŸŸŸŸŸŸŸ");
		collection.put("źźźźźźźźźź", "ŵŵŵŵŵŵŵŵŵŵ");
		collection.put("ţţţţţţţţţţ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ƃƃƃƃƃƃƃƃƃƃ");
		collection.put("şşşşşşşşşş", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("ŪŪŪŪŪŪŪŪŪŪ", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ĐĐĐĐĐĐĐĐĐĐ", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ĚĚĚĚĚĚĚĚĚĚ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ŴŴŴŴŴŴŴŴŴŴ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ûûûûûûûûûû", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ĒĒĒĒĒĒĒĒĒĒ", "ŸŸŸŸŸŸŸŸŸŸ");
		collection.put("ćććććććććć", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "ĴĴĴĴĴĴĴĴĴĴ");
		collection.put("įįįįįįįįįį", "šššššššššš");
		collection.put("ÕÕÕÕÕÕÕÕÕÕ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ÊÊÊÊÊÊÊÊÊÊ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "źźźźźźźźźź");
		collection.put("ĭĭĭĭĭĭĭĭĭĭ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ņņņņņņņņņņ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ëëëëëëëëëë", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ġġġġġġġġġġ", "ŴŴŴŴŴŴŴŴŴŴ");
		collection.put("ĄĄĄĄĄĄĄĄĄĄ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ěěěěěěěěěě", "ŁŁŁŁŁŁŁŁŁŁ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ųųųųųųųųųų");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "ũũũũũũũũũũ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "řřřřřřřřřř");
		collection.put("ĄĄĄĄĄĄĄĄĄĄ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ùùùùùùùùùù", "žžžžžžžžžž");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ĔĔĔĔĔĔĔĔĔĔ");
		collection.put("àààààààààà", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ġġġġġġġġġġ", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ÞÞÞÞÞÞÞÞÞÞ", "õõõõõõõõõõ");
		collection.put("ČČČČČČČČČČ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("įįįįįįįįįį", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("þþþþþþþþþþ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ƋƋƋƋƋƋƋƋƋƋ", "êêêêêêêêêê");
		collection.put("ļļļļļļļļļļ", "œœœœœœœœœœ");
		collection.put("ŇŇŇŇŇŇŇŇŇŇ", "ôôôôôôôôôô");
		collection.put("ſſſſſſſſſſ", "ńńńńńńńńńń");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "ēēēēēēēēēē");
		collection.put("ýýýýýýýýýý", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "łłłłłłłłłł");
		collection.put("ľľľľľľľľľľ", "ĚĚĚĚĚĚĚĚĚĚ");
		collection.put("êêêêêêêêêê", "įįįįįįįįįį");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("źźźźźźźźźź", "ėėėėėėėėėė");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "úúúúúúúúúú");
		collection.put("śśśśśśśśśś", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("şşşşşşşşşş", "ġġġġġġġġġġ");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "řřřřřřřřřř");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ćććććććććć", "öööööööööö");
		collection.put("źźźźźźźźźź", "ĀĀĀĀĀĀĀĀĀĀ");
		collection.put("ââââââââââ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ęęęęęęęęęę", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "đđđđđđđđđđ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ÈÈÈÈÈÈÈÈÈÈ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("żżżżżżżżżż", "ĸĸĸĸĸĸĸĸĸĸ");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ĚĚĚĚĚĚĚĚĚĚ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ńńńńńńńńńń", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("ññññññññññ", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ââââââââââ", "ėėėėėėėėėė");
		collection.put("ĽĽĽĽĽĽĽĽĽĽ", "ŐŐŐŐŐŐŐŐŐŐ");
		collection.put("××××××××××", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ÏÏÏÏÏÏÏÏÏÏ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("īīīīīīīīīī", "ƃƃƃƃƃƃƃƃƃƃ");
		collection.put("ĨĨĨĨĨĨĨĨĨĨ", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "şşşşşşşşşş");
		collection.put("ĶĶĶĶĶĶĶĶĶĶ", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("åååååååååå", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ōōōōōōōōōō", "ťťťťťťťťťť");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("ÐÐÐÐÐÐÐÐÐÐ", "ěěěěěěěěěě");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "òòòòòòòòòò");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ėėėėėėėėėė");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ääääääääää");
		collection.put("ŰŰŰŰŰŰŰŰŰŰ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ųųųųųųųųųų", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ėėėėėėėėėė", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ĽĽĽĽĽĽĽĽĽĽ", "ËËËËËËËËËË");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ŋŋŋŋŋŋŋŋŋŋ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ŇŇŇŇŇŇŇŇŇŇ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ųųųųųųųųųų");
		collection.put("××××××××××", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("éééééééééé", "ĲĲĲĲĲĲĲĲĲĲ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ÒÒÒÒÒÒÒÒÒÒ", "ėėėėėėėėėė");
		collection.put("łłłłłłłłłł", "łłłłłłłłłł");
		collection.put("őőőőőőőőőő", "ųųųųųųųųųų");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ōōōōōōōōōō");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ääääääääää", "şşşşşşşşşş");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ţţţţţţţţţţ");
		collection.put("ĸĸĸĸĸĸĸĸĸĸ", "éééééééééé");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "ĀĀĀĀĀĀĀĀĀĀ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ĈĈĈĈĈĈĈĈĈĈ", "ïïïïïïïïïï");
		collection.put("üüüüüüüüüü", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ØØØØØØØØØØ", "ŢŢŢŢŢŢŢŢŢŢ");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "űűűűűűűűűű");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ąąąąąąąąąą");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("ķķķķķķķķķķ", "ââââââââââ");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ðððððððððð");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("çççççççççç", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ìììììììììì", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ĳĳĳĳĳĳĳĳĳĳ", "þþþþþþþþþþ");
		collection.put("ňňňňňňňňňň", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "őőőőőőőőőő");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ìììììììììì", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("řřřřřřřřřř", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ĀĀĀĀĀĀĀĀĀĀ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "óóóóóóóóóó");
		collection.put("××××××××××", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("şşşşşşşşşş", "ăăăăăăăăăă");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ŜŜŜŜŜŜŜŜŜŜ", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("źźźźźźźźźź", "ġġġġġġġġġġ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ŒŒŒŒŒŒŒŒŒŒ");
		collection.put("ćććććććććć", "ëëëëëëëëëë");
		collection.put("ññññññññññ", "ÎÎÎÎÎÎÎÎÎÎ");
		collection.put("ÙÙÙÙÙÙÙÙÙÙ", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ſſſſſſſſſſ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ƎƎƎƎƎƎƎƎƎƎ");
		collection.put("ţţţţţţţţţţ", "ƁƁƁƁƁƁƁƁƁƁ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "íííííííííí");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ĚĚĚĚĚĚĚĚĚĚ");
		collection.put("šššššššššš", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ăăăăăăăăăă", "ąąąąąąąąąą");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "ŬŬŬŬŬŬŬŬŬŬ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "şşşşşşşşşş");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ÙÙÙÙÙÙÙÙÙÙ");
		collection.put("áááááááááá", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ĻĻĻĻĻĻĻĻĻĻ", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ťťťťťťťťťť", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ũũũũũũũũũũ");
		collection.put("ţţţţţţţţţţ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("õõõõõõõõõõ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ƁƁƁƁƁƁƁƁƁƁ", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "üüüüüüüüüü");
		collection.put("ãããããããããã", "ųųųųųųųųųų");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ŏŏŏŏŏŏŏŏŏŏ", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ÖÖÖÖÖÖÖÖÖÖ", "ħħħħħħħħħħ");
		collection.put("öööööööööö", "įįįįįįįįįį");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ťťťťťťťťťť");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ċċċċċċċċċċ");
		collection.put("ōōōōōōōōōō", "ČČČČČČČČČČ");
		collection.put("ÎÎÎÎÎÎÎÎÎÎ", "ķķķķķķķķķķ");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "āāāāāāāāāā");
		collection.put("ÎÎÎÎÎÎÎÎÎÎ", "éééééééééé");
		collection.put("ļļļļļļļļļļ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("čččččččččč", "ãããããããããã");
		collection.put("ææææææææææ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ŉŉŉŉŉŉŉŉŉŉ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ŎŎŎŎŎŎŎŎŎŎ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ëëëëëëëëëë", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("êêêêêêêêêê", "İİİİİİİİİİ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ġġġġġġġġġġ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ċċċċċċċċċċ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ŴŴŴŴŴŴŴŴŴŴ", "ÐÐÐÐÐÐÐÐÐÐ");
		collection.put("ÖÖÖÖÖÖÖÖÖÖ", "üüüüüüüüüü");
		collection.put("ŪŪŪŪŪŪŪŪŪŪ", "ÙÙÙÙÙÙÙÙÙÙ");
		collection.put("ĵĵĵĵĵĵĵĵĵĵ", "ąąąąąąąąąą");
		collection.put("śśśśśśśśśś", "ġġġġġġġġġġ");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ăăăăăăăăăă");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ūūūūūūūūūū");
		collection.put("đđđđđđđđđđ", "ØØØØØØØØØØ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("ÍÍÍÍÍÍÍÍÍÍ", "ğğğğğğğğğğ");
		collection.put("ÞÞÞÞÞÞÞÞÞÞ", "ńńńńńńńńńń");
		collection.put("ùùùùùùùùùù", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("òòòòòòòòòò", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("řřřřřřřřřř", "ÔÔÔÔÔÔÔÔÔÔ");
		collection.put("ûûûûûûûûûû", "ŉŉŉŉŉŉŉŉŉŉ");
		collection.put("ſſſſſſſſſſ", "ŢŢŢŢŢŢŢŢŢŢ");
		collection.put("ýýýýýýýýýý", "şşşşşşşşşş");
		collection.put("ƈƈƈƈƈƈƈƈƈƈ", "ðððððððððð");
		collection.put("áááááááááá", "ļļļļļļļļļļ");
		collection.put("ññññññññññ", "ŒŒŒŒŒŒŒŒŒŒ");
		collection.put("āāāāāāāāāā", "ļļļļļļļļļļ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ĔĔĔĔĔĔĔĔĔĔ");
		collection.put("ĸĸĸĸĸĸĸĸĸĸ", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("ūūūūūūūūūū", "íííííííííí");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ķķķķķķķķķķ", "þþþþþþþþþþ");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "õõõõõõõõõõ");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "àààààààààà");
		collection.put("ăăăăăăăăăă", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ļļļļļļļļļļ", "éééééééééé");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ěěěěěěěěěě");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "éééééééééé");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "øøøøøøøøøø");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ðððððððððð", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("ĚĚĚĚĚĚĚĚĚĚ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ìììììììììì", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "êêêêêêêêêê");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("ïïïïïïïïïï", "ƌƌƌƌƌƌƌƌƌƌ");
		collection.put("ıııııııııı", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ƄƄƄƄƄƄƄƄƄƄ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("óóóóóóóóóó", "ýýýýýýýýýý");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ĹĹĹĹĹĹĹĹĹĹ");
		collection.put("ÏÏÏÏÏÏÏÏÏÏ", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ýýýýýýýýýý", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "÷÷÷÷÷÷÷÷÷÷");
		collection.put("đđđđđđđđđđ", "ƎƎƎƎƎƎƎƎƎƎ");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("ßßßßßßßßßß", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("áááááááááá", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ĖĖĖĖĖĖĖĖĖĖ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ňňňňňňňňňň", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("ħħħħħħħħħħ", "įįįįįįįįįį");
		collection.put("āāāāāāāāāā", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("śśśśśśśśśś", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ĿĿĿĿĿĿĿĿĿĿ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ÉÉÉÉÉÉÉÉÉÉ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ŎŎŎŎŎŎŎŎŎŎ", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ħħħħħħħħħħ");
		collection.put("ýýýýýýýýýý", "ĲĲĲĲĲĲĲĲĲĲ");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ħħħħħħħħħħ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ääääääääää", "ſſſſſſſſſſ");
		collection.put("ĿĿĿĿĿĿĿĿĿĿ", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("śśśśśśśśśś", "łłłłłłłłłł");
		collection.put("öööööööööö", "űűűűűűűűűű");
		collection.put("ääääääääää", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ïïïïïïïïïï", "ėėėėėėėėėė");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ĨĨĨĨĨĨĨĨĨĨ", "œœœœœœœœœœ");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ĉĉĉĉĉĉĉĉĉĉ", "ċċċċċċċċċċ");
		collection.put("ŜŜŜŜŜŜŜŜŜŜ", "ğğğğğğğğğğ");
		collection.put("ďďďďďďďďďď", "œœœœœœœœœœ");
		collection.put("ſſſſſſſſſſ", "ýýýýýýýýýý");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ķķķķķķķķķķ", "ĹĹĹĹĹĹĹĹĹĹ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ļļļļļļļļļļ", "ŀŀŀŀŀŀŀŀŀŀ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "ññññññññññ");
		collection.put("ÓÓÓÓÓÓÓÓÓÓ", "ėėėėėėėėėė");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ČČČČČČČČČČ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ĐĐĐĐĐĐĐĐĐĐ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ŖŖŖŖŖŖŖŖŖŖ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ōōōōōōōōōō", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("žžžžžžžžžž", "ääääääääää");
		collection.put("čččččččččč", "ČČČČČČČČČČ");
		collection.put("üüüüüüüüüü", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("çççççççççç", "××××××××××");
		collection.put("ïïïïïïïïïï", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ßßßßßßßßßß");
		collection.put("ÙÙÙÙÙÙÙÙÙÙ", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("íííííííííí", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("ìììììììììì", "ąąąąąąąąąą");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "óóóóóóóóóó");
		collection.put("ïïïïïïïïïï", "ùùùùùùùùùù");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ãããããããããã", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ÊÊÊÊÊÊÊÊÊÊ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ćććććććććć", "ČČČČČČČČČČ");
		collection.put("þþþþþþþþþþ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ññññññññññ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ćććććććććć", "áááááááááá");
		collection.put("ţţţţţţţţţţ", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ĪĪĪĪĪĪĪĪĪĪ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ŽŽŽŽŽŽŽŽŽŽ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ŧŧŧŧŧŧŧŧŧŧ", "āāāāāāāāāā");
		collection.put("ĳĳĳĳĳĳĳĳĳĳ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ŤŤŤŤŤŤŤŤŤŤ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ƄƄƄƄƄƄƄƄƄƄ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ĒĒĒĒĒĒĒĒĒĒ", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("ÖÖÖÖÖÖÖÖÖÖ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ĐĐĐĐĐĐĐĐĐĐ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ññññññññññ");
		collection.put("òòòòòòòòòò", "ÎÎÎÎÎÎÎÎÎÎ");
		collection.put("ÙÙÙÙÙÙÙÙÙÙ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ňňňňňňňňňň", "ŦŦŦŦŦŦŦŦŦŦ");
		collection.put("āāāāāāāāāā", "ġġġġġġġġġġ");
		collection.put("ĭĭĭĭĭĭĭĭĭĭ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ãããããããããã", "ūūūūūūūūūū");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("ăăăăăăăăăă", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("ĦĦĦĦĦĦĦĦĦĦ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ââââââââââ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "çççççççççç");
		collection.put("űűűűűűűűűű", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ÙÙÙÙÙÙÙÙÙÙ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ėėėėėėėėėė", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ðððððððððð");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "îîîîîîîîîî");
		collection.put("óóóóóóóóóó", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ũũũũũũũũũũ", "žžžžžžžžžž");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ıııııııııı", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ţţţţţţţţţţ", "ůůůůůůůůůů");
		collection.put("şşşşşşşşşş", "ċċċċċċċċċċ");
		collection.put("ðððððððððð", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("ËËËËËËËËËË", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("ĵĵĵĵĵĵĵĵĵĵ", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "įįįįįįįįįį");
		collection.put("ÊÊÊÊÊÊÊÊÊÊ", "ææææææææææ");
		collection.put("ĚĚĚĚĚĚĚĚĚĚ", "ÔÔÔÔÔÔÔÔÔÔ");
		collection.put("øøøøøøøøøø", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ĄĄĄĄĄĄĄĄĄĄ", "ŠŠŠŠŠŠŠŠŠŠ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ËËËËËËËËËË");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "ĒĒĒĒĒĒĒĒĒĒ");
		collection.put("ŔŔŔŔŔŔŔŔŔŔ", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("îîîîîîîîîî", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ôôôôôôôôôô", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ØØØØØØØØØØ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "íííííííííí");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("ġġġġġġġġġġ", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ûûûûûûûûûû");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ťťťťťťťťťť", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ÈÈÈÈÈÈÈÈÈÈ", "ſſſſſſſſſſ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("ƁƁƁƁƁƁƁƁƁƁ", "ŐŐŐŐŐŐŐŐŐŐ");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("íííííííííí", "ļļļļļļļļļļ");
		collection.put("ńńńńńńńńńń", "ØØØØØØØØØØ");
		collection.put("úúúúúúúúúú", "××××××××××");
		collection.put("ļļļļļļļļļļ", "ûûûûûûûûûû");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ńńńńńńńńńń", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("ŤŤŤŤŤŤŤŤŤŤ", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ïïïïïïïïïï", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ßßßßßßßßßß");
		collection.put("žžžžžžžžžž", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("àààààààààà", "ææææææææææ");
		collection.put("šššššššššš", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ÑÑÑÑÑÑÑÑÑÑ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ğğğğğğğğğğ", "ýýýýýýýýýý");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ØØØØØØØØØØ");
		collection.put("ĻĻĻĻĻĻĻĻĻĻ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ţţţţţţţţţţ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ēēēēēēēēēē", "úúúúúúúúúú");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ƅƅƅƅƅƅƅƅƅƅ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ääääääääää");
		collection.put("éééééééééé", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ŇŇŇŇŇŇŇŇŇŇ", "řřřřřřřřřř");
		collection.put("ÈÈÈÈÈÈÈÈÈÈ", "ŤŤŤŤŤŤŤŤŤŤ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ƂƂƂƂƂƂƂƂƂƂ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ſſſſſſſſſſ", "ğğğğğğğğğğ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "žžžžžžžžžž");
		collection.put("ůůůůůůůůůů", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("ßßßßßßßßßß", "ſſſſſſſſſſ");
		collection.put("ÐÐÐÐÐÐÐÐÐÐ", "ýýýýýýýýýý");
		collection.put("ũũũũũũũũũũ", "ąąąąąąąąąą");
		collection.put("ĈĈĈĈĈĈĈĈĈĈ", "ēēēēēēēēēē");
		collection.put("ÞÞÞÞÞÞÞÞÞÞ", "āāāāāāāāāā");
		collection.put("ĨĨĨĨĨĨĨĨĨĨ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("íííííííííí", "īīīīīīīīīī");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ĹĹĹĹĹĹĹĹĹĹ");
		collection.put("ţţţţţţţţţţ", "ßßßßßßßßßß");
		collection.put("øøøøøøøøøø", "ćććććććććć");
		collection.put("ôôôôôôôôôô", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ġġġġġġġġġġ");
		collection.put("ìììììììììì", "ââââââââââ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ťťťťťťťťťť", "ŵŵŵŵŵŵŵŵŵŵ");
		collection.put("łłłłłłłłłł", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "ŗŗŗŗŗŗŗŗŗŗ");
		collection.put("űűűűűűűűűű", "ØØØØØØØØØØ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ŎŎŎŎŎŎŎŎŎŎ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ùùùùùùùùùù");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ääääääääää");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ļļļļļļļļļļ", "õõõõõõõõõõ");
		collection.put("ĵĵĵĵĵĵĵĵĵĵ", "řřřřřřřřřř");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ìììììììììì");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ğğğğğğğğğğ");
		collection.put("ĞĞĞĞĞĞĞĞĞĞ", "ÖÖÖÖÖÖÖÖÖÖ");
		collection.put("ÉÉÉÉÉÉÉÉÉÉ", "ÖÖÖÖÖÖÖÖÖÖ");
		collection.put("ïïïïïïïïïï", "ìììììììììì");
		collection.put("ŜŜŜŜŜŜŜŜŜŜ", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "čččččččččč");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("œœœœœœœœœœ", "çççççççççç");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "îîîîîîîîîî");
		collection.put("űűűűűűűűűű", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ŏŏŏŏŏŏŏŏŏŏ", "ìììììììììì");
		collection.put("øøøøøøøøøø", "żżżżżżżżżż");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "ãããããããããã");
		collection.put("űűűűűűűűűű", "šššššššššš");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ââââââââââ", "åååååååååå");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ľľľľľľľľľľ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ţţţţţţţţţţ");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ææææææææææ", "ſſſſſſſſſſ");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ùùùùùùùùùù");
		collection.put("ėėėėėėėėėė", "śśśśśśśśśś");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("ļļļļļļļļļļ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("êêêêêêêêêê", "ŃŃŃŃŃŃŃŃŃŃ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "áááááááááá");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "õõõõõõõõõõ");
		collection.put("ćććććććććć", "ńńńńńńńńńń");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("œœœœœœœœœœ", "ƃƃƃƃƃƃƃƃƃƃ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("őőőőőőőőőő", "õõõõõõõõõõ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ðððððððððð");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "đđđđđđđđđđ");
		collection.put("šššššššššš", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ćććććććććć", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ÑÑÑÑÑÑÑÑÑÑ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ÈÈÈÈÈÈÈÈÈÈ", "įįįįįįįįįį");
		collection.put("ņņņņņņņņņņ", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("œœœœœœœœœœ", "żżżżżżżżżż");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ïïïïïïïïïï");
		collection.put("úúúúúúúúúú", "ññññññññññ");
		collection.put("ÉÉÉÉÉÉÉÉÉÉ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("ũũũũũũũũũũ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ĄĄĄĄĄĄĄĄĄĄ", "ěěěěěěěěěě");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ƌƌƌƌƌƌƌƌƌƌ");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "žžžžžžžžžž");
		collection.put("üüüüüüüüüü", "čččččččččč");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ĴĴĴĴĴĴĴĴĴĴ");
		collection.put("ćććććććććć", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ŃŃŃŃŃŃŃŃŃŃ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "èèèèèèèèèè");
		collection.put("ſſſſſſſſſſ", "ĒĒĒĒĒĒĒĒĒĒ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "şşşşşşşşşş");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "üüüüüüüüüü");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ÐÐÐÐÐÐÐÐÐÐ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("öööööööööö", "ģģģģģģģģģģ");
		collection.put("ŠŠŠŠŠŠŠŠŠŠ", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ěěěěěěěěěě", "ĖĖĖĖĖĖĖĖĖĖ");
		collection.put("ĶĶĶĶĶĶĶĶĶĶ", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ĒĒĒĒĒĒĒĒĒĒ");
		collection.put("źźźźźźźźźź", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ëëëëëëëëëë", "ŤŤŤŤŤŤŤŤŤŤ");
		collection.put("ŭŭŭŭŭŭŭŭŭŭ", "ÊÊÊÊÊÊÊÊÊÊ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "öööööööööö");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ņņņņņņņņņņ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ŠŠŠŠŠŠŠŠŠŠ");
		collection.put("üüüüüüüüüü", "ōōōōōōōōōō");
		collection.put("ďďďďďďďďďď", "ƁƁƁƁƁƁƁƁƁƁ");
		collection.put("ıııııııııı", "ðððððððððð");
		collection.put("ąąąąąąąąąą", "ßßßßßßßßßß");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "ƊƊƊƊƊƊƊƊƊƊ");
		collection.put("ĽĽĽĽĽĽĽĽĽĽ", "ĠĠĠĠĠĠĠĠĠĠ");
		collection.put("óóóóóóóóóó", "ŉŉŉŉŉŉŉŉŉŉ");
		collection.put("ƂƂƂƂƂƂƂƂƂƂ", "éééééééééé");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("śśśśśśśśśś", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ìììììììììì", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("ŠŠŠŠŠŠŠŠŠŠ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ŤŤŤŤŤŤŤŤŤŤ");
		collection.put("ƁƁƁƁƁƁƁƁƁƁ", "ææææææææææ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ŭŭŭŭŭŭŭŭŭŭ", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "òòòòòòòòòò");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("àààààààààà", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ŦŦŦŦŦŦŦŦŦŦ");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ƆƆƆƆƆƆƆƆƆƆ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ťťťťťťťťťť", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "ŠŠŠŠŠŠŠŠŠŠ");
		collection.put("ññññññññññ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "źźźźźźźźźź");
		collection.put("İİİİİİİİİİ", "ŁŁŁŁŁŁŁŁŁŁ");
		collection.put("óóóóóóóóóó", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("İİİİİİİİİİ", "ċċċċċċċċċċ");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "üüüüüüüüüü");
		collection.put("ůůůůůůůůůů", "ġġġġġġġġġġ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "œœœœœœœœœœ");
		collection.put("čččččččččč", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ľľľľľľľľľľ");
		collection.put("įįįįįįįįįį", "ąąąąąąąąąą");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("ČČČČČČČČČČ", "ņņņņņņņņņņ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "óóóóóóóóóó");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ċċċċċċċċċċ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "śśśśśśśśśś");
		collection.put("ĳĳĳĳĳĳĳĳĳĳ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ÉÉÉÉÉÉÉÉÉÉ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ƈƈƈƈƈƈƈƈƈƈ", "ľľľľľľľľľľ");
		collection.put("ðððððððððð", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("êêêêêêêêêê", "ĽĽĽĽĽĽĽĽĽĽ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("đđđđđđđđđđ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ðððððððððð");
		collection.put("ăăăăăăăăăă", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ţţţţţţţţţţ", "ÛÛÛÛÛÛÛÛÛÛ");
		collection.put("ĪĪĪĪĪĪĪĪĪĪ", "ŒŒŒŒŒŒŒŒŒŒ");
		collection.put("ðððððððððð", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ĐĐĐĐĐĐĐĐĐĐ", "ƌƌƌƌƌƌƌƌƌƌ");
		collection.put("ļļļļļļļļļļ", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ËËËËËËËËËË");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("ÕÕÕÕÕÕÕÕÕÕ", "ņņņņņņņņņņ");
		collection.put("ıııııııııı", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("øøøøøøøøøø", "şşşşşşşşşş");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "řřřřřřřřřř");
		collection.put("ĪĪĪĪĪĪĪĪĪĪ", "ƍƍƍƍƍƍƍƍƍƍ");
		collection.put("ŪŪŪŪŪŪŪŪŪŪ", "ēēēēēēēēēē");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "îîîîîîîîîî");
		collection.put("ŋŋŋŋŋŋŋŋŋŋ", "ŉŉŉŉŉŉŉŉŉŉ");
		collection.put("įįįįįįįįįį", "ññññññññññ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "įįįįįįįįįį");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("řřřřřřřřřř", "ŒŒŒŒŒŒŒŒŒŒ");
		collection.put("ŶŶŶŶŶŶŶŶŶŶ", "ŵŵŵŵŵŵŵŵŵŵ");
		collection.put("ÓÓÓÓÓÓÓÓÓÓ", "ĔĔĔĔĔĔĔĔĔĔ");
		collection.put("ůůůůůůůůůů", "ŇŇŇŇŇŇŇŇŇŇ");
		collection.put("žžžžžžžžžž", "ńńńńńńńńńń");
		collection.put("ņņņņņņņņņņ", "ÊÊÊÊÊÊÊÊÊÊ");
		collection.put("ŧŧŧŧŧŧŧŧŧŧ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ŞŞŞŞŞŞŞŞŞŞ", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ŘŘŘŘŘŘŘŘŘŘ");
		collection.put("óóóóóóóóóó", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ĆĆĆĆĆĆĆĆĆĆ");
		collection.put("ûûûûûûûûûû", "þþþþþþþþþþ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "íííííííííí");
		collection.put("żżżżżżżżżż", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("ķķķķķķķķķķ", "şşşşşşşşşş");
		collection.put("čččččččččč", "ăăăăăăăăăă");
		collection.put("÷÷÷÷÷÷÷÷÷÷", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ÉÉÉÉÉÉÉÉÉÉ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "ŢŢŢŢŢŢŢŢŢŢ");
		collection.put("ėėėėėėėėėė", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("ūūūūūūūūūū", "ääääääääää");
		collection.put("ćććććććććć", "īīīīīīīīīī");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ėėėėėėėėėė");
		collection.put("îîîîîîîîîî", "ŗŗŗŗŗŗŗŗŗŗ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ûûûûûûûûûû");
		collection.put("źźźźźźźźźź", "ČČČČČČČČČČ");
		collection.put("èèèèèèèèèè", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ųųųųųųųųųų", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ČČČČČČČČČČ", "īīīīīīīīīī");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ĖĖĖĖĖĖĖĖĖĖ");
		collection.put("ĮĮĮĮĮĮĮĮĮĮ", "ůůůůůůůůůů");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ïïïïïïïïïï");
		collection.put("õõõõõõõõõõ", "ññññññññññ");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "İİİİİİİİİİ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ææææææææææ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("éééééééééé", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("şşşşşşşşşş", "ŋŋŋŋŋŋŋŋŋŋ");
		collection.put("áááááááááá", "žžžžžžžžžž");
		collection.put("śśśśśśśśśś", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ōōōōōōōōōō", "ůůůůůůůůůů");
		collection.put("ÒÒÒÒÒÒÒÒÒÒ", "ýýýýýýýýýý");
		collection.put("ĭĭĭĭĭĭĭĭĭĭ", "ųųųųųųųųųų");
		collection.put("ċċċċċċċċċċ", "ňňňňňňňňňň");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("œœœœœœœœœœ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ìììììììììì", "ĆĆĆĆĆĆĆĆĆĆ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ùùùùùùùùùù", "ÎÎÎÎÎÎÎÎÎÎ");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ĔĔĔĔĔĔĔĔĔĔ");
		collection.put("ĞĞĞĞĞĞĞĞĞĞ", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("ƄƄƄƄƄƄƄƄƄƄ", "ěěěěěěěěěě");
		collection.put("źźźźźźźźźź", "ŁŁŁŁŁŁŁŁŁŁ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "ØØØØØØØØØØ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ħħħħħħħħħħ");
		collection.put("ıııııııııı", "ĴĴĴĴĴĴĴĴĴĴ");
		collection.put("ÎÎÎÎÎÎÎÎÎÎ", "ļļļļļļļļļļ");
		collection.put("ƈƈƈƈƈƈƈƈƈƈ", "ľľľľľľľľľľ");
		collection.put("čččččččččč", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("õõõõõõõõõõ", "ħħħħħħħħħħ");
		collection.put("ĦĦĦĦĦĦĦĦĦĦ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("èèèèèèèèèè", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ĮĮĮĮĮĮĮĮĮĮ", "ææææææææææ");
		collection.put("óóóóóóóóóó", "ăăăăăăăăăă");
		collection.put("řřřřřřřřřř", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("űűűűűűűűűű", "đđđđđđđđđđ");
		collection.put("õõõõõõõõõõ", "öööööööööö");
		collection.put("ìììììììììì", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ƆƆƆƆƆƆƆƆƆƆ", "ìììììììììì");
		collection.put("òòòòòòòòòò", "ĖĖĖĖĖĖĖĖĖĖ");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("īīīīīīīīīī", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ÕÕÕÕÕÕÕÕÕÕ", "ƎƎƎƎƎƎƎƎƎƎ");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ÎÎÎÎÎÎÎÎÎÎ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "øøøøøøøøøø");
		collection.put("şşşşşşşşşş", "ħħħħħħħħħħ");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("úúúúúúúúúú", "ýýýýýýýýýý");
		collection.put("ŔŔŔŔŔŔŔŔŔŔ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ťťťťťťťťťť", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("ēēēēēēēēēē", "ŃŃŃŃŃŃŃŃŃŃ");
		collection.put("ÓÓÓÓÓÓÓÓÓÓ", "ĵĵĵĵĵĵĵĵĵĵ");
		collection.put("ČČČČČČČČČČ", "ØØØØØØØØØØ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ĨĨĨĨĨĨĨĨĨĨ", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ÓÓÓÓÓÓÓÓÓÓ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ÐÐÐÐÐÐÐÐÐÐ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ċċċċċċċċċċ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ŭŭŭŭŭŭŭŭŭŭ", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ųųųųųųųųųų");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ŤŤŤŤŤŤŤŤŤŤ");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ŭŭŭŭŭŭŭŭŭŭ", "ÓÓÓÓÓÓÓÓÓÓ");
		collection.put("ŪŪŪŪŪŪŪŪŪŪ", "śśśśśśśśśś");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ßßßßßßßßßß");
		collection.put("íííííííííí", "ŤŤŤŤŤŤŤŤŤŤ");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "ğğğğğğğğğğ");
		collection.put("řřřřřřřřřř", "õõõõõõõõõõ");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ľľľľľľľľľľ");
		collection.put("çççççççççç", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("őőőőőőőőőő", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ąąąąąąąąąą");
		collection.put("ēēēēēēēēēē", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ÎÎÎÎÎÎÎÎÎÎ", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("ßßßßßßßßßß", "ńńńńńńńńńń");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "öööööööööö");
		collection.put("ēēēēēēēēēē", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "şşşşşşşşşş");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "ōōōōōōōōōō");
		collection.put("řřřřřřřřřř", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ģģģģģģģģģģ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ÙÙÙÙÙÙÙÙÙÙ");
		collection.put("ĈĈĈĈĈĈĈĈĈĈ", "żżżżżżżżżż");
		collection.put("ĒĒĒĒĒĒĒĒĒĒ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("áááááááááá", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ĵĵĵĵĵĵĵĵĵĵ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ÏÏÏÏÏÏÏÏÏÏ", "ăăăăăăăăăă");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ŴŴŴŴŴŴŴŴŴŴ", "ËËËËËËËËËË");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ƈƈƈƈƈƈƈƈƈƈ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ēēēēēēēēēē", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("żżżżżżżżżż", "řřřřřřřřřř");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ŕŕŕŕŕŕŕŕŕŕ");
		collection.put("đđđđđđđđđđ", "ıııııııııı");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "ťťťťťťťťťť");
		collection.put("ýýýýýýýýýý", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ũũũũũũũũũũ", "ÌÌÌÌÌÌÌÌÌÌ");
		collection.put("ƋƋƋƋƋƋƋƋƋƋ", "åååååååååå");
		collection.put("ľľľľľľľľľľ", "ïïïïïïïïïï");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("İİİİİİİİİİ", "ŁŁŁŁŁŁŁŁŁŁ");
		collection.put("ßßßßßßßßßß", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ďďďďďďďďďď", "ġġġġġġġġġġ");
		collection.put("ćććććććććć", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "ļļļļļļļļļļ");
		collection.put("ţţţţţţţţţţ", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("ūūūūūūūūūū", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ĦĦĦĦĦĦĦĦĦĦ");
		collection.put("øøøøøøøøøø", "ĆĆĆĆĆĆĆĆĆĆ");
		collection.put("ëëëëëëëëëë", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("úúúúúúúúúú", "čččččččččč");
		collection.put("ĉĉĉĉĉĉĉĉĉĉ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ĮĮĮĮĮĮĮĮĮĮ", "ŃŃŃŃŃŃŃŃŃŃ");
		collection.put("úúúúúúúúúú", "íííííííííí");
		collection.put("öööööööööö", "ƅƅƅƅƅƅƅƅƅƅ");
		collection.put("ŵŵŵŵŵŵŵŵŵŵ", "ĿĿĿĿĿĿĿĿĿĿ");
		collection.put("ţţţţţţţţţţ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("ıııııııııı", "ēēēēēēēēēē");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ËËËËËËËËËË");
		collection.put("ķķķķķķķķķķ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "××××××××××");
		collection.put("ÎÎÎÎÎÎÎÎÎÎ", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ıııııııııı", "ðððððððððð");
		collection.put("çççççççççç", "××××××××××");
		collection.put("ńńńńńńńńńń", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ÐÐÐÐÐÐÐÐÐÐ", "ÙÙÙÙÙÙÙÙÙÙ");
		collection.put("ÖÖÖÖÖÖÖÖÖÖ", "ťťťťťťťťťť");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ÙÙÙÙÙÙÙÙÙÙ");
		collection.put("ĄĄĄĄĄĄĄĄĄĄ", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ôôôôôôôôôô", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ŘŘŘŘŘŘŘŘŘŘ", "ůůůůůůůůůů");
		collection.put("ŎŎŎŎŎŎŎŎŎŎ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("èèèèèèèèèè", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ķķķķķķķķķķ", "ĐĐĐĐĐĐĐĐĐĐ");
		collection.put("ââââââââââ", "åååååååååå");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ýýýýýýýýýý");
		collection.put("ĚĚĚĚĚĚĚĚĚĚ", "ēēēēēēēēēē");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "úúúúúúúúúú");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ňňňňňňňňňň");
		collection.put("ČČČČČČČČČČ", "ƎƎƎƎƎƎƎƎƎƎ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ųųųųųųųųųų");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ƋƋƋƋƋƋƋƋƋƋ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("åååååååååå", "ŗŗŗŗŗŗŗŗŗŗ");
		collection.put("ļļļļļļļļļļ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ÌÌÌÌÌÌÌÌÌÌ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ïïïïïïïïïï", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("įįįįįįįįįį", "ƋƋƋƋƋƋƋƋƋƋ");
		collection.put("ÞÞÞÞÞÞÞÞÞÞ", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ŏŏŏŏŏŏŏŏŏŏ");
		collection.put("îîîîîîîîîî", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ħħħħħħħħħħ");
		collection.put("řřřřřřřřřř", "ÖÖÖÖÖÖÖÖÖÖ");
		collection.put("řřřřřřřřřř", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ãããããããããã", "ńńńńńńńńńń");
		collection.put("ĠĠĠĠĠĠĠĠĠĠ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ĂĂĂĂĂĂĂĂĂĂ", "čččččččččč");
		collection.put("ſſſſſſſſſſ", "ƉƉƉƉƉƉƉƉƉƉ");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "ČČČČČČČČČČ");
		collection.put("ņņņņņņņņņņ", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("éééééééééé", "ŸŸŸŸŸŸŸŸŸŸ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ĸĸĸĸĸĸĸĸĸĸ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ōōōōōōōōōō", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ÜÜÜÜÜÜÜÜÜÜ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("èèèèèèèèèè", "ĮĮĮĮĮĮĮĮĮĮ");
		collection.put("đđđđđđđđđđ", "ÎÎÎÎÎÎÎÎÎÎ");
		collection.put("áááááááááá", "šššššššššš");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ĵĵĵĵĵĵĵĵĵĵ", "ħħħħħħħħħħ");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ææææææææææ", "ŋŋŋŋŋŋŋŋŋŋ");
		collection.put("öööööööööö", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "ěěěěěěěěěě");
		collection.put("ėėėėėėėėėė", "įįįįįįįįįį");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "öööööööööö");
		collection.put("öööööööööö", "ĩĩĩĩĩĩĩĩĩĩ");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ťťťťťťťťťť");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ƇƇƇƇƇƇƇƇƇƇ");
		collection.put("îîîîîîîîîî", "ŊŊŊŊŊŊŊŊŊŊ");
		collection.put("ĿĿĿĿĿĿĿĿĿĿ", "ƎƎƎƎƎƎƎƎƎƎ");
		collection.put("ňňňňňňňňňň", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("çççççççççç", "çççççççççç");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ġġġġġġġġġġ");
		collection.put("ūūūūūūūūūū", "õõõõõõõõõõ");
		collection.put("ƀƀƀƀƀƀƀƀƀƀ", "čččččččččč");
		collection.put("ĪĪĪĪĪĪĪĪĪĪ", "řřřřřřřřřř");
		collection.put("ŠŠŠŠŠŠŠŠŠŠ", "îîîîîîîîîî");
		collection.put("ŁŁŁŁŁŁŁŁŁŁ", "ìììììììììì");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ËËËËËËËËËË");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ĦĦĦĦĦĦĦĦĦĦ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "ŨŨŨŨŨŨŨŨŨŨ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ĿĿĿĿĿĿĿĿĿĿ", "ŰŰŰŰŰŰŰŰŰŰ");
		collection.put("ĐĐĐĐĐĐĐĐĐĐ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "áááááááááá");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ŞŞŞŞŞŞŞŞŞŞ");
		collection.put("ňňňňňňňňňň", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ƆƆƆƆƆƆƆƆƆƆ", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ïïïïïïïïïï", "ņņņņņņņņņņ");
		collection.put("ęęęęęęęęęę", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ĜĜĜĜĜĜĜĜĜĜ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ËËËËËËËËËË");
		collection.put("ŠŠŠŠŠŠŠŠŠŠ", "××××××××××");
		collection.put("ãããããããããã", "ŦŦŦŦŦŦŦŦŦŦ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ĖĖĖĖĖĖĖĖĖĖ");
		collection.put("ũũũũũũũũũũ", "įįįįįįįįįį");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ţţţţţţţţţţ");
		collection.put("ĦĦĦĦĦĦĦĦĦĦ", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ƂƂƂƂƂƂƂƂƂƂ", "ƏƏƏƏƏƏƏƏƏƏ");
		collection.put("ĿĿĿĿĿĿĿĿĿĿ", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ŬŬŬŬŬŬŬŬŬŬ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("åååååååååå", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("ĸĸĸĸĸĸĸĸĸĸ", "İİİİİİİİİİ");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("óóóóóóóóóó", "őőőőőőőőőő");
		collection.put("åååååååååå", "ëëëëëëëëëë");
		collection.put("đđđđđđđđđđ", "ƆƆƆƆƆƆƆƆƆƆ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ēēēēēēēēēē");
		collection.put("ïïïïïïïïïï", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "ÓÓÓÓÓÓÓÓÓÓ");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "şşşşşşşşşş");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĹĹĹĹĹĹĹĹĹĹ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "ŮŮŮŮŮŮŮŮŮŮ");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "ħħħħħħħħħħ");
		collection.put("ęęęęęęęęęę", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ŝŝŝŝŝŝŝŝŝŝ", "ûûûûûûûûûû");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ÛÛÛÛÛÛÛÛÛÛ");
		collection.put("ğğğğğğğğğğ", "ĔĔĔĔĔĔĔĔĔĔ");
		collection.put("ŸŸŸŸŸŸŸŸŸŸ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("ŶŶŶŶŶŶŶŶŶŶ", "ĽĽĽĽĽĽĽĽĽĽ");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ìììììììììì");
		collection.put("ŇŇŇŇŇŇŇŇŇŇ", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "ŢŢŢŢŢŢŢŢŢŢ");
		collection.put("ƏƏƏƏƏƏƏƏƏƏ", "ŹŹŹŹŹŹŹŹŹŹ");
		collection.put("ĪĪĪĪĪĪĪĪĪĪ", "ÜÜÜÜÜÜÜÜÜÜ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "ĭĭĭĭĭĭĭĭĭĭ");
		collection.put("őőőőőőőőőő", "úúúúúúúúúú");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ĶĶĶĶĶĶĶĶĶĶ");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "ÞÞÞÞÞÞÞÞÞÞ");
		collection.put("ČČČČČČČČČČ", "ČČČČČČČČČČ");
		collection.put("ŤŤŤŤŤŤŤŤŤŤ", "ťťťťťťťťťť");
		collection.put("ĺĺĺĺĺĺĺĺĺĺ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("óóóóóóóóóó", "ÊÊÊÊÊÊÊÊÊÊ");
		collection.put("øøøøøøøøøø", "ŴŴŴŴŴŴŴŴŴŴ");
		collection.put("ņņņņņņņņņņ", "ĺĺĺĺĺĺĺĺĺĺ");
		collection.put("ŉŉŉŉŉŉŉŉŉŉ", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "łłłłłłłłłł");
		collection.put("ĕĕĕĕĕĕĕĕĕĕ", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ÔÔÔÔÔÔÔÔÔÔ", "ÐÐÐÐÐÐÐÐÐÐ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "ËËËËËËËËËË");
		collection.put("ƊƊƊƊƊƊƊƊƊƊ", "ŌŌŌŌŌŌŌŌŌŌ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ėėėėėėėėėė", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ăăăăăăăăăă");
		collection.put("ūūūūūūūūūū", "ķķķķķķķķķķ");
		collection.put("õõõõõõõõõõ", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "śśśśśśśśśś");
		collection.put("ĩĩĩĩĩĩĩĩĩĩ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ĈĈĈĈĈĈĈĈĈĈ", "ëëëëëëëëëë");
		collection.put("őőőőőőőőőő", "ôôôôôôôôôô");
		collection.put("ŗŗŗŗŗŗŗŗŗŗ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ĮĮĮĮĮĮĮĮĮĮ", "ƊƊƊƊƊƊƊƊƊƊ");
		collection.put("ŮŮŮŮŮŮŮŮŮŮ", "þþþþþþþþþþ");
		collection.put("ŠŠŠŠŠŠŠŠŠŠ", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("ŒŒŒŒŒŒŒŒŒŒ", "ęęęęęęęęęę");
		collection.put("ĈĈĈĈĈĈĈĈĈĈ", "ŖŖŖŖŖŖŖŖŖŖ");
		collection.put("ŐŐŐŐŐŐŐŐŐŐ", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("åååååååååå", "ïïïïïïïïïï");
		collection.put("ƆƆƆƆƆƆƆƆƆƆ", "ĊĊĊĊĊĊĊĊĊĊ");
		collection.put("ũũũũũũũũũũ", "ŷŷŷŷŷŷŷŷŷŷ");
		collection.put("îîîîîîîîîî", "ûûûûûûûûûû");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ċċċċċċċċċċ", "ĽĽĽĽĽĽĽĽĽĽ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ìììììììììì", "ĉĉĉĉĉĉĉĉĉĉ");
		collection.put("şşşşşşşşşş", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ŰŰŰŰŰŰŰŰŰŰ", "ûûûûûûûûûû");
		collection.put("ŧŧŧŧŧŧŧŧŧŧ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ČČČČČČČČČČ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ØØØØØØØØØØ");
		collection.put("áááááááááá", "ƄƄƄƄƄƄƄƄƄƄ");
		collection.put("åååååååååå", "ääääääääää");
		collection.put("ģģģģģģģģģģ", "ýýýýýýýýýý");
		collection.put("íííííííííí", "œœœœœœœœœœ");
		collection.put("ŢŢŢŢŢŢŢŢŢŢ", "ťťťťťťťťťť");
		collection.put("ÛÛÛÛÛÛÛÛÛÛ", "ĻĻĻĻĻĻĻĻĻĻ");
		collection.put("ĨĨĨĨĨĨĨĨĨĨ", "ŻŻŻŻŻŻŻŻŻŻ");
		collection.put("ĢĢĢĢĢĢĢĢĢĢ", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ŨŨŨŨŨŨŨŨŨŨ", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("ċċċċċċċċċċ", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ĪĪĪĪĪĪĪĪĪĪ");
		collection.put("ňňňňňňňňňň", "êêêêêêêêêê");
		collection.put("××××××××××", "ÏÏÏÏÏÏÏÏÏÏ");
		collection.put("ŊŊŊŊŊŊŊŊŊŊ", "źźźźźźźźźź");
		collection.put("ąąąąąąąąąą", "ËËËËËËËËËË");
		collection.put("ņņņņņņņņņņ", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("ķķķķķķķķķķ", "ŦŦŦŦŦŦŦŦŦŦ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ÝÝÝÝÝÝÝÝÝÝ");
		collection.put("ſſſſſſſſſſ", "ââââââââââ");
		collection.put("ƈƈƈƈƈƈƈƈƈƈ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("óóóóóóóóóó", "ÚÚÚÚÚÚÚÚÚÚ");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ľľľľľľľľľľ");
		collection.put("ŃŃŃŃŃŃŃŃŃŃ", "øøøøøøøøøø");
		collection.put("žžžžžžžžžž", "āāāāāāāāāā");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "îîîîîîîîîî");
		collection.put("ŕŕŕŕŕŕŕŕŕŕ", "ůůůůůůůůůů");
		collection.put("ƃƃƃƃƃƃƃƃƃƃ", "éééééééééé");
		collection.put("ęęęęęęęęęę", "ÍÍÍÍÍÍÍÍÍÍ");
		collection.put("ññññññññññ", "ėėėėėėėėėė");
		collection.put("ƉƉƉƉƉƉƉƉƉƉ", "ßßßßßßßßßß");
		collection.put("ãããããããããã", "óóóóóóóóóó");
		collection.put("ĤĤĤĤĤĤĤĤĤĤ", "ùùùùùùùùùù");
		collection.put("àààààààààà", "ĨĨĨĨĨĨĨĨĨĨ");
		collection.put("ôôôôôôôôôô", "ŲŲŲŲŲŲŲŲŲŲ");
		collection.put("ĲĲĲĲĲĲĲĲĲĲ", "ùùùùùùùùùù");
		collection.put("ŴŴŴŴŴŴŴŴŴŴ", "ßßßßßßßßßß");
		collection.put("ÿÿÿÿÿÿÿÿÿÿ", "żżżżżżżżżż");
		collection.put("ŅŅŅŅŅŅŅŅŅŅ", "óóóóóóóóóó");
		collection.put("śśśśśśśśśś", "ŵŵŵŵŵŵŵŵŵŵ");
		collection.put("íííííííííí", "ĽĽĽĽĽĽĽĽĽĽ");
		collection.put("ÚÚÚÚÚÚÚÚÚÚ", "ĕĕĕĕĕĕĕĕĕĕ");
		collection.put("ĔĔĔĔĔĔĔĔĔĔ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ÍÍÍÍÍÍÍÍÍÍ", "óóóóóóóóóó");
		collection.put("ģģģģģģģģģģ", "ÔÔÔÔÔÔÔÔÔÔ");
		collection.put("ðððððððððð", "ţţţţţţţţţţ");
		collection.put("ęęęęęęęęęę", "ėėėėėėėėėė");
		collection.put("ďďďďďďďďďď", "ØØØØØØØØØØ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ŭŭŭŭŭŭŭŭŭŭ");
		collection.put("ƇƇƇƇƇƇƇƇƇƇ", "ÊÊÊÊÊÊÊÊÊÊ");
		collection.put("ŰŰŰŰŰŰŰŰŰŰ", "űűűűűűűűűű");
		collection.put("ĥĥĥĥĥĥĥĥĥĥ", "ħħħħħħħħħħ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "űűűűűűűűűű");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ŬŬŬŬŬŬŬŬŬŬ");
		collection.put("××××××××××", "ØØØØØØØØØØ");
		collection.put("ƅƅƅƅƅƅƅƅƅƅ", "ÑÑÑÑÑÑÑÑÑÑ");
		collection.put("ŧŧŧŧŧŧŧŧŧŧ", "ŧŧŧŧŧŧŧŧŧŧ");
		collection.put("ģģģģģģģģģģ", "ææææææææææ");
		collection.put("üüüüüüüüüü", "źźźźźźźźźź");
		collection.put("ĜĜĜĜĜĜĜĜĜĜ", "čččččččččč");
		collection.put("ĽĽĽĽĽĽĽĽĽĽ", "øøøøøøøøøø");
		collection.put("łłłłłłłłłł", "ĄĄĄĄĄĄĄĄĄĄ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "čččččččččč");
		collection.put("łłłłłłłłłł", "ïïïïïïïïïï");
		collection.put("ìììììììììì", "ůůůůůůůůůů");
		collection.put("ƎƎƎƎƎƎƎƎƎƎ", "ĬĬĬĬĬĬĬĬĬĬ");
		collection.put("ßßßßßßßßßß", "ĞĞĞĞĞĞĞĞĞĞ");
		collection.put("ðððððððððð", "ŝŝŝŝŝŝŝŝŝŝ");
		collection.put("ƄƄƄƄƄƄƄƄƄƄ", "ÈÈÈÈÈÈÈÈÈÈ");
		collection.put("ķķķķķķķķķķ", "ůůůůůůůůůů");
		collection.put("ŲŲŲŲŲŲŲŲŲŲ", "ÒÒÒÒÒÒÒÒÒÒ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "İİİİİİİİİİ");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ìììììììììì");
		collection.put("ƌƌƌƌƌƌƌƌƌƌ", "ŅŅŅŅŅŅŅŅŅŅ");
		collection.put("ÒÒÒÒÒÒÒÒÒÒ", "āāāāāāāāāā");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("áááááááááá", "êêêêêêêêêê");
		collection.put("ŀŀŀŀŀŀŀŀŀŀ", "îîîîîîîîîî");
		collection.put("ĻĻĻĻĻĻĻĻĻĻ", "ÕÕÕÕÕÕÕÕÕÕ");
		collection.put("ıııııııııı", "ģģģģģģģģģģ");
		collection.put("ýýýýýýýýýý", "ÿÿÿÿÿÿÿÿÿÿ");
		collection.put("ƂƂƂƂƂƂƂƂƂƂ", "ĝĝĝĝĝĝĝĝĝĝ");
		collection.put("ŹŹŹŹŹŹŹŹŹŹ", "ŚŚŚŚŚŚŚŚŚŚ");
		collection.put("ņņņņņņņņņņ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ìììììììììì", "ŶŶŶŶŶŶŶŶŶŶ");
		collection.put("ææææææææææ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ĬĬĬĬĬĬĬĬĬĬ", "òòòòòòòòòò");
		collection.put("źźźźźźźźźź", "ƂƂƂƂƂƂƂƂƂƂ");
		collection.put("çççççççççç", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ěěěěěěěěěě", "ŠŠŠŠŠŠŠŠŠŠ");
		collection.put("ňňňňňňňňňň", "űűűűűűűűűű");
		collection.put("šššššššššš", "ũũũũũũũũũũ");
		collection.put("ĆĆĆĆĆĆĆĆĆĆ", "ňňňňňňňňňň");
		collection.put("œœœœœœœœœœ", "ŜŜŜŜŜŜŜŜŜŜ");
		collection.put("ŌŌŌŌŌŌŌŌŌŌ", "ŐŐŐŐŐŐŐŐŐŐ");
		collection.put("łłłłłłłłłł", "ĤĤĤĤĤĤĤĤĤĤ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "èèèèèèèèèè");
		collection.put("ĳĳĳĳĳĳĳĳĳĳ", "ĎĎĎĎĎĎĎĎĎĎ");
		collection.put("ĊĊĊĊĊĊĊĊĊĊ", "ÛÛÛÛÛÛÛÛÛÛ");
		collection.put("ŦŦŦŦŦŦŦŦŦŦ", "ņņņņņņņņņņ");
		collection.put("ĖĖĖĖĖĖĖĖĖĖ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ĝĝĝĝĝĝĝĝĝĝ", "ŏŏŏŏŏŏŏŏŏŏ");
		collection.put("ęęęęęęęęęę", "ťťťťťťťťťť");
		collection.put("ĹĹĹĹĹĹĹĹĹĹ", "ĲĲĲĲĲĲĲĲĲĲ");
		collection.put("ĘĘĘĘĘĘĘĘĘĘ", "ĈĈĈĈĈĈĈĈĈĈ");
		collection.put("ŰŰŰŰŰŰŰŰŰŰ", "ţţţţţţţţţţ");
		collection.put("ĀĀĀĀĀĀĀĀĀĀ", "ÑÑÑÑÑÑÑÑÑÑ");
		collection.put("ůůůůůůůůůů", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("ƁƁƁƁƁƁƁƁƁƁ", "ŎŎŎŎŎŎŎŎŎŎ");
		collection.put("õõõõõõõõõõ", "ůůůůůůůůůů");
		collection.put("ńńńńńńńńńń", "ĥĥĥĥĥĥĥĥĥĥ");
		collection.put("ŻŻŻŻŻŻŻŻŻŻ", "ŔŔŔŔŔŔŔŔŔŔ");
		collection.put("ĴĴĴĴĴĴĴĴĴĴ", "ĂĂĂĂĂĂĂĂĂĂ");
		collection.put("įįįįįįįįįį", "ľľľľľľľľľľ");
		collection.put("ĎĎĎĎĎĎĎĎĎĎ", "ľľľľľľľľľľ");
		collection.put("ÒÒÒÒÒÒÒÒÒÒ", "ĳĳĳĳĳĳĳĳĳĳ");
		collection.put("ùùùùùùùùùù", "ƀƀƀƀƀƀƀƀƀƀ");
		collection.put("ńńńńńńńńńń", "ŽŽŽŽŽŽŽŽŽŽ");
		collection.put("ŷŷŷŷŷŷŷŷŷŷ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("øøøøøøøøøø", "ĘĘĘĘĘĘĘĘĘĘ");
		collection.put("ćććććććććć", "łłłłłłłłłł");
		collection.put("ÒÒÒÒÒÒÒÒÒÒ", "ĢĢĢĢĢĢĢĢĢĢ");
		collection.put("ƍƍƍƍƍƍƍƍƍƍ", "źźźźźźźźźź");
		collection.put("åååååååååå", "úúúúúúúúúú");
		collection.put("ŚŚŚŚŚŚŚŚŚŚ", "ŪŪŪŪŪŪŪŪŪŪ");
		collection.put("ÝÝÝÝÝÝÝÝÝÝ", "ģģģģģģģģģģ");
	}
	@Benchmark
	@Fork(1)
	@Warmup(time=3)
	@Measurement(time=3,iterations=10)
	public void JHashMap(Blackhole bh) {
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĪĪĪĪĪĪĪĪĪĪ"));
		bh.consume(collection.containsKey("ĵĵĵĵĵĵĵĵĵĵ"));
		bh.consume(collection.remove("ňňňňňňňňňň"));
		bh.consume(collection.get("šššššššššš"));
		bh.consume(collection.get("øøøøøøøøøø"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ůůůůůůůůůů", "ĘĘĘĘĘĘĘĘĘĘ"));
		bh.consume(collection.replace("ďďďďďďďďďď", "ĝĝĝĝĝĝĝĝĝĝ"));
		bh.consume(collection.remove("ƋƋƋƋƋƋƋƋƋƋ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ƃƃƃƃƃƃƃƃƃƃ", "ŒŒŒŒŒŒŒŒŒŒ"));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ŧŧŧŧŧŧŧŧŧŧ", "ŬŬŬŬŬŬŬŬŬŬ"));
		bh.consume(collection.get("ēēēēēēēēēē"));
		bh.consume(collection.replace("ÎÎÎÎÎÎÎÎÎÎ", "ĞĞĞĞĞĞĞĞĞĞ"));
		bh.consume(collection.get("þþþþþþþþþþ"));
		bh.consume(collection.replace("ŹŹŹŹŹŹŹŹŹŹ", "ĊĊĊĊĊĊĊĊĊĊ"));
		bh.consume(collection.replace("ćććććććććć", "ťťťťťťťťťť"));
		bh.consume(collection.replace("ČČČČČČČČČČ", "ïïïïïïïïïï"));
		bh.consume(collection.get("úúúúúúúúúú"));
		bh.consume(collection.values());
		bh.consume(collection.remove("ĘĘĘĘĘĘĘĘĘĘ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("íííííííííí"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĆĆĆĆĆĆĆĆĆĆ"));
		bh.consume(collection.containsKey("ĚĚĚĚĚĚĚĚĚĚ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get("ƆƆƆƆƆƆƆƆƆƆ"));
		bh.consume(collection.get("ůůůůůůůůůů"));
		bh.consume(collection.replace("óóóóóóóóóó", "üüüüüüüüüü"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ăăăăăăăăăă"));
		bh.consume(collection.replace("êêêêêêêêêê", "ĽĽĽĽĽĽĽĽĽĽ"));
		bh.consume(collection.containsKey("ġġġġġġġġġġ"));
		bh.consume(collection.get("ŀŀŀŀŀŀŀŀŀŀ"));
		bh.consume(collection.containsKey("ƇƇƇƇƇƇƇƇƇƇ"));
		bh.consume(collection.remove("ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.remove("þþþþþþþþþþ"));
		bh.consume(collection.get("ĠĠĠĠĠĠĠĠĠĠ"));
		bh.consume(collection.remove("íííííííííí"));
		bh.consume(collection.containsKey("ŁŁŁŁŁŁŁŁŁŁ"));
		bh.consume(collection.containsKey("ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("ŭŭŭŭŭŭŭŭŭŭ"));
		bh.consume(collection.replace("ĽĽĽĽĽĽĽĽĽĽ", "ĭĭĭĭĭĭĭĭĭĭ"));
		bh.consume(collection.get("ƏƏƏƏƏƏƏƏƏƏ"));
		bh.consume(collection.containsKey("ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.containsKey("üüüüüüüüüü"));
		bh.consume(collection.remove("îîîîîîîîîî"));
		bh.consume(collection.replace("ææææææææææ", "ôôôôôôôôôô"));
		bh.consume(collection.containsKey("íííííííííí"));
		bh.consume(collection.remove("ÈÈÈÈÈÈÈÈÈÈ"));
		bh.consume(collection.replace("ũũũũũũũũũũ", "ĉĉĉĉĉĉĉĉĉĉ"));
		bh.consume(collection.containsKey("ĆĆĆĆĆĆĆĆĆĆ"));
		bh.consume(collection.get("ŊŊŊŊŊŊŊŊŊŊ"));
		bh.consume(collection.replace("ŖŖŖŖŖŖŖŖŖŖ", "ŶŶŶŶŶŶŶŶŶŶ"));
		bh.consume(collection.containsKey("űűűűűűűűűű"));
		bh.consume(collection.replace("ƆƆƆƆƆƆƆƆƆƆ", "ƋƋƋƋƋƋƋƋƋƋ"));
		bh.consume(collection.containsKey("ĕĕĕĕĕĕĕĕĕĕ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĜĜĜĜĜĜĜĜĜĜ"));
		bh.consume(collection.replace("ÌÌÌÌÌÌÌÌÌÌ", "ôôôôôôôôôô"));
		bh.consume(collection.replace("ĕĕĕĕĕĕĕĕĕĕ", "ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.containsKey("ĐĐĐĐĐĐĐĐĐĐ"));
		bh.consume(collection.containsKey("ââââââââââ"));
		bh.consume(collection.replace("ũũũũũũũũũũ", "ƌƌƌƌƌƌƌƌƌƌ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace("ŖŖŖŖŖŖŖŖŖŖ", "××××××××××"));
		bh.consume(collection.containsKey("ŰŰŰŰŰŰŰŰŰŰ"));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("êêêêêêêêêê", "ÜÜÜÜÜÜÜÜÜÜ"));
		bh.consume(collection.remove("ġġġġġġġġġġ"));
		bh.consume(collection.containsKey("ƂƂƂƂƂƂƂƂƂƂ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("ÑÑÑÑÑÑÑÑÑÑ", "ċċċċċċċċċċ"));
		bh.consume(collection.replace("ŭŭŭŭŭŭŭŭŭŭ", "āāāāāāāāāā"));
		bh.consume(collection.containsKey("ŋŋŋŋŋŋŋŋŋŋ"));
		bh.consume(collection.containsKey("ûûûûûûûûûû"));
		bh.consume(collection.remove("ųųųųųųųųųų"));
		bh.consume(collection.replace("ƏƏƏƏƏƏƏƏƏƏ", "ŵŵŵŵŵŵŵŵŵŵ"));
		bh.consume(collection.remove("ƂƂƂƂƂƂƂƂƂƂ"));
		bh.consume(collection.remove("ýýýýýýýýýý"));
		bh.consume(collection.get("ĢĢĢĢĢĢĢĢĢĢ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ĩĩĩĩĩĩĩĩĩĩ", "ĵĵĵĵĵĵĵĵĵĵ"));
		bh.consume(collection.containsKey("ÙÙÙÙÙÙÙÙÙÙ"));
		bh.consume(collection.containsKey("ĨĨĨĨĨĨĨĨĨĨ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("òòòòòòòòòò", "ĦĦĦĦĦĦĦĦĦĦ"));
		bh.consume(collection.replace("żżżżżżżżżż", "ĊĊĊĊĊĊĊĊĊĊ"));
		bh.consume(collection.remove("īīīīīīīīīī"));
		bh.consume(collection.containsKey("ŹŹŹŹŹŹŹŹŹŹ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("ÌÌÌÌÌÌÌÌÌÌ", "ÉÉÉÉÉÉÉÉÉÉ"));
		bh.consume(collection.replace("ţţţţţţţţţţ", "óóóóóóóóóó"));
		bh.consume(collection.get("ÒÒÒÒÒÒÒÒÒÒ"));
		bh.consume(collection.get("ķķķķķķķķķķ"));
		bh.consume(collection.get("ŷŷŷŷŷŷŷŷŷŷ"));
		bh.consume(collection.replace("ĖĖĖĖĖĖĖĖĖĖ", "ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.remove("çççççççççç"));
		bh.consume(collection.get("įįįįįįįįįį"));
		bh.consume(collection.replace("ƂƂƂƂƂƂƂƂƂƂ", "ĀĀĀĀĀĀĀĀĀĀ"));
		bh.consume(collection.replace("ŽŽŽŽŽŽŽŽŽŽ", "ŪŪŪŪŪŪŪŪŪŪ"));
		bh.consume(collection.get("İİİİİİİİİİ"));
		bh.consume(collection.containsKey("éééééééééé"));
		bh.consume(collection.replace("ŖŖŖŖŖŖŖŖŖŖ", "ŀŀŀŀŀŀŀŀŀŀ"));
		bh.consume(collection.containsKey("ŭŭŭŭŭŭŭŭŭŭ"));
		bh.consume(collection.containsKey("ŘŘŘŘŘŘŘŘŘŘ"));
		bh.consume(collection.containsKey("ŧŧŧŧŧŧŧŧŧŧ"));
		bh.consume(collection.get("øøøøøøøøøø"));
		bh.consume(collection.remove("ÔÔÔÔÔÔÔÔÔÔ"));
		bh.consume(collection.replace("ÏÏÏÏÏÏÏÏÏÏ", "òòòòòòòòòò"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ŐŐŐŐŐŐŐŐŐŐ", "ŞŞŞŞŞŞŞŞŞŞ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("èèèèèèèèèè", "ŜŜŜŜŜŜŜŜŜŜ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("čččččččččč", "ƅƅƅƅƅƅƅƅƅƅ"));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.get("ōōōōōōōōōō"));
		bh.consume(collection.replace("ĥĥĥĥĥĥĥĥĥĥ", "ÙÙÙÙÙÙÙÙÙÙ"));
		bh.consume(collection.replace("įįįįįįįįįį", "ƁƁƁƁƁƁƁƁƁƁ"));
		bh.consume(collection.get("şşşşşşşşşş"));
		bh.consume(collection.get("ŲŲŲŲŲŲŲŲŲŲ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ƁƁƁƁƁƁƁƁƁƁ"));
		bh.consume(collection.containsKey("ÏÏÏÏÏÏÏÏÏÏ"));
		bh.consume(collection.replace("ßßßßßßßßßß", "ďďďďďďďďďď"));
		bh.consume(collection.remove("ĨĨĨĨĨĨĨĨĨĨ"));
		bh.consume(collection.remove("ÍÍÍÍÍÍÍÍÍÍ"));
		bh.consume(collection.remove("ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.keySet());
		bh.consume(collection.remove("óóóóóóóóóó"));
		bh.consume(collection.replace("ĹĹĹĹĹĹĹĹĹĹ", "çççççççççç"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ąąąąąąąąąą", "ƏƏƏƏƏƏƏƏƏƏ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĈĈĈĈĈĈĈĈĈĈ"));
		bh.consume(collection.replace("ÞÞÞÞÞÞÞÞÞÞ", "ƍƍƍƍƍƍƍƍƍƍ"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("ÚÚÚÚÚÚÚÚÚÚ"));
		bh.consume(collection.replace("ſſſſſſſſſſ", "ČČČČČČČČČČ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ŽŽŽŽŽŽŽŽŽŽ"));
		bh.consume(collection.remove("ģģģģģģģģģģ"));
		bh.consume(collection.get("êêêêêêêêêê"));
		bh.consume(collection.containsKey("ññññññññññ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.get("ĈĈĈĈĈĈĈĈĈĈ"));
		bh.consume(collection.replace("ŴŴŴŴŴŴŴŴŴŴ", "ĺĺĺĺĺĺĺĺĺĺ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace("ÏÏÏÏÏÏÏÏÏÏ", "ĢĢĢĢĢĢĢĢĢĢ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey("łłłłłłłłłł"));
		bh.consume(collection.containsKey("ìììììììììì"));
		bh.consume(collection.containsKey("żżżżżżżżżż"));
		bh.consume(collection.replace("ėėėėėėėėėė", "êêêêêêêêêê"));
		bh.consume(collection.containsKey("ââââââââââ"));
		bh.consume(collection.replace("ſſſſſſſſſſ", "ěěěěěěěěěě"));
		bh.consume(collection.containsKey("żżżżżżżżżż"));
		bh.consume(collection.values());
		bh.consume(collection.get("ŬŬŬŬŬŬŬŬŬŬ"));
		bh.consume(collection.remove("ƇƇƇƇƇƇƇƇƇƇ"));
		bh.consume(collection.replace("ØØØØØØØØØØ", "ĠĠĠĠĠĠĠĠĠĠ"));
		bh.consume(collection.get("ťťťťťťťťťť"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("çççççççççç"));
		bh.consume(collection.replace("ŕŕŕŕŕŕŕŕŕŕ", "ŇŇŇŇŇŇŇŇŇŇ"));
		bh.consume(collection.containsKey("ĽĽĽĽĽĽĽĽĽĽ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ūūūūūūūūūū", "īīīīīīīīīī"));
		bh.consume(collection.get("ńńńńńńńńńń"));
		bh.consume(collection.replace("ĒĒĒĒĒĒĒĒĒĒ", "ĞĞĞĞĞĞĞĞĞĞ"));
		bh.consume(collection.remove("ōōōōōōōōōō"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ÓÓÓÓÓÓÓÓÓÓ"));
		bh.consume(collection.containsKey("řřřřřřřřřř"));
		bh.consume(collection.remove("ŔŔŔŔŔŔŔŔŔŔ"));
		bh.consume(collection.replace("ťťťťťťťťťť", "ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.replace("ĮĮĮĮĮĮĮĮĮĮ", "ƎƎƎƎƎƎƎƎƎƎ"));
		bh.consume(collection.containsKey("ŬŬŬŬŬŬŬŬŬŬ"));
		bh.consume(collection.get("ŚŚŚŚŚŚŚŚŚŚ"));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ĴĴĴĴĴĴĴĴĴĴ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("××××××××××", "óóóóóóóóóó"));
		bh.consume(collection.get("ŊŊŊŊŊŊŊŊŊŊ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ËËËËËËËËËË", "ıııııııııı"));
		bh.consume(collection.get("ƎƎƎƎƎƎƎƎƎƎ"));
		bh.consume(collection.get("ƋƋƋƋƋƋƋƋƋƋ"));
		bh.consume(collection.get("ţţţţţţţţţţ"));
		bh.consume(collection.containsKey("ƎƎƎƎƎƎƎƎƎƎ"));
		bh.consume(collection.containsKey("ĲĲĲĲĲĲĲĲĲĲ"));
		bh.consume(collection.get("ĎĎĎĎĎĎĎĎĎĎ"));
		bh.consume(collection.remove("ïïïïïïïïïï"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ƊƊƊƊƊƊƊƊƊƊ", "ÑÑÑÑÑÑÑÑÑÑ"));
		bh.consume(collection.replace("ēēēēēēēēēē", "õõõõõõõõõõ"));
		bh.consume(collection.containsKey("ƆƆƆƆƆƆƆƆƆƆ"));
		bh.consume(collection.remove("řřřřřřřřřř"));
		bh.consume(collection.replace("ññññññññññ", "ŃŃŃŃŃŃŃŃŃŃ"));
		bh.consume(collection.get("ŰŰŰŰŰŰŰŰŰŰ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ėėėėėėėėėė", "ƌƌƌƌƌƌƌƌƌƌ"));
		bh.consume(collection.containsKey("ƇƇƇƇƇƇƇƇƇƇ"));
		bh.consume(collection.containsKey("ÔÔÔÔÔÔÔÔÔÔ"));
		bh.consume(collection.remove("ÿÿÿÿÿÿÿÿÿÿ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("þþþþþþþþþþ", "ƋƋƋƋƋƋƋƋƋƋ"));
		bh.consume(collection.containsKey("ĐĐĐĐĐĐĐĐĐĐ"));
		bh.consume(collection.remove("ēēēēēēēēēē"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("ŖŖŖŖŖŖŖŖŖŖ"));
		bh.consume(collection.replace("ÖÖÖÖÖÖÖÖÖÖ", "ſſſſſſſſſſ"));
		bh.consume(collection.replace("ſſſſſſſſſſ", "ęęęęęęęęęę"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ØØØØØØØØØØ", "ļļļļļļļļļļ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ŕŕŕŕŕŕŕŕŕŕ"));
		bh.consume(collection.get("çççççççççç"));
		bh.consume(collection.replace("ŃŃŃŃŃŃŃŃŃŃ", "ċċċċċċċċċċ"));
		bh.consume(collection.get("ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.replace("ŶŶŶŶŶŶŶŶŶŶ", "ĩĩĩĩĩĩĩĩĩĩ"));
		bh.consume(collection.replace("ŢŢŢŢŢŢŢŢŢŢ", "ĚĚĚĚĚĚĚĚĚĚ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ƈƈƈƈƈƈƈƈƈƈ", "çççççççççç"));
		bh.consume(collection.get("ôôôôôôôôôô"));
		bh.consume(collection.replace("ÝÝÝÝÝÝÝÝÝÝ", "ĝĝĝĝĝĝĝĝĝĝ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ûûûûûûûûûû", "ƏƏƏƏƏƏƏƏƏƏ"));
		bh.consume(collection.replace("źźźźźźźźźź", "ťťťťťťťťťť"));
		bh.consume(collection.containsKey("ğğğğğğğğğğ"));
		bh.consume(collection.containsKey("ĂĂĂĂĂĂĂĂĂĂ"));
		bh.consume(collection.values());
		bh.consume(collection.remove("ńńńńńńńńńń"));
		bh.consume(collection.containsKey("ŚŚŚŚŚŚŚŚŚŚ"));
		bh.consume(collection.replace("ÎÎÎÎÎÎÎÎÎÎ", "óóóóóóóóóó"));
		bh.consume(collection.containsKey("ÉÉÉÉÉÉÉÉÉÉ"));
		bh.consume(collection.replace("ÛÛÛÛÛÛÛÛÛÛ", "ŋŋŋŋŋŋŋŋŋŋ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.remove("ŒŒŒŒŒŒŒŒŒŒ"));
		bh.consume(collection.get("šššššššššš"));
		bh.consume(collection.replace("ŏŏŏŏŏŏŏŏŏŏ", "ŷŷŷŷŷŷŷŷŷŷ"));
		bh.consume(collection.containsKey("ĪĪĪĪĪĪĪĪĪĪ"));
		bh.consume(collection.containsKey("ÚÚÚÚÚÚÚÚÚÚ"));
		bh.consume(collection.get("ŻŻŻŻŻŻŻŻŻŻ"));
		bh.consume(collection.containsKey("ųųųųųųųųųų"));
		bh.consume(collection.get("ĆĆĆĆĆĆĆĆĆĆ"));
		bh.consume(collection.replace("ĝĝĝĝĝĝĝĝĝĝ", "ĄĄĄĄĄĄĄĄĄĄ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.remove("ĭĭĭĭĭĭĭĭĭĭ"));
		bh.consume(collection.get("ŭŭŭŭŭŭŭŭŭŭ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĈĈĈĈĈĈĈĈĈĈ"));
		bh.consume(collection.remove("İİİİİİİİİİ"));
		bh.consume(collection.containsKey("ÚÚÚÚÚÚÚÚÚÚ"));
		bh.consume(collection.containsKey("ņņņņņņņņņņ"));
		bh.consume(collection.replace("ŭŭŭŭŭŭŭŭŭŭ", "ĂĂĂĂĂĂĂĂĂĂ"));
		bh.consume(collection.containsKey("ĵĵĵĵĵĵĵĵĵĵ"));
		bh.consume(collection.containsKey("ŌŌŌŌŌŌŌŌŌŌ"));
		bh.consume(collection.containsKey("ææææææææææ"));
		bh.consume(collection.values());
		bh.consume(collection.get("ħħħħħħħħħħ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ŵŵŵŵŵŵŵŵŵŵ"));
		bh.consume(collection.replace("ĬĬĬĬĬĬĬĬĬĬ", "ńńńńńńńńńń"));
		bh.consume(collection.containsKey("ũũũũũũũũũũ"));
		bh.consume(collection.containsKey("ĎĎĎĎĎĎĎĎĎĎ"));
		bh.consume(collection.values());
		bh.consume(collection.get("ŊŊŊŊŊŊŊŊŊŊ"));
		bh.consume(collection.replace("ĔĔĔĔĔĔĔĔĔĔ", "ťťťťťťťťťť"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ŮŮŮŮŮŮŮŮŮŮ", "ƆƆƆƆƆƆƆƆƆƆ"));
		bh.consume(collection.containsKey("ĆĆĆĆĆĆĆĆĆĆ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ĩĩĩĩĩĩĩĩĩĩ", "ŠŠŠŠŠŠŠŠŠŠ"));
		bh.consume(collection.containsKey("ēēēēēēēēēē"));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.get("ÓÓÓÓÓÓÓÓÓÓ"));
		bh.consume(collection.keySet());
		bh.consume(collection.remove("ƀƀƀƀƀƀƀƀƀƀ"));
		bh.consume(collection.get("êêêêêêêêêê"));
		bh.consume(collection.containsKey("ōōōōōōōōōō"));
		bh.consume(collection.containsKey("ŰŰŰŰŰŰŰŰŰŰ"));
		bh.consume(collection.replace("šššššššššš", "ŲŲŲŲŲŲŲŲŲŲ"));
		bh.consume(collection.get("ŵŵŵŵŵŵŵŵŵŵ"));
		bh.consume(collection.get("řřřřřřřřřř"));
		bh.consume(collection.remove("ƉƉƉƉƉƉƉƉƉƉ"));
		bh.consume(collection.get("ěěěěěěěěěě"));
		bh.consume(collection.replace("ŜŜŜŜŜŜŜŜŜŜ", "ìììììììììì"));
		bh.consume(collection.containsKey("ÌÌÌÌÌÌÌÌÌÌ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ţţţţţţţţţţ", "××××××××××"));
		bh.consume(collection.values());
		bh.consume(collection.get("ŮŮŮŮŮŮŮŮŮŮ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("źźźźźźźźźź"));
		bh.consume(collection.remove("åååååååååå"));
		bh.consume(collection.values());
		bh.consume(collection.get("ėėėėėėėėėė"));
		bh.consume(collection.values());
		bh.consume(collection.get("ďďďďďďďďďď"));
		bh.consume(collection.get("ūūūūūūūūūū"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.get("ŷŷŷŷŷŷŷŷŷŷ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ŖŖŖŖŖŖŖŖŖŖ", "ČČČČČČČČČČ"));
		bh.consume(collection.get("ŦŦŦŦŦŦŦŦŦŦ"));
		bh.consume(collection.replace("üüüüüüüüüü", "ōōōōōōōōōō"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ßßßßßßßßßß", "ÝÝÝÝÝÝÝÝÝÝ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("çççççççççç", "ĲĲĲĲĲĲĲĲĲĲ"));
		bh.consume(collection.containsKey("ÚÚÚÚÚÚÚÚÚÚ"));
		bh.consume(collection.replace("ƆƆƆƆƆƆƆƆƆƆ", "ĒĒĒĒĒĒĒĒĒĒ"));
		bh.consume(collection.get("ïïïïïïïïïï"));
		bh.consume(collection.replace("ĴĴĴĴĴĴĴĴĴĴ", "íííííííííí"));
		bh.consume(collection.containsKey("ĵĵĵĵĵĵĵĵĵĵ"));
		bh.consume(collection.replace("üüüüüüüüüü", "ÜÜÜÜÜÜÜÜÜÜ"));
		bh.consume(collection.containsKey("ØØØØØØØØØØ"));
		bh.consume(collection.get("ĕĕĕĕĕĕĕĕĕĕ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ćććććććććć", "ſſſſſſſſſſ"));
		bh.consume(collection.containsKey("ďďďďďďďďďď"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ąąąąąąąąąą"));
		bh.consume(collection.containsKey("ïïïïïïïïïï"));
		bh.consume(collection.remove("ÐÐÐÐÐÐÐÐÐÐ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĥĥĥĥĥĥĥĥĥĥ"));
		bh.consume(collection.containsKey("ĖĖĖĖĖĖĖĖĖĖ"));
		bh.consume(collection.containsKey("ĠĠĠĠĠĠĠĠĠĠ"));
		bh.consume(collection.replace("ââââââââââ", "şşşşşşşşşş"));
		bh.consume(collection.replace("ņņņņņņņņņņ", "ůůůůůůůůůů"));
		bh.consume(collection.replace("ăăăăăăăăăă", "ĵĵĵĵĵĵĵĵĵĵ"));
		bh.consume(collection.replace("ÑÑÑÑÑÑÑÑÑÑ", "ùùùùùùùùùù"));
		bh.consume(collection.values());
		bh.consume(collection.replace("đđđđđđđđđđ", "ÚÚÚÚÚÚÚÚÚÚ"));
		bh.consume(collection.values());
		bh.consume(collection.remove("åååååååååå"));
		bh.consume(collection.replace("řřřřřřřřřř", "ğğğğğğğğğğ"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("ðððððððððð"));
		bh.consume(collection.containsKey("ŬŬŬŬŬŬŬŬŬŬ"));
		bh.consume(collection.replace("ċċċċċċċċċċ", "ðððððððððð"));
		bh.consume(collection.containsKey("ĝĝĝĝĝĝĝĝĝĝ"));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get("ĈĈĈĈĈĈĈĈĈĈ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.get("ļļļļļļļļļļ"));
		bh.consume(collection.replace("ŒŒŒŒŒŒŒŒŒŒ", "űűűűűűűűűű"));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.replace("žžžžžžžžžž", "ƈƈƈƈƈƈƈƈƈƈ"));
		bh.consume(collection.replace("òòòòòòòòòò", "þþþþþþþþþþ"));
		bh.consume(collection.replace("ÚÚÚÚÚÚÚÚÚÚ", "ŨŨŨŨŨŨŨŨŨŨ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ææææææææææ", "îîîîîîîîîî"));
		bh.consume(collection.containsKey("ŴŴŴŴŴŴŴŴŴŴ"));
		bh.consume(collection.containsKey("ãããããããããã"));
		bh.consume(collection.containsKey("ăăăăăăăăăă"));
		bh.consume(collection.containsKey("ĲĲĲĲĲĲĲĲĲĲ"));
		bh.consume(collection.get("ŔŔŔŔŔŔŔŔŔŔ"));
		bh.consume(collection.containsKey("ŭŭŭŭŭŭŭŭŭŭ"));
		bh.consume(collection.replace("ÉÉÉÉÉÉÉÉÉÉ", "ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.get("øøøøøøøøøø"));
		bh.consume(collection.containsKey("ŠŠŠŠŠŠŠŠŠŠ"));
		bh.consume(collection.containsKey("ŐŐŐŐŐŐŐŐŐŐ"));
		bh.consume(collection.replace("İİİİİİİİİİ", "ŸŸŸŸŸŸŸŸŸŸ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ƆƆƆƆƆƆƆƆƆƆ", "÷÷÷÷÷÷÷÷÷÷"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ņņņņņņņņņņ", "ěěěěěěěěěě"));
		bh.consume(collection.remove("ąąąąąąąąąą"));
		bh.consume(collection.get("þþþþþþþþþþ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ĝĝĝĝĝĝĝĝĝĝ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("ƊƊƊƊƊƊƊƊƊƊ", "ũũũũũũũũũũ"));
		bh.consume(collection.replace("ăăăăăăăăăă", "ƂƂƂƂƂƂƂƂƂƂ"));
		bh.consume(collection.get("ļļļļļļļļļļ"));
		bh.consume(collection.values());
		bh.consume(collection.replace("ŎŎŎŎŎŎŎŎŎŎ", "ůůůůůůůůůů"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ĤĤĤĤĤĤĤĤĤĤ"));
		bh.consume(collection.containsKey("ńńńńńńńńńń"));
		bh.consume(collection.containsKey("ëëëëëëëëëë"));
		bh.consume(collection.replace("źźźźźźźźźź", "ÙÙÙÙÙÙÙÙÙÙ"));
		bh.consume(collection.containsKey("şşşşşşşşşş"));
		bh.consume(collection.containsKey("ĴĴĴĴĴĴĴĴĴĴ"));
		bh.consume(collection.remove("ůůůůůůůůůů"));
		bh.consume(collection.remove("ŷŷŷŷŷŷŷŷŷŷ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ŧŧŧŧŧŧŧŧŧŧ"));
		bh.consume(collection.get("íííííííííí"));
		bh.consume(collection.values());
		bh.consume(collection.remove("ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.values());
		bh.consume(collection.remove("ŦŦŦŦŦŦŦŦŦŦ"));
		bh.consume(collection.containsKey("ıııııııııı"));
		bh.consume(collection.containsKey("ĚĚĚĚĚĚĚĚĚĚ"));
		bh.consume(collection.replace("ýýýýýýýýýý", "ÐÐÐÐÐÐÐÐÐÐ"));
		bh.consume(collection.remove("××××××××××"));
		bh.consume(collection.keySet());
		bh.consume(collection.get("ÏÏÏÏÏÏÏÏÏÏ"));
		bh.consume(collection.get("ØØØØØØØØØØ"));
		bh.consume(collection.get("ƊƊƊƊƊƊƊƊƊƊ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.remove("őőőőőőőőőő"));
		bh.consume(collection.replace("ŇŇŇŇŇŇŇŇŇŇ", "ŝŝŝŝŝŝŝŝŝŝ"));
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ųųųųųųųųųų", "ĂĂĂĂĂĂĂĂĂĂ"));
		bh.consume(collection.remove("ģģģģģģģģģģ"));
		bh.consume(collection.replace("šššššššššš", "ţţţţţţţţţţ"));
		bh.consume(collection.containsKey("ƅƅƅƅƅƅƅƅƅƅ"));
		bh.consume(collection.containsKey("××××××××××"));
		bh.consume(collection.get("öööööööööö"));
		bh.consume(collection.get("ķķķķķķķķķķ"));
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ŇŇŇŇŇŇŇŇŇŇ"));
		bh.consume(collection.replace("ŤŤŤŤŤŤŤŤŤŤ", "ĨĨĨĨĨĨĨĨĨĨ"));
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ąąąąąąąąąą"));
		bh.consume(collection.containsKey("ĐĐĐĐĐĐĐĐĐĐ"));
		bh.consume(collection.keySet());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.replace("ŤŤŤŤŤŤŤŤŤŤ", "ŊŊŊŊŊŊŊŊŊŊ"));
		bh.consume(collection.replace("ƉƉƉƉƉƉƉƉƉƉ", "êêêêêêêêêê"));
		bh.consume(collection.replace("ƅƅƅƅƅƅƅƅƅƅ", "ââââââââââ"));
		bh.consume(collection.keySet());
		bh.consume(collection.remove("üüüüüüüüüü"));
		bh.consume(collection.containsKey("ÛÛÛÛÛÛÛÛÛÛ"));
		bh.consume(collection.remove("ÕÕÕÕÕÕÕÕÕÕ"));
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.keySet());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.values());
		bh.consume(collection.containsKey("ƊƊƊƊƊƊƊƊƊƊ"));
		bh.consume(collection.keySet());
		bh.consume(collection.replace("ęęęęęęęęęę", "òòòòòòòòòò"));
		bh.consume(collection.containsKey("ċċċċċċċċċċ"));
		bh.consume(collection.replace("ĨĨĨĨĨĨĨĨĨĨ", "ðððððððððð"));
		bh.consume(collection.replace("ŧŧŧŧŧŧŧŧŧŧ", "éééééééééé"));
		bh.consume(collection.get("ĐĐĐĐĐĐĐĐĐĐ"));
		bh.consume(collection.keySet());
		bh.consume(collection.containsKey("ĿĿĿĿĿĿĿĿĿĿ"));
		bh.consume(collection.containsKey("ËËËËËËËËËË"));
		bh.consume(collection.replace("ŀŀŀŀŀŀŀŀŀŀ", "šššššššššš"));
		bh.consume(collection.replace("ŖŖŖŖŖŖŖŖŖŖ", "ŽŽŽŽŽŽŽŽŽŽ"));
		bh.consume(collection.replace("ăăăăăăăăăă", "ĲĲĲĲĲĲĲĲĲĲ"));
	}
}
