package com.adalbert;
import java.util
import scala.collection.immutable
import scala.collection.mutable
import scala.reflect.classTag
import org.openjdk.jmh.annotations._
import org.openjdk.jmh.infra._

@State(Scope.Benchmark)
class S_Profile4AllSets_SLinkedSet_20220429190546974 {
	var collection = mutable.LinkedHashSet[Character]()
	@Setup(Level.Invocation)
	def setupSLinkedSet(): Unit = {
		collection = mutable.LinkedHashSet[Character]()
		collection.add('ė')
		collection.add('ż')
		collection.add('Ÿ')
		collection.add('ę')
		collection.add('ú')
		collection.add('ā')
		collection.add('Ě')
		collection.add('Ŵ')
		collection.add('ŗ')
		collection.add('Ū')
		collection.add('ũ')
		collection.add('ŝ')
		collection.add('ŭ')
		collection.add('Ģ')
		collection.add('ľ')
		collection.add('ŝ')
		collection.add('ť')
		collection.add('ç')
		collection.add('Û')
		collection.add('Ů')
		collection.add('Œ')
		collection.add('Ŗ')
		collection.add('ĉ')
		collection.add('Ĺ')
		collection.add('Ĺ')
		collection.add('ă')
		collection.add('ĭ')
		collection.add('Ď')
		collection.add('Ģ')
		collection.add('ņ')
		collection.add('ƅ')
		collection.add('Ĺ')
		collection.add('ĭ')
		collection.add('ı')
		collection.add('Ű')
		collection.add('Ş')
		collection.add('İ')
		collection.add('Ű')
		collection.add('Õ')
		collection.add('Ń')
		collection.add('Ų')
		collection.add('Ŷ')
		collection.add('Ƃ')
		collection.add('Ī')
		collection.add('Ɔ')
		collection.add('Ë')
		collection.add('î')
		collection.add('Ś')
		collection.add('Ɖ')
		collection.add('Ō')
		collection.add('ļ')
		collection.add('ĥ')
		collection.add('è')
		collection.add('Ĩ')
		collection.add('ř')
		collection.add('ë')
		collection.add('Ï')
		collection.add('Ļ')
		collection.add('Ż')
		collection.add('Ţ')
		collection.add('Ƈ')
		collection.add('ŧ')
		collection.add('ð')
		collection.add('Ş')
		collection.add('é')
		collection.add('Ų')
		collection.add('á')
		collection.add('š')
		collection.add('Ĭ')
		collection.add('Ĝ')
		collection.add('ă')
		collection.add('Ɖ')
		collection.add('ã')
		collection.add('Ó')
		collection.add('Ƃ')
		collection.add('Ɔ')
		collection.add('Ď')
		collection.add('Ñ')
		collection.add('ŗ')
		collection.add('É')
		collection.add('ŕ')
		collection.add('Ƃ')
		collection.add('ķ')
		collection.add('Í')
		collection.add('Ġ')
		collection.add('đ')
		collection.add('Ɓ')
		collection.add('ź')
		collection.add('ò')
		collection.add('Ľ')
		collection.add('Œ')
		collection.add('Ũ')
		collection.add('í')
		collection.add('ť')
		collection.add('Ā')
		collection.add('ŝ')
		collection.add('Ï')
		collection.add('Ĝ')
		collection.add('Ð')
		collection.add('ŵ')
		collection.add('Ë')
		collection.add('ŝ')
		collection.add('Ô')
		collection.add('Ü')
		collection.add('Ī')
		collection.add('ŏ')
		collection.add('Ą')
		collection.add('ę')
		collection.add('Î')
		collection.add('ĕ')
		collection.add('Ĥ')
		collection.add('Ų')
		collection.add('Ă')
		collection.add('å')
		collection.add('ť')
		collection.add('à')
		collection.add('Š')
		collection.add('Ð')
		collection.add('ŀ')
		collection.add('ċ')
		collection.add('ù')
		collection.add('÷')
		collection.add('ã')
		collection.add('Ş')
		collection.add('Ǝ')
		collection.add('ũ')
		collection.add('Ü')
		collection.add('ŵ')
		collection.add('ĳ')
		collection.add('ƅ')
		collection.add('Ì')
		collection.add('ä')
		collection.add('Ũ')
		collection.add('ø')
		collection.add('Ù')
		collection.add('Ő')
		collection.add('ƃ')
		collection.add('Đ')
		collection.add('Š')
		collection.add('ſ')
		collection.add('Ù')
		collection.add('ÿ')
		collection.add('ś')
		collection.add('ÿ')
		collection.add('ø')
		collection.add('ē')
		collection.add('Ÿ')
		collection.add('ƈ')
		collection.add('ï')
		collection.add('Ũ')
		collection.add('í')
		collection.add('š')
		collection.add('Ô')
		collection.add('ê')
		collection.add('ÿ')
		collection.add('Ô')
		collection.add('Ŕ')
		collection.add('Ź')
		collection.add('Ə')
		collection.add('ë')
		collection.add('Ɓ')
		collection.add('Í')
		collection.add('ď')
		collection.add('Ŏ')
		collection.add('ś')
		collection.add('ŋ')
		collection.add('Ï')
		collection.add('ď')
		collection.add('ĥ')
		collection.add('Ě')
		collection.add('Ÿ')
		collection.add('Ƅ')
		collection.add('ŏ')
		collection.add('Ú')
		collection.add('æ')
		collection.add('Ö')
		collection.add('œ')
		collection.add('è')
		collection.add('ŝ')
		collection.add('ą')
		collection.add('ƈ')
		collection.add('ī')
		collection.add('Ğ')
		collection.add('Ğ')
		collection.add('ĵ')
		collection.add('ĭ')
		collection.add('ĉ')
		collection.add('Ǝ')
		collection.add('ú')
		collection.add('Ö')
		collection.add('í')
		collection.add('Ý')
		collection.add('Ƈ')
		collection.add('Ċ')
		collection.add('ô')
		collection.add('ą')
		collection.add('ä')
		collection.add('ŵ')
		collection.add('ű')
		collection.add('ŷ')
		collection.add('ĩ')
		collection.add('þ')
		collection.add('ű')
		collection.add('ō')
		collection.add('Ÿ')
		collection.add('Ù')
		collection.add('Ů')
		collection.add('Ó')
		collection.add('ĩ')
		collection.add('Ɔ')
		collection.add('Ż')
		collection.add('š')
		collection.add('Õ')
		collection.add('Í')
		collection.add('ï')
		collection.add('Ŧ')
		collection.add('ĩ')
		collection.add('Ť')
		collection.add('ō')
		collection.add('ň')
		collection.add('Ĥ')
		collection.add('ƅ')
		collection.add('ì')
		collection.add('ğ')
		collection.add('ő')
		collection.add('Ć')
		collection.add('ä')
		collection.add('Ǝ')
		collection.add('Ø')
		collection.add('Ź')
		collection.add('Ă')
		collection.add('ƃ')
		collection.add('ŀ')
		collection.add('ƈ')
		collection.add('Ī')
		collection.add('ſ')
		collection.add('ä')
		collection.add('Ð')
		collection.add('Ā')
		collection.add('Ă')
		collection.add('į')
		collection.add('ĺ')
		collection.add('Ŕ')
		collection.add('Ì')
		collection.add('ě')
		collection.add('è')
		collection.add('Ĕ')
		collection.add('ų')
		collection.add('ŭ')
		collection.add('ù')
		collection.add('ĳ')
		collection.add('î')
		collection.add('Ŝ')
		collection.add('Ş')
		collection.add('ê')
		collection.add('Í')
		collection.add('ŋ')
		collection.add('ě')
		collection.add('Ŋ')
		collection.add('ë')
		collection.add('Ħ')
		collection.add('Ż')
		collection.add('ċ')
		collection.add('ñ')
		collection.add('Ǝ')
		collection.add('š')
		collection.add('Ĥ')
		collection.add('ŷ')
		collection.add('é')
		collection.add('Ɓ')
		collection.add('Ô')
		collection.add('Ɔ')
		collection.add('ć')
		collection.add('Ť')
		collection.add('Š')
		collection.add('Ø')
		collection.add('Û')
		collection.add('Ý')
		collection.add('ĕ')
		collection.add('ý')
		collection.add('Û')
		collection.add('ƍ')
		collection.add('ÿ')
		collection.add('É')
		collection.add('Ó')
		collection.add('Ě')
		collection.add('Ũ')
		collection.add('Ƃ')
		collection.add('Ą')
		collection.add('Ɔ')
		collection.add('Ž')
		collection.add('đ')
		collection.add('č')
		collection.add('Ü')
		collection.add('Ò')
		collection.add('ů')
		collection.add('Ź')
		collection.add('È')
		collection.add('å')
		collection.add('Ũ')
		collection.add('Ō')
		collection.add('Ò')
		collection.add('Č')
		collection.add('Ü')
		collection.add('ƃ')
		collection.add('ű')
		collection.add('ö')
		collection.add('ň')
		collection.add('ĉ')
		collection.add('ă')
		collection.add('ű')
		collection.add('Ğ')
		collection.add('Ò')
		collection.add('Ė')
		collection.add('Ŭ')
		collection.add('ŵ')
		collection.add('Ƃ')
		collection.add('Ě')
		collection.add('Ī')
		collection.add('ć')
		collection.add('ŷ')
		collection.add('ŗ')
		collection.add('Ž')
		collection.add('ö')
		collection.add('Ň')
		collection.add('Ə')
		collection.add('Į')
		collection.add('ŀ')
		collection.add('ø')
		collection.add('ŀ')
		collection.add('Ň')
		collection.add('ē')
		collection.add('û')
		collection.add('ó')
		collection.add('ĵ')
		collection.add('ŵ')
		collection.add('ĺ')
		collection.add('Ɓ')
		collection.add('ÿ')
		collection.add('Ɓ')
		collection.add('Ŵ')
		collection.add('Ý')
		collection.add('Ŭ')
		collection.add('ê')
		collection.add('ľ')
		collection.add('Ģ')
		collection.add('Ĵ')
		collection.add('Š')
		collection.add('ŧ')
		collection.add('ē')
		collection.add('ģ')
		collection.add('ŗ')
		collection.add('Œ')
		collection.add('î')
		collection.add('ę')
		collection.add('Ŵ')
		collection.add('ņ')
		collection.add('Ŵ')
		collection.add('Ņ')
		collection.add('ż')
		collection.add('Ś')
		collection.add('œ')
		collection.add('ŵ')
		collection.add('Ŗ')
		collection.add('ŧ')
		collection.add('é')
		collection.add('ĭ')
		collection.add('Ő')
		collection.add('Ì')
		collection.add('Ğ')
		collection.add('ű')
		collection.add('Ò')
		collection.add('ŷ')
		collection.add('Ĕ')
		collection.add('ƅ')
		collection.add('Ē')
		collection.add('ę')
		collection.add('Ń')
		collection.add('Ŀ')
		collection.add('Į')
		collection.add('Ĵ')
		collection.add('ĉ')
		collection.add('ű')
		collection.add('Ǝ')
		collection.add('Ũ')
		collection.add('ë')
		collection.add('î')
		collection.add('Ö')
		collection.add('Ş')
		collection.add('Ā')
		collection.add('ś')
		collection.add('ƍ')
		collection.add('ñ')
		collection.add('Ƃ')
		collection.add('ŧ')
		collection.add('ý')
		collection.add('Ŵ')
		collection.add('Ā')
		collection.add('Ś')
		collection.add('ã')
		collection.add('ſ')
		collection.add('ß')
		collection.add('ē')
		collection.add('Ĩ')
		collection.add('÷')
		collection.add('ĺ')
		collection.add('ŵ')
		collection.add('Ŕ')
		collection.add('ğ')
		collection.add('×')
		collection.add('ĕ')
		collection.add('ë')
		collection.add('ļ')
		collection.add('ŗ')
		collection.add('Ý')
		collection.add('ò')
		collection.add('Đ')
		collection.add('ō')
		collection.add('Ɓ')
		collection.add('ĥ')
		collection.add('ű')
		collection.add('ť')
		collection.add('â')
		collection.add('þ')
		collection.add('Ĳ')
		collection.add('Ą')
		collection.add('Ƈ')
		collection.add('ũ')
		collection.add('Į')
		collection.add('ŷ')
		collection.add('Ñ')
		collection.add('ũ')
		collection.add('Ů')
		collection.add('Ĺ')
		collection.add('ń')
		collection.add('ŉ')
		collection.add('ÿ')
		collection.add('Ř')
		collection.add('Ô')
		collection.add('Ć')
		collection.add('Ħ')
		collection.add('ƅ')
		collection.add('×')
		collection.add('š')
		collection.add('Ê')
		collection.add('Ŀ')
		collection.add('ó')
		collection.add('ŭ')
		collection.add('Ƈ')
		collection.add('Ũ')
		collection.add('Ŝ')
		collection.add('Ĳ')
		collection.add('×')
		collection.add('É')
		collection.add('Ĩ')
		collection.add('î')
		collection.add('Ɔ')
		collection.add('Ú')
		collection.add('ņ')
		collection.add('ĺ')
		collection.add('Ê')
		collection.add('Ø')
		collection.add('Č')
		collection.add('Ø')
		collection.add('ý')
		collection.add('Ā')
		collection.add('ă')
		collection.add('û')
		collection.add('ĺ')
		collection.add('Ķ')
		collection.add('Ċ')
		collection.add('š')
		collection.add('Į')
		collection.add('Ï')
		collection.add('û')
		collection.add('Ÿ')
		collection.add('ƅ')
		collection.add('ƈ')
		collection.add('Ţ')
		collection.add('ŭ')
		collection.add('ý')
		collection.add('Ũ')
		collection.add('œ')
		collection.add('Û')
		collection.add('ň')
		collection.add('Õ')
		collection.add('û')
		collection.add('Ţ')
		collection.add('ā')
		collection.add('ŝ')
		collection.add('ŋ')
		collection.add('ź')
		collection.add('Ď')
		collection.add('â')
		collection.add('ċ')
		collection.add('Ğ')
		collection.add('Ò')
		collection.add('Õ')
		collection.add('ĭ')
		collection.add('ƀ')
		collection.add('ċ')
		collection.add('Ŏ')
		collection.add('Ì')
		collection.add('Ē')
		collection.add('Ķ')
		collection.add('Û')
		collection.add('ā')
		collection.add('Đ')
		collection.add('ÿ')
		collection.add('đ')
		collection.add('Ň')
		collection.add('Ĺ')
		collection.add('Ù')
		collection.add('Ŷ')
		collection.add('ż')
		collection.add('Ō')
		collection.add('Ž')
		collection.add('Ĕ')
		collection.add('ŉ')
		collection.add('Ƃ')
		collection.add('ŵ')
		collection.add('Ĩ')
		collection.add('Ɓ')
		collection.add('ý')
		collection.add('î')
		collection.add('ı')
		collection.add('É')
		collection.add('Ť')
		collection.add('ƀ')
		collection.add('Ɖ')
		collection.add('Ÿ')
		collection.add('ŕ')
		collection.add('Ő')
		collection.add('Ť')
		collection.add('Ė')
		collection.add('ƀ')
		collection.add('ĉ')
		collection.add('ķ')
		collection.add('Ą')
		collection.add('ê')
		collection.add('Ŀ')
		collection.add('Ĝ')
		collection.add('ŗ')
		collection.add('æ')
		collection.add('Đ')
		collection.add('Ú')
		collection.add('Ô')
		collection.add('ļ')
		collection.add('ç')
		collection.add('į')
		collection.add('Ĵ')
		collection.add('ū')
		collection.add('Ą')
		collection.add('í')
		collection.add('Ů')
		collection.add('Ƌ')
		collection.add('ƀ')
		collection.add('î')
		collection.add('ĉ')
		collection.add('ů')
		collection.add('ı')
		collection.add('Ý')
		collection.add('ķ')
		collection.add('Ĩ')
		collection.add('Ź')
		collection.add('Ł')
		collection.add('Ĕ')
		collection.add('ũ')
		collection.add('Ɔ')
		collection.add('ç')
		collection.add('ƀ')
		collection.add('Ù')
		collection.add('Ɔ')
		collection.add('ė')
		collection.add('ā')
		collection.add('ć')
		collection.add('Ŷ')
		collection.add('ů')
		collection.add('Ø')
		collection.add('Ë')
		collection.add('Í')
		collection.add('ŝ')
		collection.add('Ø')
		collection.add('ƅ')
		collection.add('ô')
		collection.add('İ')
		collection.add('Õ')
		collection.add('ċ')
		collection.add('ç')
		collection.add('Ž')
		collection.add('Ɗ')
		collection.add('ţ')
		collection.add('ä')
		collection.add('ñ')
		collection.add('Ŕ')
		collection.add('ļ')
		collection.add('ğ')
		collection.add('œ')
		collection.add('Ĥ')
		collection.add('û')
		collection.add('Ţ')
		collection.add('ė')
		collection.add('ƌ')
		collection.add('Ù')
		collection.add('Ú')
		collection.add('ő')
		collection.add('đ')
		collection.add('Ħ')
		collection.add('ċ')
		collection.add('ù')
		collection.add('İ')
		collection.add('Ø')
		collection.add('ī')
		collection.add('Ĭ')
		collection.add('ŏ')
		collection.add('Ĵ')
		collection.add('ī')
		collection.add('ä')
		collection.add('Ź')
		collection.add('ù')
		collection.add('Ĭ')
		collection.add('ĸ')
		collection.add('ĥ')
		collection.add('Ĉ')
		collection.add('š')
		collection.add('ç')
		collection.add('Ÿ')
		collection.add('Ê')
		collection.add('Č')
		collection.add('Ŗ')
		collection.add('ƌ')
		collection.add('Ƈ')
		collection.add('è')
		collection.add('Ų')
		collection.add('Ė')
		collection.add('Ə')
		collection.add('Ĝ')
		collection.add('Î')
		collection.add('Ə')
		collection.add('ę')
		collection.add('Ŗ')
		collection.add('ŭ')
		collection.add('Ă')
		collection.add('Ŭ')
		collection.add('ī')
		collection.add('Ŷ')
		collection.add('ģ')
		collection.add('Ċ')
		collection.add('Ƃ')
		collection.add('ű')
		collection.add('ň')
		collection.add('Ķ')
		collection.add('Ş')
		collection.add('Ő')
		collection.add('ď')
		collection.add('Į')
		collection.add('Ú')
		collection.add('û')
		collection.add('ĭ')
		collection.add('Ė')
		collection.add('Ż')
		collection.add('þ')
		collection.add('ő')
		collection.add('Ə')
		collection.add('Ļ')
		collection.add('Ÿ')
		collection.add('Þ')
		collection.add('Ɔ')
		collection.add('ō')
		collection.add('Ļ')
		collection.add('ĩ')
		collection.add('ç')
		collection.add('š')
		collection.add('Ż')
		collection.add('ħ')
		collection.add('Ķ')
		collection.add('Ě')
		collection.add('Ğ')
		collection.add('ø')
		collection.add('ų')
		collection.add('Ƌ')
		collection.add('Ĉ')
		collection.add('ç')
		collection.add('Ɗ')
		collection.add('ĥ')
		collection.add('Ĕ')
		collection.add('Ġ')
		collection.add('ű')
		collection.add('Į')
		collection.add('ĭ')
		collection.add('ŭ')
		collection.add('ŵ')
		collection.add('ç')
		collection.add('Ź')
		collection.add('È')
		collection.add('Đ')
		collection.add('ƍ')
		collection.add('ƌ')
		collection.add('Ŗ')
		collection.add('à')
		collection.add('Í')
		collection.add('Ă')
		collection.add('ť')
		collection.add('Į')
		collection.add('Ğ')
		collection.add('Î')
		collection.add('ŝ')
		collection.add('ŵ')
		collection.add('Ď')
		collection.add('ŀ')
		collection.add('Ù')
		collection.add('ŵ')
		collection.add('ŉ')
		collection.add('ű')
		collection.add('ë')
		collection.add('Ŵ')
		collection.add('ĥ')
		collection.add('ƅ')
		collection.add('ù')
		collection.add('Î')
		collection.add('Ò')
		collection.add('Œ')
		collection.add('Ě')
		collection.add('Ŝ')
		collection.add('ķ')
		collection.add('Ĕ')
		collection.add('Ï')
		collection.add('Ķ')
		collection.add('Ė')
		collection.add('ø')
		collection.add('Î')
		collection.add('Ɗ')
		collection.add('Ě')
		collection.add('â')
		collection.add('Ɖ')
		collection.add('ě')
		collection.add('Ħ')
		collection.add('œ')
		collection.add('Ţ')
		collection.add('Ņ')
		collection.add('Ť')
		collection.add('ê')
		collection.add('Ŋ')
		collection.add('ô')
		collection.add('ī')
		collection.add('ƈ')
		collection.add('ſ')
		collection.add('ö')
		collection.add('ð')
		collection.add('Ɖ')
		collection.add('ą')
		collection.add('Û')
		collection.add('Ę')
		collection.add('â')
		collection.add('ľ')
		collection.add('ë')
		collection.add('Ğ')
		collection.add('È')
		collection.add('Ó')
		collection.add('í')
		collection.add('ô')
		collection.add('Ġ')
		collection.add('ê')
		collection.add('Ů')
		collection.add('ú')
		collection.add('ê')
		collection.add('Ń')
		collection.add('ä')
		collection.add('Ė')
		collection.add('ď')
		collection.add('Ž')
		collection.add('ı')
		collection.add('Ŕ')
		collection.add('ü')
		collection.add('ŭ')
		collection.add('ď')
		collection.add('ş')
		collection.add('ř')
		collection.add('ŭ')
		collection.add('ĸ')
		collection.add('Ġ')
		collection.add('Đ')
		collection.add('à')
		collection.add('ĉ')
		collection.add('ţ')
		collection.add('ö')
		collection.add('ų')
		collection.add('Ü')
		collection.add('Ŭ')
		collection.add('Đ')
		collection.add('Õ')
		collection.add('Ǝ')
		collection.add('ĩ')
		collection.add('ó')
		collection.add('ļ')
		collection.add('è')
		collection.add('Ŕ')
		collection.add('ì')
		collection.add('ù')
		collection.add('į')
		collection.add('İ')
		collection.add('û')
		collection.add('Ŕ')
		collection.add('ē')
		collection.add('ĥ')
		collection.add('î')
		collection.add('Ĳ')
		collection.add('Ƅ')
		collection.add('ű')
		collection.add('Ö')
		collection.add('Ř')
		collection.add('Î')
		collection.add('ñ')
		collection.add('Ũ')
		collection.add('Ê')
		collection.add('ŵ')
		collection.add('Ć')
		collection.add('ŵ')
		collection.add('Ê')
		collection.add('ŀ')
		collection.add('Ƌ')
		collection.add('ũ')
		collection.add('ū')
		collection.add('ŀ')
		collection.add('æ')
		collection.add('ş')
		collection.add('ď')
		collection.add('Ľ')
		collection.add('Ɓ')
		collection.add('Ź')
		collection.add('Ƅ')
		collection.add('ý')
		collection.add('ł')
		collection.add('ņ')
		collection.add('Č')
		collection.add('Ş')
		collection.add('Ű')
		collection.add('Ï')
		collection.add('ť')
		collection.add('ī')
		collection.add('ś')
		collection.add('È')
		collection.add('Ō')
		collection.add('Ł')
		collection.add('đ')
		collection.add('Ƃ')
		collection.add('î')
		collection.add('ŝ')
		collection.add('Ý')
		collection.add('Ġ')
		collection.add('ė')
		collection.add('Þ')
		collection.add('ƅ')
		collection.add('Ŧ')
		collection.add('Ľ')
		collection.add('Ņ')
		collection.add('Ƃ')
		collection.add('Ò')
		collection.add('ı')
		collection.add('á')
		collection.add('Ņ')
		collection.add('ī')
		collection.add('Ž')
		collection.add('ù')
		collection.add('ū')
		collection.add('Ū')
		collection.add('Ę')
		collection.add('Ŋ')
		collection.add('ě')
		collection.add('Ó')
		collection.add('ě')
		collection.add('Ć')
		collection.add('ĸ')
		collection.add('Ì')
		collection.add('ţ')
		collection.add('Į')
		collection.add('Ř')
		collection.add('ƍ')
		collection.add('Ò')
		collection.add('Ö')
		collection.add('Ũ')
		collection.add('å')
		collection.add('ķ')
		collection.add('ű')
		collection.add('ĩ')
		collection.add('ů')
		collection.add('Ë')
		collection.add('Ñ')
		collection.add('Ë')
		collection.add('ā')
		collection.add('ś')
		collection.add('ž')
		collection.add('Û')
		collection.add('ú')
		collection.add('Ś')
		collection.add('ŭ')
		collection.add('ŧ')
		collection.add('Ŷ')
		collection.add('í')
		collection.add('Ŵ')
		collection.add('í')
		collection.add('ò')
		collection.add('Ű')
		collection.add('ŝ')
		collection.add('ż')
		collection.add('ċ')
		collection.add('Ł')
		collection.add('ć')
		collection.add('ü')
		collection.add('Ť')
		collection.add('ģ')
		collection.add('ņ')
		collection.add('è')
		collection.add('Ň')
		collection.add('õ')
		collection.add('ã')
		collection.add('Ɗ')
		collection.add('ù')
		collection.add('Ì')
		collection.add('æ')
		collection.add('Ŕ')
		collection.add('ƅ')
		collection.add('Ŧ')
		collection.add('ŏ')
		collection.add('ž')
		collection.add('ń')
		collection.add('Ŕ')
		collection.add('Ÿ')
		collection.add('å')
		collection.add('Ų')
		collection.add('ē')
		collection.add('é')
		collection.add('Č')
		collection.add('å')
		collection.add('à')
		collection.add('Ý')
		collection.add('Ÿ')
		collection.add('ĕ')
		collection.add('ŕ')
		collection.add('ó')
		collection.add('ċ')
		collection.add('Ġ')
		collection.add('ś')
		collection.add('é')
		collection.add('ć')
		collection.add('Ě')
		collection.add('Ļ')
		collection.add('ŝ')
		collection.add('ƌ')
		collection.add('Þ')
		collection.add('Ɓ')
		collection.add('Ď')
		collection.add('Ľ')
		collection.add('ī')
		collection.add('Ś')
		collection.add('ŷ')
		collection.add('Ê')
		collection.add('ƍ')
		collection.add('ĭ')
		collection.add('ā')
		collection.add('Ĩ')
		collection.add('ú')
		collection.add('Ē')
		collection.add('ƅ')
		collection.add('Œ')
		collection.add('ŋ')
		collection.add('í')
		collection.add('Ê')
		collection.add('č')
		collection.add('ä')
		collection.add('Û')
		collection.add('Ñ')
		collection.add('č')
		collection.add('ì')
		collection.add('ý')
		collection.add('ê')
		collection.add('ò')
		collection.add('Ď')
		collection.add('Ň')
		collection.add('ĺ')
		collection.add('Ľ')
		collection.add('Ý')
		collection.add('Ɓ')
		collection.add('Ĳ')
		collection.add('í')
		collection.add('Ø')
		collection.add('Ő')
		collection.add('Ŋ')
		collection.add('Ŏ')
		collection.add('ċ')
		collection.add('Í')
		collection.add('Ÿ')
		collection.add('ţ')
		collection.add('Ŝ')
		collection.add('Ť')
		collection.add('ļ')
		collection.add('Ŷ')
		collection.add('ő')
		collection.add('Š')
		collection.add('ĕ')
		collection.add('į')
		collection.add('ŀ')
		collection.add('Ö')
		collection.add('ū')
		collection.add('á')
		collection.add('á')
		collection.add('ð')
		collection.add('ğ')
		collection.add('Ô')
		collection.add('ċ')
		collection.add('š')
		collection.add('ź')
		collection.add('ŉ')
		collection.add('ē')
		collection.add('ŕ')
		collection.add('Ŀ')
		collection.add('Ò')
		collection.add('Ś')
		collection.add('Ĕ')
		collection.add('ƌ')
		collection.add('ê')
		collection.add('Ï')
		collection.add('Ê')
		collection.add('ś')
		collection.add('ĝ')
		collection.add('ç')
		collection.add('í')
		collection.add('ē')
		collection.add('ð')
		collection.add('Ǝ')
		collection.add('Ɔ')
		collection.add('Ŝ')
		collection.add('ĕ')
		collection.add('đ')
		collection.add('ë')
		collection.add('ß')
		collection.add('ƈ')
		collection.add('Ŵ')
		collection.add('þ')
		collection.add('Ű')
		collection.add('Ľ')
		collection.add('ĺ')
		collection.add('ƃ')
		collection.add('Š')
		collection.add('Ë')
		collection.add('ē')
		collection.add('Ŀ')
		collection.add('ŏ')
		collection.add('đ')
		collection.add('Ŀ')
		collection.add('ŉ')
		collection.add('Ĉ')
		collection.add('ġ')
		collection.add('Ū')
		collection.add('Ō')
		collection.add('ĥ')
		collection.add('Ĭ')
		collection.add('į')
		collection.add('Ǝ')
		collection.add('ĥ')
		collection.add('Č')
		collection.add('Ė')
		collection.add('û')
		collection.add('Ļ')
		collection.add('ŭ')
		collection.add('ì')
		collection.add('Ĩ')
		collection.add('Ů')
		collection.add('ù')
		collection.add('Ý')
		collection.add('Ĺ')
		collection.add('ů')
		collection.add('ĺ')
		collection.add('Ô')
		collection.add('ŧ')
		collection.add('Ê')
		collection.add('ç')
		collection.add('Ĳ')
		collection.add('ď')
		collection.add('Ć')
		collection.add('Ŀ')
		collection.add('ŉ')
		collection.add('ń')
		collection.add('î')
		collection.add('ƍ')
		collection.add('ê')
		collection.add('ö')
		collection.add('ň')
		collection.add('ĳ')
		collection.add('ļ')
		collection.add('Ɓ')
		collection.add('Ć')
		collection.add('Ŗ')
		collection.add('ý')
		collection.add('İ')
		collection.add('Ũ')
		collection.add('Ƅ')
		collection.add('ÿ')
		collection.add('×')
		collection.add('ø')
		collection.add('Ĺ')
		collection.add('ó')
		collection.add('Ĩ')
		collection.add('ě')
		collection.add('Ř')
		collection.add('ý')
		collection.add('Ő')
		collection.add('È')
		collection.add('Ľ')
		collection.add('ī')
		collection.add('Ź')
		collection.add('Ŭ')
		collection.add('Ğ')
		collection.add('Ù')
		collection.add('é')
		collection.add('Ĕ')
		collection.add('ő')
		collection.add('â')
		collection.add('Õ')
		collection.add('ň')
		collection.add('ţ')
		collection.add('Ò')
		collection.add('Ĺ')
		collection.add('Ũ')
		collection.add('Ř')
		collection.add('ƌ')
		collection.add('Ő')
		collection.add('ľ')
		collection.add('ż')
		collection.add('Č')
		collection.add('Ď')
		collection.add('ƌ')
		collection.add('ô')
		collection.add('Ą')
		collection.add('Ö')
		collection.add('í')
		collection.add('į')
		collection.add('ý')
		collection.add('ĸ')
		collection.add('Ĩ')
		collection.add('Ī')
		collection.add('ĉ')
		collection.add('ū')
		collection.add('ċ')
		collection.add('Ĉ')
		collection.add('ñ')
		collection.add('Ǝ')
		collection.add('Ĉ')
		collection.add('Ú')
		collection.add('Ľ')
		collection.add('č')
		collection.add('Ğ')
		collection.add('ĕ')
		collection.add('Õ')
		collection.add('ĩ')
		collection.add('ė')
		collection.add('ō')
		collection.add('Ŝ')
		collection.add('Ġ')
		collection.add('÷')
		collection.add('ô')
		collection.add('ŏ')
		collection.add('Ü')
		collection.add('Ŋ')
		collection.add('ĩ')
		collection.add('é')
		collection.add('Ś')
		collection.add('Ɖ')
		collection.add('ô')
		collection.add('÷')
		collection.add('ś')
		collection.add('ŀ')
		collection.add('ĩ')
		collection.add('ŗ')
		collection.add('ŕ')
		collection.add('Œ')
		collection.add('ĳ')
		collection.add('Ę')
		collection.add('ž')
		collection.add('ÿ')
		collection.add('ũ')
		collection.add('Ķ')
		collection.add('Ĉ')
		collection.add('ņ')
		collection.add('Į')
		collection.add('ĵ')
		collection.add('Ƃ')
		collection.add('ō')
		collection.add('í')
		collection.add('ū')
		collection.add('ú')
		collection.add('Ų')
		collection.add('ő')
		collection.add('ë')
		collection.add('Ņ')
		collection.add('ġ')
		collection.add('Ů')
		collection.add('ñ')
		collection.add('Ÿ')
		collection.add('ŝ')
	}
	@Benchmark
	@Fork(1)
	@Warmup(time=3)
	@Measurement(time=3,iterations=10)
	def SLinkedSet(bh: Blackhole): Unit = {
		collection = collection.union(mutable.HashSet[Character]('ż','ő','Ŏ','ĥ','Ő','â','Ň','Ŕ'))
		bh.consume(collection.add('æ'))
		collection = collection.union(mutable.HashSet[Character]('ì','Ć','ñ','ł','ī','Ù'))
		bh.consume(collection.add('œ'))
		bh.consume(collection.add('Ŗ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('č','í','Ń','ż','ñ')))
		collection = collection.diff(mutable.HashSet[Character]('Ī','ò','ť','à','ŷ','ò','û'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ġ','Ņ','ƌ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('đ','Ą','Ċ','ú')))
		collection = collection.union(mutable.HashSet[Character]('Ļ','Ŷ','û'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ì','Ė','Ĳ','ū','ƈ','Ɓ','ź'))
		collection = collection.union(mutable.HashSet[Character]('Ņ','ŭ','Ŵ','ś','ý','Í','î','Ű'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ĝ','Ĺ','Ū','É','Ũ','ť','ŀ')))
		collection = collection.union(mutable.HashSet[Character]('ß','ğ','ñ','ó'))
		collection = collection.union(mutable.HashSet[Character]('ś','Ì','Ì'))
		bh.consume(collection.add('ų'))
		bh.consume(collection.add('ò'))
		bh.consume(collection.add('ã'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ò','ď','Ŝ','Ż','ƍ','Ř')))
		collection = collection.diff(mutable.HashSet[Character]('è','þ','ģ','ġ','Ņ','æ','ÿ','ƈ','Ŷ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ĭ'))
		collection = collection.union(mutable.HashSet[Character]('ì','Ŷ','Ē','Ž','ƃ','ċ','Ŋ'))
		collection = collection.union(mutable.HashSet[Character]('Ō','Ų','Ɗ','×','Ŀ','ũ','Ű'))
		bh.consume(collection.add('đ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ţ','ă','Ū','Ų','ť','ţ','ù','Ĝ')))
		collection = collection.union(mutable.HashSet[Character]('ġ','Û','Ƅ','Î','Ż'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ō','Ú','Ɗ'))
		bh.consume(collection.remove('Ċ'))
		bh.consume(collection.contains('Ĕ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.remove('Ò'))
		bh.consume(collection.add('ö'))
		collection = collection.union(mutable.HashSet[Character]('ƈ','ô','Ć','Ɔ','İ','Ǝ','Ɖ'))
		bh.consume(collection.add('Ŝ'))
		bh.consume(collection.add('ŭ'))
		collection = collection.diff(mutable.HashSet[Character]('ť','ĳ','Ĺ','Ŷ','æ','Ŭ'))
		collection = collection.diff(mutable.HashSet[Character]('ĩ','ï','ń','Ė','Ĥ','ů','ņ','ą'))
		collection = collection.union(mutable.HashSet[Character]('Č','ƌ','Ɗ','æ','Õ'))
		collection = collection.union(mutable.HashSet[Character]('ŵ','Ś','Đ','Ů','Ż','ƌ'))
		bh.consume(collection.contains('Û'))
		bh.consume(collection.add('Ť'))
		bh.consume(collection.add('Ą'))
		collection = collection.union(mutable.HashSet[Character]('Ĥ','à','ť','Ù','đ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Õ'))
		bh.consume(collection.remove('Ń'))
		bh.consume(collection.add('Ź'))
		collection = collection.diff(mutable.HashSet[Character]('Ë','ſ','Ď'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ń','ř','Ə','Ü')))
		bh.consume(collection.add('Ö'))
		collection = collection.union(mutable.HashSet[Character]('Ļ','Ĺ','Ē','ĝ','ê','ô','ß','Ê','ù'))
		collection = collection.diff(mutable.HashSet[Character]('ļ','ô','ğ','Ć','č'))
		bh.consume(collection.remove('þ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ź'))
		bh.consume(collection.remove('Ŭ'))
		collection = collection.diff(mutable.HashSet[Character]('ð','ã','ŷ','Į','ŉ','ĭ','Ĉ','Ɓ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ø','í','Ż','ņ')))
		collection = collection.union(mutable.HashSet[Character]('Ŷ','Ž','ű','÷','ħ','ŧ','ß','ŋ','đ'))
		collection = collection.diff(mutable.HashSet[Character]('ğ','Ż','Ĵ','Ø','È','Š','Ÿ','đ','Ə'))
		bh.consume(collection.add('Ź'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ń','Ł','Ĕ','Ī','è')))
		collection = collection.union(mutable.HashSet[Character]('Ì','Ŧ','Ŭ','Ĳ','ģ','Ú'))
		collection = collection.union(mutable.HashSet[Character]('ş','ö','ŕ','Ŋ','Ķ','ŝ','Ŕ'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Ĭ','Ɖ','ř','ŀ','ŉ','Ɔ','ũ','ė'))
		collection = collection.union(mutable.HashSet[Character]('Ö','Ö','ń','à','Ġ','Í','ĝ','Ż'))
		collection = collection.union(mutable.HashSet[Character]('ħ','ò','Õ'))
		bh.consume(collection.contains('Ě'))
		bh.consume(collection.add('ē'))
		collection = collection.union(mutable.HashSet[Character]('Ĉ','Ü','Ö','Ĝ','ì'))
		bh.consume(collection.add('Ś'))
		bh.consume(collection.add('Ɔ'))
		bh.consume(collection.remove('ñ'))
		bh.consume(collection.remove('Ń'))
		collection = collection.diff(mutable.HashSet[Character]('Ě','Ğ','ŷ'))
		bh.consume(collection.add('ì'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ş','ű','ƃ','Ň','Ń','Ò','í')))
		bh.consume(collection.add('ú'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('ŵ','đ','ï'))
		bh.consume(collection.remove('þ'))
		bh.consume(collection.remove('ŭ'))
		bh.consume(collection.add('Ə'))
		collection = collection.union(mutable.HashSet[Character]('Ÿ','Ŗ','Ɖ','ē','ń','Ī','ů','Ŷ','Ĉ'))
		bh.consume(collection.remove('Ø'))
		bh.consume(collection.add('ħ'))
		collection = collection.diff(mutable.HashSet[Character]('Ŕ','Ĭ','Š','Ă'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ë'))
		collection = collection.diff(mutable.HashSet[Character]('à','Ŧ','ç','ķ','Ý','þ','Ď','ň','Ĥ'))
		collection = collection.diff(mutable.HashSet[Character]('Ô','ź','ç','×','Ò','ı','Ĥ','ī'))
		collection = collection.diff(mutable.HashSet[Character]('Ģ','Ŷ','ė','Ē'))
		collection = collection.union(mutable.HashSet[Character]('Ï','ĳ','Ù','ą'))
		bh.consume(collection.add('û'))
		bh.consume(collection.add('Ė'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŝ','Ɓ','ƍ')))
		bh.consume(collection.remove('Ť'))
		bh.consume(collection.remove('ć'))
		collection = collection.union(mutable.HashSet[Character]('ŝ','š','Ŏ','í','ť','ļ'))
		collection = collection.diff(mutable.HashSet[Character]('Ž','ť','ĥ','ć','Ŧ','Ğ'))
		bh.consume(collection.add('á'))
		collection = collection.union(mutable.HashSet[Character]('ĉ','Ɗ','Ĥ','Ɗ','Ĵ','Ƅ'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ŵ','Í','Ɗ','ŕ','à','ř','œ','ó','ď'))
		bh.consume(collection.remove('Ę'))
		bh.consume(collection.contains('ŝ'))
		bh.consume(collection.add('å'))
		bh.consume(collection.add('Ġ'))
		bh.consume(collection.add('š'))
		bh.consume(collection.add('ź'))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Đ','Ţ','ƈ','É')))
		collection = collection.diff(mutable.HashSet[Character]('Ɗ','á','ĺ','Î','İ','Ğ','ð','Ô'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('â','Ć','ž','Ž','ě','û')))
		collection = collection.diff(mutable.HashSet[Character]('Ɓ','Ï','Ŏ','Ć','Ĺ','é','Ŏ'))
		bh.consume(collection.remove('ù'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŗ','Ă','Œ','ũ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('û','đ','Ƌ')))
		bh.consume(collection.add('ē'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ĕ'))
		collection = collection.diff(mutable.HashSet[Character]('á','Ś','ċ','õ','ï','ı','Ǝ','Ǝ'))
		bh.consume(collection.add('ĉ'))
		bh.consume(collection.remove('Ą'))
		collection = collection.diff(mutable.HashSet[Character]('Ş','ŧ','Ɗ','Ø','ţ','ĩ','Ü'))
		bh.consume(collection.add('Ù'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ţ'))
		bh.consume(collection.add('Ő'))
		bh.consume(collection.add('č'))
		bh.consume(collection.contains('ı'))
		bh.consume(collection.remove('ß'))
		bh.consume(collection.add('Ď'))
		bh.consume(collection.add('ĸ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŀ','ţ','Ö','ū','Ć')))
		collection = collection.union(mutable.HashSet[Character]('Ĭ','è','ĝ','ö'))
		collection = collection.union(mutable.HashSet[Character]('Û','è','Ľ','ř','ï','ď'))
		collection = collection.union(mutable.HashSet[Character]('Ž','Ũ','ē','Ÿ','ð'))
		bh.consume(collection.add('Ġ'))
		collection = collection.union(mutable.HashSet[Character]('į','Ū','Ĝ','Ę','Ů','ė','ŵ'))
		bh.consume(collection.add('û'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('æ','å','Ŗ','ÿ')))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ä','õ','Ś','œ','Ú','Ĩ')))
		bh.consume(collection.add('ś'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ß','Č','×','Ÿ','Ĭ','ù','Ǝ','Ƅ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ɔ','Ĭ','Ó','ĉ','Ɗ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ď','Ŧ','ĕ')))
		bh.consume(collection.add('í'))
		collection = collection.diff(mutable.HashSet[Character]('ő','ĭ','Ŵ','ó','Ġ'))
		collection = collection.union(mutable.HashSet[Character]('É','ĝ','ò','ļ','Ġ'))
		collection = collection.diff(mutable.HashSet[Character]('Ĥ','Ú','Ž','Ĳ','ű','ø','÷','ķ'))
		bh.consume(collection.add('ņ'))
		collection = collection.diff(mutable.HashSet[Character]('Ť','Ŏ','Š','Ũ','é'))
		bh.consume(collection.contains('ż'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ö','Ţ','Ő','ŧ','ş','Ÿ','ù','œ','ġ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ò','ŧ','ļ','į','ē')))
		bh.consume(collection.add('é'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Ë','Ĩ','Ð','Ý','ğ','ř','Ě','Ħ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ī','Ŝ','Ķ','Ÿ','ō')))
		collection = collection.union(mutable.HashSet[Character]('û','â','Ə','ų'))
		bh.consume(collection.contains('ù'))
		collection = collection.diff(mutable.HashSet[Character]('ő','ä','ç','ƈ','ŋ','ŀ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ė','ė','ĳ','ę','Ĺ','İ','ť')))
		collection = collection.union(mutable.HashSet[Character]('Ĥ','ú','Ŕ','È','ą','ų','ő'))
		bh.consume(collection.add('İ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ź','đ','č','ù','Ī','ŗ')))
		bh.consume(collection.remove('Ċ'))
		collection = collection.union(mutable.HashSet[Character]('Ź','ĩ','Ò','å','Ê','ō','ċ'))
		collection = collection.union(mutable.HashSet[Character]('ď','Ÿ','Ŷ'))
		bh.consume(collection.add('Ķ'))
		collection = collection.diff(mutable.HashSet[Character]('Ô','Ľ','ź','æ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Õ','ķ','ė','ê')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ŧ','ļ','Ƈ','ĳ')))
		collection = collection.diff(mutable.HashSet[Character]('ı','Ñ','Ļ','ĝ'))
		collection = collection.union(mutable.HashSet[Character]('Ž','ű','ê','ƈ','Ò'))
		collection = collection.union(mutable.HashSet[Character]('ă','ā','Ĥ','Ĩ','ķ','ć','Ž','î'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ŧ','û','Ş','Ɖ','ź','ğ','ƌ','ê')))
		collection = collection.union(mutable.HashSet[Character]('ñ','č','Ĺ','ž'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ľ','Č','ƅ')))
		collection = collection.diff(mutable.HashSet[Character]('ķ','ı','ĥ','Ĝ','ņ','Ï','ł','á'))
		bh.consume(collection.add('Ė'))
		collection = collection.union(mutable.HashSet[Character]('õ','û','œ','Ķ','Ñ','Ā','Ŀ','Ą','ÿ'))
		collection = collection.union(mutable.HashSet[Character]('Ž','Ŵ','Ŷ','ĵ','Į','Ò'))
		bh.consume(collection.add('á'))
		bh.consume(collection.add('Ĝ'))
		bh.consume(collection.add('ň'))
		collection = collection.union(mutable.HashSet[Character]('Ƈ','ı','Ó','ŧ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ĳ','Ġ','Ŋ','Ë','ğ','Ǝ','ø','Þ')))
		bh.consume(collection.add('ú'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ă','ā','ŷ','ç','ő')))
		bh.consume(collection.add('ğ'))
		collection = collection.union(mutable.HashSet[Character]('Ŗ','Ŝ','ş','ƌ','ā','ý','ĭ'))
		bh.consume(collection.remove('ç'))
		collection = collection.union(mutable.HashSet[Character]('Ŕ','Ő','ŧ','Ų','ġ'))
		collection = collection.diff(mutable.HashSet[Character]('ĳ','Ţ','Ů'))
		bh.consume(collection.remove('ſ'))
		collection = collection.union(mutable.HashSet[Character]('ĭ','đ','ð','Ɓ','ƀ','Ɔ'))
		bh.consume(collection.remove('ĺ'))
		collection = collection.diff(mutable.HashSet[Character]('ĺ','è','ï'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Ŏ','ê','Š','ä','ì'))
		bh.consume(collection.add('Ŋ'))
		bh.consume(collection.add('Î'))
		collection = collection.union(mutable.HashSet[Character]('×','Ĩ','ŏ','Ŭ','â'))
		collection = collection.union(mutable.HashSet[Character]('Č','Ċ','þ','Ę','Š','Ŝ'))
		bh.consume(collection.add('ġ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ů'))
		bh.consume(collection.add('ō'))
		collection = collection.union(mutable.HashSet[Character]('Ű','ç','ľ','ß'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ů','Ɗ','â','ħ','Ų','Ī')))
		collection = collection.union(mutable.HashSet[Character]('Ə','Ù','Ĉ','Ń','ĉ','ī','Ō'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ć','ņ','ų','Ì','Ï','î','ƀ')))
		collection = collection.diff(mutable.HashSet[Character]('á','Š','ł','Ú','Ò','ą','ġ','Ũ'))
		bh.consume(collection.add('ŧ'))
		collection = collection.diff(mutable.HashSet[Character]('Ō','Ŏ','ċ','ð','Ǝ'))
		bh.consume(collection.contains('ē'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ö','Ĝ','Ć','Ñ','ě','Đ','ç','È','ê'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ì'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ɔ','Ô','ġ','Ų','Ţ','İ','Ƅ'))
		collection = collection.union(mutable.HashSet[Character]('Ū','ñ','ê','ě','í','ņ'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Ƃ','ę','Ŭ','Ę','ł','œ','Į','ã','Ú'))
		bh.consume(collection.add('į'))
		collection = collection.diff(mutable.HashSet[Character]('ĉ','Ļ','ó','Ĝ','Ÿ','ß'))
		collection = collection.union(mutable.HashSet[Character]('è','ā','ģ','Ō','Ą','Ú','ť'))
		collection = collection.union(mutable.HashSet[Character]('ƌ','×','ū'))
		collection = collection.diff(mutable.HashSet[Character]('ƌ','ę','å','Þ','ĸ','é','ť','ā','Ũ'))
		bh.consume(collection.add('â'))
		collection = collection.diff(mutable.HashSet[Character]('ś','Ŗ','ń','Ÿ','÷','Ó','ş','ø'))
		collection = collection.diff(mutable.HashSet[Character]('Ì','Ź','ƃ','Ő'))
		collection = collection.diff(mutable.HashSet[Character]('ť','Í','Ô','Ə','Ï','Ě','į'))
		bh.consume(collection.add('ŏ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ĳ','Ţ','ŗ','ã')))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('š','ô','ŀ','č','Ö','ę'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ƅ','Š','ſ','Ƃ','ç')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ø','Ŵ','Ŀ','ù','Ŗ')))
		bh.consume(collection.remove('ŗ'))
		collection = collection.union(mutable.HashSet[Character]('Ź','Ĉ','Ò','Ú','ŏ','Œ','Ŷ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('š','ģ','Ő','ð','Ś','Ɖ','Ñ','ħ','ú')))
		bh.consume(collection.add('č'))
		collection = collection.union(mutable.HashSet[Character]('Ğ','ŀ','þ','š','Ĝ','Ę','Ų'))
		collection = collection.diff(mutable.HashSet[Character]('Ħ','Ħ','à','ƈ','Ż','Ŏ','ŋ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ĳ','ê','Ż','Ĳ','Ė','ê','Ê')))
		bh.consume(collection.add('Ĩ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŉ','ę','ĉ','ĥ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('þ','â','Ţ')))
		bh.consume(collection.remove('Ü'))
		bh.consume(collection.add('ú'))
		collection = collection.union(mutable.HashSet[Character]('Ő','Ĵ','ė','ù','Ű','Ħ','ƀ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Õ','Ŗ','į')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ā','Ĥ','ć','ť','ı','Ű')))
		collection = collection.union(mutable.HashSet[Character]('Û','ĕ','Ų','í'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('×','ã','ŵ','ń','Ű','ł','Ê')))
		collection = collection.diff(mutable.HashSet[Character]('ţ','Ĕ','ì','į','Ú','Ĺ','Ŗ','ï'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		bh.consume(collection.add('İ'))
		bh.consume(collection.add('Ĵ'))
		bh.consume(collection.add('ş'))
		collection = collection.union(mutable.HashSet[Character]('Ý','Ë','Ǝ','ğ','Ř','ò','û'))
		bh.consume(collection.remove('Ŀ'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ą','Û','ž','ƌ','á','à','Đ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ą','ŭ','Ə','ĉ','ž')))
		bh.consume(collection.add('Ĩ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ƀ'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('þ','ĭ','ę','ġ','ĕ','Ų','ž'))
		bh.consume(collection.remove('ĥ'))
		collection = collection.union(mutable.HashSet[Character]('ŉ','Ƃ','Ļ','Ñ','Î','ń','Ł','ð','Ĭ'))
		bh.consume(collection.add('ĩ'))
		collection = collection.diff(mutable.HashSet[Character]('Ő','ŕ','ą'))
		collection = collection.union(mutable.HashSet[Character]('Î','ŭ','ƃ','Š','ô','È','ƌ','Ê','ÿ'))
		collection = collection.diff(mutable.HashSet[Character]('į','ś','š','Ő','Ù','į','ī','õ','ģ'))
		collection = collection.union(mutable.HashSet[Character]('Ɓ','ç','ŵ','Ƈ','İ','ă','Ĵ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ƈ','Ę','Ĭ','ŏ','Đ','ŗ','Ū')))
		collection = collection.diff(mutable.HashSet[Character]('Ŕ','Ó','Ń','ĸ','Ü'))
		collection = collection.diff(mutable.HashSet[Character]('Õ','Ğ','Ħ','ģ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ą','ŉ','Ş','Œ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ę','Ž','Ü','Þ','İ','Ê','Ö','ÿ')))
		bh.consume(collection.add('Ĵ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ø','ĥ','ŕ','Ĵ','ţ','Ÿ','Ġ','ś','ë')))
		bh.consume(collection.add('ż'))
		collection = collection.union(mutable.HashSet[Character]('Ă','Ŏ','ĝ','Ď','á','ô'))
		bh.consume(collection.add('ĵ'))
		collection = collection.diff(mutable.HashSet[Character]('ı','ž','ŉ','ł','ĵ'))
		bh.consume(collection.add('Ľ'))
		bh.consume(collection.add('ŏ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ô','Ō','Ó','İ')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('į','Ť','Ô')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ĥ','ę','Í','Ň','Ğ','ĺ','ù','ę','Ā')))
		bh.consume(collection.add('ų'))
		bh.consume(collection.add('Ú'))
		bh.consume(collection.add('ŕ'))
		bh.consume(collection.add('Ŋ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.remove('Ź'))
		bh.consume(collection.add('ģ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ē','ō','ë','í')))
		collection = collection.union(mutable.HashSet[Character]('ò','ū','ı','ė','Ŋ','Ž','ŝ'))
		bh.consume(collection.add('Ũ'))
		bh.consume(collection.add('×'))
		collection = collection.diff(mutable.HashSet[Character]('Ƈ','ė','ō','ī','Ī','Ů'))
		bh.consume(collection.remove('Ù'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('Ť','ƌ','ě','ě','Ů'))
		bh.consume(collection.add('ć'))
		bh.consume(collection.add('ú'))
		bh.consume(collection.add('ŝ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ħ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŏ','Ğ','ĩ','ĥ','Ļ','ł','Ŀ','Ķ','ý')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŀ','à','ĩ','Ì','ć')))
		collection = collection.diff(mutable.HashSet[Character]('ò','ƃ','Ù','Ɓ'))
		collection = collection.union(mutable.HashSet[Character]('ƌ','ƌ','ŀ','Ĉ','ů','Ć','ę','Ŗ'))
		collection = collection.diff(mutable.HashSet[Character]('ŀ','ö','Ñ','Ģ','Ă','Œ','ź','Ñ'))
		collection = collection.union(mutable.HashSet[Character]('Ê','ö','õ','Ľ'))
		collection = collection.union(mutable.HashSet[Character]('Õ','Ė','ļ','Ğ'))
		collection = collection.diff(mutable.HashSet[Character]('Ù','É','ž','Ę','Ƈ','ŕ','è','Ƈ','į'))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ĸ','ů','Ĉ','ā','į','Ŵ','ä','đ','Ö')))
		bh.consume(collection.add('Ĵ'))
		bh.consume(collection.remove('Ŗ'))
		bh.consume(collection.remove('Ƌ'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ę','Ŭ','ĕ','Ĵ','ũ'))
		collection = collection.diff(mutable.HashSet[Character]('š','õ','ŧ','Ę','ł','ı','Ɗ','ƅ','ť'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ň'))
		collection = collection.diff(mutable.HashSet[Character]('Ĕ','æ','æ','Ě','ƍ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ë','Š','Ų','ĉ','Ú','ė','Ś','ã')))
		collection = collection.union(mutable.HashSet[Character]('Ý','ï','ď','Ŏ','Ų','ê','ā','ƈ'))
		bh.consume(collection.add('Ĕ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ł','Ĩ','Ƌ')))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ì','Ĺ','ŕ','ĵ','Ŏ','Ï')))
		collection = collection.union(mutable.HashSet[Character]('Ŀ','Ŏ','Ɖ','ų','Į'))
		collection = collection.diff(mutable.HashSet[Character]('þ','ƍ','Ɖ','Ü','Ë','ō'))
		bh.consume(collection.remove('ŏ'))
		collection = collection.diff(mutable.HashSet[Character]('ē','Ŵ','Ĉ','Ķ','â','Ŧ'))
		bh.consume(collection.remove('ĥ'))
		collection = collection.union(mutable.HashSet[Character]('ö','į','Ô','ƀ','ë'))
		bh.consume(collection.remove('ż'))
		bh.consume(collection.add('ţ'))
		collection = collection.union(mutable.HashSet[Character]('Ć','Ĕ','ĩ','Ă','Ģ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ǝ','ī','ē')))
		collection = collection.union(mutable.HashSet[Character]('ď','Þ','ļ'))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ť','Ŭ','Ü','Ĵ')))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('Ɗ'))
		bh.consume(collection.add('ŕ'))
		bh.consume(collection.remove('Ŋ'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Đ','ĳ','Ĳ','ĺ','ţ','ò'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('Ā','ŉ','Ŗ','ķ','Ķ','Ŧ','Ō','Í','Ŧ'))
		bh.consume(collection.add('Þ'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ė','ï','ü','Ě','ī','ƅ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ņ','ä','Ŏ','Ŵ','ŏ','Ň','Ť','Ž')))
		collection = collection.union(mutable.HashSet[Character]('ċ','œ','ĥ','ś','ą','ð','õ','ĩ','ƅ'))
		collection.toArray(classTag[Character])
		collection = collection.diff(mutable.HashSet[Character]('ľ','ŋ','ƌ','Ŷ'))
		bh.consume(collection.add('Ž'))
		collection = collection.union(mutable.HashSet[Character]('ă','ŝ','ƍ','Í','ğ','ğ','è'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('û','ž','ď','ř','ř'))
		collection = collection.union(mutable.HashSet[Character]('İ','ę','ſ','Ð'))
		collection = collection.diff(mutable.HashSet[Character]('ø','Ĥ','ī','ů'))
		bh.consume(collection.remove('Ð'))
		collection = collection.diff(mutable.HashSet[Character]('ã','Ÿ','Ù','é','Ő','œ','Ŵ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ø','ţ','œ','ĥ','Ñ','İ','Ô','Ċ','Ƃ')))
		bh.consume(collection.add('Š'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ò','Ŕ','Ø','ù','ħ','ê','õ','Ĵ','Ê')))
		bh.consume(collection.add('Ű'))
		collection = collection.union(mutable.HashSet[Character]('Ď','ė','Ē'))
		collection = collection.union(mutable.HashSet[Character]('Ø','ť','Ħ','Î','œ','ƃ','Ŵ'))
		collection = collection.union(mutable.HashSet[Character]('ŕ','œ','Ŀ','Û','ř','ö','ƈ','Œ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ũ','đ','Ġ','Ķ','ţ','Ġ','Ŏ','ŕ','Ć')))
		collection = collection.union(mutable.HashSet[Character]('Ž','ą','ė','Ŧ','Ī','ŝ','è','ī'))
		bh.consume(collection.add('Œ'))
		bh.consume(collection.add('Ƃ'))
		collection = collection.diff(mutable.HashSet[Character]('õ','Ħ','Ę','Í'))
		collection = collection.union(mutable.HashSet[Character]('ŕ','Ĵ','Ķ'))
		bh.consume(collection.add('ô'))
		bh.consume(collection.add('ŷ'))
		bh.consume(collection.add('œ'))
		collection = collection.diff(mutable.HashSet[Character]('Ş','÷','Ĺ','ů','ō','Ƅ','Ť'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ũ','Ü','Ę','ŷ')))
		bh.consume(collection.add('Ā'))
		collection = collection.diff(mutable.HashSet[Character]('Ź','Ŀ','ŀ','Ð'))
		collection = collection.diff(mutable.HashSet[Character]('Ï','Ĩ','Ľ','ĝ','Ķ','Ƈ','Ë'))
		collection = collection.union(mutable.HashSet[Character]('Ŏ','Ë','ĺ','ć','ă','ě','ĩ','ƀ','â'))
		bh.consume(collection.add('ė'))
		collection = collection.diff(mutable.HashSet[Character]('Ǝ','Ď','ƀ','Ğ','ł','ĳ','Ś','į','ß'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ɖ','Ģ','ú','Ő','ı','ž')))
		bh.consume(collection.add('Ŭ'))
		collection = collection.union(mutable.HashSet[Character]('Ù','Ē','ŏ','ÿ','ñ','ĳ','Ļ','Ń'))
		collection = collection.union(mutable.HashSet[Character]('ę','Ř','Ħ','ň','Ť','Ė','ƈ','ŷ','Ĉ'))
		bh.consume(collection.add('ŉ'))
		collection = collection.diff(mutable.HashSet[Character]('Õ','Ķ','Ş','Ē','Ģ','ĕ'))
		collection = collection.union(mutable.HashSet[Character]('Ŋ','Ì','Ń'))
		bh.consume(collection.add('Ż'))
		collection = collection.diff(mutable.HashSet[Character]('ƈ','â','Ô','Ĥ','Ř','ŉ','ż','Ū'))
		collection = collection.union(mutable.HashSet[Character]('Ù','æ','ã','Ŷ','Ī','Ś'))
		collection = collection.union(mutable.HashSet[Character]('ď','Ð','Ŀ','Ă','Ɖ','Ć','ſ'))
		bh.consume(collection.add('ů'))
		collection = collection.union(mutable.HashSet[Character]('ų','É','å','Ƌ','Þ','Į','Ĳ'))
		bh.consume(collection.add('õ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ō','Û','Ə')))
		bh.consume(collection.add('Ƈ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ž','ť','Ÿ')))
		collection = collection.union(mutable.HashSet[Character]('ñ','ĝ','÷'))
		bh.consume(collection.add('ß'))
		bh.consume(collection.add('Ţ'))
		collection = collection.union(mutable.HashSet[Character]('ŕ','Í','û','Ų','Ú','Ľ'))
		bh.consume(collection.remove('ŉ'))
		collection = collection.union(mutable.HashSet[Character]('Ī','ù','Ņ','Ŗ','ľ','Ĥ','ŕ','Ā'))
		collection = collection.union(mutable.HashSet[Character]('á','Ŗ','š','į','Ò','ï','š'))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('ĺ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ċ','đ','Ƅ','ĩ')))
		collection = collection.union(mutable.HashSet[Character]('ŭ','š','Ď','Ć','ì','Ī','ƌ'))
		bh.consume(collection.add('Ą'))
		bh.consume(collection.add('ì'))
		collection = collection.union(mutable.HashSet[Character]('ÿ','Ģ','Ē','Ū','Ĉ','Į','ƅ'))
		collection = collection.union(mutable.HashSet[Character]('ŧ','ŧ','ŕ','Ė'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ŕ','É','ď','ú','Ɗ','Ĉ','ì','ń','ù')))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Õ','Ĕ','Ê')))
		bh.consume(collection.add('è'))
		collection = collection.union(mutable.HashSet[Character]('ŝ','Í','ă','ő','ù','Š','ĉ','ŉ','ł'))
		bh.consume(collection.add('Ţ'))
		collection.toArray(classTag[Character])
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ź','ŷ','Ī','ÿ','ŕ','Ě','î','ĸ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ţ','Ŗ','Ù','Ď','Ŭ','ı','Ø','Ò','Ĝ')))
		collection = collection.union(mutable.HashSet[Character]('ā','Ĭ','Ō','ě','ō','ƃ','Ĕ','ē','ć'))
		bh.consume(collection.add('Ĩ'))
		collection = collection.diff(mutable.HashSet[Character]('ĳ','Õ','Ŀ','ø','Ø','ĭ','Ć'))
		collection.toArray(classTag[Character])
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ĕ','ÿ','ğ','ő','å','ó')))
		collection = collection.diff(mutable.HashSet[Character]('ė','ź','Ă','Ĺ','ţ','ƍ','Ó'))
		bh.consume(collection.add('Ë'))
		collection = collection.diff(mutable.HashSet[Character]('ħ','Ű','ç','ĝ'))
		collection = collection.union(mutable.HashSet[Character]('ĉ','á','Ŭ'))
		bh.consume(collection.remove('Ŏ'))
		bh.consume(collection.add('ŷ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ø','Ĩ','ō','ę','Ÿ','é','Ŝ')))
		bh.consume(collection.add('ā'))
		collection.toArray(classTag[Character])
		collection = collection.union(mutable.HashSet[Character]('ú','Ų','Ê','ż','ƀ','Đ','á'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ś','İ','à','ļ','ũ','ë')))
		collection = collection.union(mutable.HashSet[Character]('É','ę','ů','Ę','Ű','æ'))
		collection = collection.union(mutable.HashSet[Character]('ũ','ê','ô','ö','Í','Ģ','Ľ'))
		bh.consume(collection.add('Ž'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ı','Ò','Ţ')))
		collection = collection.union(mutable.HashSet[Character]('Ś','Ħ','Ň','Ľ','Ĳ','ņ','ĉ'))
		collection = collection.diff(mutable.HashSet[Character]('ķ','Ň','Ł','Ċ','Ì','÷','Ļ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ő','û','Ł','ŀ','â')))
		bh.consume(collection.add('Ə'))
		collection = collection.union(mutable.HashSet[Character]('Ø','ú','Ĳ','ĕ','ž','ĥ','Į'))
		bh.consume(collection.add('ĳ'))
		collection = collection.union(mutable.HashSet[Character]('Ŧ','ı','ă','õ','ň','Ċ','Ū'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ê','Ā','Ă','ƈ','é','ţ','Ċ','Ù')))
		bh.consume(collection.add('ī'))
		collection = collection.diff(mutable.HashSet[Character]('Ĝ','ő','Ū','ĵ','ţ'))
		bh.consume(collection.add('Ă'))
		bh.consume(collection.add('ŵ'))
		collection = collection.union(mutable.HashSet[Character]('ç','Ŭ','õ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ü','č','é','ģ','þ','ć','ĵ','ÿ','ŗ')))
		collection.toArray(classTag[Character])
		bh.consume(collection.add('þ'))
		collection = collection.diff(mutable.HashSet[Character]('Ù','ē','Í','Ś','Ŏ','ż'))
		bh.consume(collection.add('đ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ą','Ĩ','Ů')))
		collection = collection.union(mutable.HashSet[Character]('ƃ','ć','×'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('Ĉ','í','à','ç','ñ','ŏ','ě')))
		bh.consume(collection.add('ŕ'))
		bh.consume(collection.addAll(mutable.ArrayBuffer[Character]('ƃ','ŷ','Ø','õ','ĥ','ť','Ë')))
	}
}
