package com.adalbert;
import java.util
import scala.collection.immutable
import scala.collection.mutable
import scala.reflect.classTag
import org.openjdk.jmh.annotations._
import org.openjdk.jmh.infra._

@State(Scope.Benchmark)
class S_Profile1AllSets_STreeSet_20220429190545561 {
	var collection = mutable.TreeSet[String]()
	@Setup(Level.Invocation)
	def setupSTreeSet(): Unit = {
		collection = mutable.TreeSet[String]()
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ŘŘŘŘŘŘŘŘŘŘ")
		collection.add("ůůůůůůůůůů")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("çççççççççç")
		collection.add("ęęęęęęęęęę")
		collection.add("ěěěěěěěěěě")
		collection.add("ģģģģģģģģģģ")
		collection.add("øøøøøøøøøø")
		collection.add("ĳĳĳĳĳĳĳĳĳĳ")
		collection.add("ůůůůůůůůůů")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ââââââââââ")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ěěěěěěěěěě")
		collection.add("ŔŔŔŔŔŔŔŔŔŔ")
		collection.add("ĝĝĝĝĝĝĝĝĝĝ")
		collection.add("áááááááááá")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("įįįįįįįįįį")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("ƍƍƍƍƍƍƍƍƍƍ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ČČČČČČČČČČ")
		collection.add("ÍÍÍÍÍÍÍÍÍÍ")
		collection.add("ŜŜŜŜŜŜŜŜŜŜ")
		collection.add("ťťťťťťťťťť")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ĜĜĜĜĜĜĜĜĜĜ")
		collection.add("àààààààààà")
		collection.add("çççççççççç")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("ćććććććććć")
		collection.add("ññññññññññ")
		collection.add("ÓÓÓÓÓÓÓÓÓÓ")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ľľľľľľľľľľ")
		collection.add("łłłłłłłłłł")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("ţţţţţţţţţţ")
		collection.add("ŃŃŃŃŃŃŃŃŃŃ")
		collection.add("ìììììììììì")
		collection.add("ŰŰŰŰŰŰŰŰŰŰ")
		collection.add("ÿÿÿÿÿÿÿÿÿÿ")
		collection.add("źźźźźźźźźź")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ēēēēēēēēēē")
		collection.add("ľľľľľľľľľľ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ÍÍÍÍÍÍÍÍÍÍ")
		collection.add("đđđđđđđđđđ")
		collection.add("ÙÙÙÙÙÙÙÙÙÙ")
		collection.add("ÚÚÚÚÚÚÚÚÚÚ")
		collection.add("ĎĎĎĎĎĎĎĎĎĎ")
		collection.add("ĶĶĶĶĶĶĶĶĶĶ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ŤŤŤŤŤŤŤŤŤŤ")
		collection.add("ūūūūūūūūūū")
		collection.add("ŕŕŕŕŕŕŕŕŕŕ")
		collection.add("çççççççççç")
		collection.add("āāāāāāāāāā")
		collection.add("ġġġġġġġġġġ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ėėėėėėėėėė")
		collection.add("ųųųųųųųųųų")
		collection.add("üüüüüüüüüü")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ÝÝÝÝÝÝÝÝÝÝ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ńńńńńńńńńń")
		collection.add("ÍÍÍÍÍÍÍÍÍÍ")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ŧŧŧŧŧŧŧŧŧŧ")
		collection.add("ŦŦŦŦŦŦŦŦŦŦ")
		collection.add("ģģģģģģģģģģ")
		collection.add("áááááááááá")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("ùùùùùùùùùù")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ääääääääää")
		collection.add("ŎŎŎŎŎŎŎŎŎŎ")
		collection.add("ûûûûûûûûûû")
		collection.add("żżżżżżżżżż")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ìììììììììì")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("àààààààààà")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ųųųųųųųųųų")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("ěěěěěěěěěě")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("řřřřřřřřřř")
		collection.add("ƁƁƁƁƁƁƁƁƁƁ")
		collection.add("ŽŽŽŽŽŽŽŽŽŽ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("żżżżżżżżżż")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ųųųųųųųųųų")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ŠŠŠŠŠŠŠŠŠŠ")
		collection.add("ƈƈƈƈƈƈƈƈƈƈ")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ææææææææææ")
		collection.add("ŗŗŗŗŗŗŗŗŗŗ")
		collection.add("ŅŅŅŅŅŅŅŅŅŅ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("ĠĠĠĠĠĠĠĠĠĠ")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("įįįįįįįįįį")
		collection.add("áááááááááá")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ƎƎƎƎƎƎƎƎƎƎ")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ÝÝÝÝÝÝÝÝÝÝ")
		collection.add("öööööööööö")
		collection.add("ċċċċċċċċċċ")
		collection.add("şşşşşşşşşş")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("áááááááááá")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ĶĶĶĶĶĶĶĶĶĶ")
		collection.add("ċċċċċċċċċċ")
		collection.add("áááááááááá")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("źźźźźźźźźź")
		collection.add("ââââââââââ")
		collection.add("ŰŰŰŰŰŰŰŰŰŰ")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("āāāāāāāāāā")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ÓÓÓÓÓÓÓÓÓÓ")
		collection.add("ƍƍƍƍƍƍƍƍƍƍ")
		collection.add("ţţţţţţţţţţ")
		collection.add("ëëëëëëëëëë")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ƊƊƊƊƊƊƊƊƊƊ")
		collection.add("ĵĵĵĵĵĵĵĵĵĵ")
		collection.add("ņņņņņņņņņņ")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("ŖŖŖŖŖŖŖŖŖŖ")
		collection.add("ƈƈƈƈƈƈƈƈƈƈ")
		collection.add("ßßßßßßßßßß")
		collection.add("ŪŪŪŪŪŪŪŪŪŪ")
		collection.add("ľľľľľľľľľľ")
		collection.add("ľľľľľľľľľľ")
		collection.add("ąąąąąąąąąą")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ûûûûûûûûûû")
		collection.add("čččččččččč")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ģģģģģģģģģģ")
		collection.add("ƀƀƀƀƀƀƀƀƀƀ")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ćććććććććć")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("ţţţţţţţţţţ")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("ĕĕĕĕĕĕĕĕĕĕ")
		collection.add("êêêêêêêêêê")
		collection.add("ĜĜĜĜĜĜĜĜĜĜ")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("ŘŘŘŘŘŘŘŘŘŘ")
		collection.add("åååååååååå")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("ďďďďďďďďďď")
		collection.add("ūūūūūūūūūū")
		collection.add("ôôôôôôôôôô")
		collection.add("××××××××××")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("ŞŞŞŞŞŞŞŞŞŞ")
		collection.add("îîîîîîîîîî")
		collection.add("ĠĠĠĠĠĠĠĠĠĠ")
		collection.add("ķķķķķķķķķķ")
		collection.add("àààààààààà")
		collection.add("ăăăăăăăăăă")
		collection.add("ķķķķķķķķķķ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("ƃƃƃƃƃƃƃƃƃƃ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("ŞŞŞŞŞŞŞŞŞŞ")
		collection.add("ìììììììììì")
		collection.add("ƏƏƏƏƏƏƏƏƏƏ")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ńńńńńńńńńń")
		collection.add("žžžžžžžžžž")
		collection.add("ÍÍÍÍÍÍÍÍÍÍ")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("áááááááááá")
		collection.add("žžžžžžžžžž")
		collection.add("ħħħħħħħħħħ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("œœœœœœœœœœ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ïïïïïïïïïï")
		collection.add("ŧŧŧŧŧŧŧŧŧŧ")
		collection.add("ŽŽŽŽŽŽŽŽŽŽ")
		collection.add("àààààààààà")
		collection.add("øøøøøøøøøø")
		collection.add("ĳĳĳĳĳĳĳĳĳĳ")
		collection.add("ŞŞŞŞŞŞŞŞŞŞ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("řřřřřřřřřř")
		collection.add("ÉÉÉÉÉÉÉÉÉÉ")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ŭŭŭŭŭŭŭŭŭŭ")
		collection.add("ųųųųųųųųųų")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ķķķķķķķķķķ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ƈƈƈƈƈƈƈƈƈƈ")
		collection.add("ėėėėėėėėėė")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("ųųųųųųųųųų")
		collection.add("ľľľľľľľľľľ")
		collection.add("ŎŎŎŎŎŎŎŎŎŎ")
		collection.add("êêêêêêêêêê")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("èèèèèèèèèè")
		collection.add("ūūūūūūūūūū")
		collection.add("ĹĹĹĹĹĹĹĹĹĹ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("đđđđđđđđđđ")
		collection.add("ŅŅŅŅŅŅŅŅŅŅ")
		collection.add("ţţţţţţţţţţ")
		collection.add("ÿÿÿÿÿÿÿÿÿÿ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ūūūūūūūūūū")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("řřřřřřřřřř")
		collection.add("źźźźźźźźźź")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("őőőőőőőőőő")
		collection.add("ƃƃƃƃƃƃƃƃƃƃ")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("ßßßßßßßßßß")
		collection.add("èèèèèèèèèè")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("ââââââââââ")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ƁƁƁƁƁƁƁƁƁƁ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ġġġġġġġġġġ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ûûûûûûûûûû")
		collection.add("ūūūūūūūūūū")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ĈĈĈĈĈĈĈĈĈĈ")
		collection.add("çççççççççç")
		collection.add("ƁƁƁƁƁƁƁƁƁƁ")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ĈĈĈĈĈĈĈĈĈĈ")
		collection.add("žžžžžžžžžž")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ìììììììììì")
		collection.add("āāāāāāāāāā")
		collection.add("ŧŧŧŧŧŧŧŧŧŧ")
		collection.add("ġġġġġġġġġġ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("åååååååååå")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("úúúúúúúúúú")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("ƀƀƀƀƀƀƀƀƀƀ")
		collection.add("đđđđđđđđđđ")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("žžžžžžžžžž")
		collection.add("śśśśśśśśśś")
		collection.add("ūūūūūūūūūū")
		collection.add("ÚÚÚÚÚÚÚÚÚÚ")
		collection.add("ńńńńńńńńńń")
		collection.add("šššššššššš")
		collection.add("ŔŔŔŔŔŔŔŔŔŔ")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("þþþþþþþþþþ")
		collection.add("ƏƏƏƏƏƏƏƏƏƏ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("ŸŸŸŸŸŸŸŸŸŸ")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("ĜĜĜĜĜĜĜĜĜĜ")
		collection.add("ğğğğğğğğğğ")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ďďďďďďďďďď")
		collection.add("ſſſſſſſſſſ")
		collection.add("đđđđđđđđđđ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("İİİİİİİİİİ")
		collection.add("óóóóóóóóóó")
		collection.add("üüüüüüüüüü")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("ĳĳĳĳĳĳĳĳĳĳ")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("ìììììììììì")
		collection.add("šššššššššš")
		collection.add("ſſſſſſſſſſ")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ÉÉÉÉÉÉÉÉÉÉ")
		collection.add("ÕÕÕÕÕÕÕÕÕÕ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("ſſſſſſſſſſ")
		collection.add("ŰŰŰŰŰŰŰŰŰŰ")
		collection.add("ąąąąąąąąąą")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("ġġġġġġġġġġ")
		collection.add("ýýýýýýýýýý")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("îîîîîîîîîî")
		collection.add("üüüüüüüüüü")
		collection.add("ƊƊƊƊƊƊƊƊƊƊ")
		collection.add("ĹĹĹĹĹĹĹĹĹĹ")
		collection.add("šššššššššš")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("īīīīīīīīīī")
		collection.add("ÝÝÝÝÝÝÝÝÝÝ")
		collection.add("íííííííííí")
		collection.add("āāāāāāāāāā")
		collection.add("ďďďďďďďďďď")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("šššššššššš")
		collection.add("ļļļļļļļļļļ")
		collection.add("êêêêêêêêêê")
		collection.add("ŪŪŪŪŪŪŪŪŪŪ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ēēēēēēēēēē")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ĠĠĠĠĠĠĠĠĠĠ")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("ħħħħħħħħħħ")
		collection.add("ìììììììììì")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("ńńńńńńńńńń")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("ŰŰŰŰŰŰŰŰŰŰ")
		collection.add("ÚÚÚÚÚÚÚÚÚÚ")
		collection.add("ĪĪĪĪĪĪĪĪĪĪ")
		collection.add("ïïïïïïïïïï")
		collection.add("ƂƂƂƂƂƂƂƂƂƂ")
		collection.add("åååååååååå")
		collection.add("ňňňňňňňňňň")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("öööööööööö")
		collection.add("ËËËËËËËËËË")
		collection.add("ūūūūūūūūūū")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("éééééééééé")
		collection.add("ěěěěěěěěěě")
		collection.add("ýýýýýýýýýý")
		collection.add("ÙÙÙÙÙÙÙÙÙÙ")
		collection.add("źźźźźźźźźź")
		collection.add("ēēēēēēēēēē")
		collection.add("ƈƈƈƈƈƈƈƈƈƈ")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("ķķķķķķķķķķ")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("úúúúúúúúúú")
		collection.add("áááááááááá")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("ŞŞŞŞŞŞŞŞŞŞ")
		collection.add("œœœœœœœœœœ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("šššššššššš")
		collection.add("ņņņņņņņņņņ")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("îîîîîîîîîî")
		collection.add("ƅƅƅƅƅƅƅƅƅƅ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("űűűűűűűűűű")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("ůůůůůůůůůů")
		collection.add("ġġġġġġġġġġ")
		collection.add("ğğğğğğğğğğ")
		collection.add("īīīīīīīīīī")
		collection.add("ļļļļļļļļļļ")
		collection.add("ïïïïïïïïïï")
		collection.add("ĹĹĹĹĹĹĹĹĹĹ")
		collection.add("ăăăăăăăăăă")
		collection.add("ūūūūūūūūūū")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ƏƏƏƏƏƏƏƏƏƏ")
		collection.add("ýýýýýýýýýý")
		collection.add("ĝĝĝĝĝĝĝĝĝĝ")
		collection.add("őőőőőőőőőő")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ůůůůůůůůůů")
		collection.add("ËËËËËËËËËË")
		collection.add("ðððððððððð")
		collection.add("īīīīīīīīīī")
		collection.add("ßßßßßßßßßß")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("ĐĐĐĐĐĐĐĐĐĐ")
		collection.add("ôôôôôôôôôô")
		collection.add("ĞĞĞĞĞĞĞĞĞĞ")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("şşşşşşşşşş")
		collection.add("őőőőőőőőőő")
		collection.add("ŠŠŠŠŠŠŠŠŠŠ")
		collection.add("ÝÝÝÝÝÝÝÝÝÝ")
		collection.add("ÓÓÓÓÓÓÓÓÓÓ")
		collection.add("ÈÈÈÈÈÈÈÈÈÈ")
		collection.add("ðððððððððð")
		collection.add("ęęęęęęęęęę")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ŕŕŕŕŕŕŕŕŕŕ")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("ĜĜĜĜĜĜĜĜĜĜ")
		collection.add("ęęęęęęęęęę")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("ůůůůůůůůůů")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ËËËËËËËËËË")
		collection.add("ţţţţţţţţţţ")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("êêêêêêêêêê")
		collection.add("àààààààààà")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("ōōōōōōōōōō")
		collection.add("ĭĭĭĭĭĭĭĭĭĭ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("××××××××××")
		collection.add("ąąąąąąąąąą")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ſſſſſſſſſſ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ĒĒĒĒĒĒĒĒĒĒ")
		collection.add("àààààààààà")
		collection.add("ťťťťťťťťťť")
		collection.add("ŅŅŅŅŅŅŅŅŅŅ")
		collection.add("ĸĸĸĸĸĸĸĸĸĸ")
		collection.add("ēēēēēēēēēē")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ıııııııııı")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("õõõõõõõõõõ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("éééééééééé")
		collection.add("šššššššššš")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ƁƁƁƁƁƁƁƁƁƁ")
		collection.add("ıııııııııı")
		collection.add("ķķķķķķķķķķ")
		collection.add("ĳĳĳĳĳĳĳĳĳĳ")
		collection.add("ƀƀƀƀƀƀƀƀƀƀ")
		collection.add("ěěěěěěěěěě")
		collection.add("ċċċċċċċċċċ")
		collection.add("ĝĝĝĝĝĝĝĝĝĝ")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ŗŗŗŗŗŗŗŗŗŗ")
		collection.add("ŌŌŌŌŌŌŌŌŌŌ")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("àààààààààà")
		collection.add("çççççççççç")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("ŗŗŗŗŗŗŗŗŗŗ")
		collection.add("ĭĭĭĭĭĭĭĭĭĭ")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ļļļļļļļļļļ")
		collection.add("ýýýýýýýýýý")
		collection.add("ĸĸĸĸĸĸĸĸĸĸ")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("ŦŦŦŦŦŦŦŦŦŦ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("żżżżżżżżżż")
		collection.add("éééééééééé")
		collection.add("úúúúúúúúúú")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("īīīīīīīīīī")
		collection.add("ęęęęęęęęęę")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("řřřřřřřřřř")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("čččččččččč")
		collection.add("ŽŽŽŽŽŽŽŽŽŽ")
		collection.add("ŖŖŖŖŖŖŖŖŖŖ")
		collection.add("ļļļļļļļļļļ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ýýýýýýýýýý")
		collection.add("žžžžžžžžžž")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ŒŒŒŒŒŒŒŒŒŒ")
		collection.add("ŌŌŌŌŌŌŌŌŌŌ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("ųųųųųųųųųų")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ÕÕÕÕÕÕÕÕÕÕ")
		collection.add("îîîîîîîîîî")
		collection.add("ġġġġġġġġġġ")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("àààààààààà")
		collection.add("ŠŠŠŠŠŠŠŠŠŠ")
		collection.add("îîîîîîîîîî")
		collection.add("îîîîîîîîîî")
		collection.add("őőőőőőőőőő")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ƍƍƍƍƍƍƍƍƍƍ")
		collection.add("ŃŃŃŃŃŃŃŃŃŃ")
		collection.add("ľľľľľľľľľľ")
		collection.add("ĶĶĶĶĶĶĶĶĶĶ")
		collection.add("ēēēēēēēēēē")
		collection.add("ĵĵĵĵĵĵĵĵĵĵ")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("áááááááááá")
		collection.add("šššššššššš")
		collection.add("ĵĵĵĵĵĵĵĵĵĵ")
		collection.add("ŅŅŅŅŅŅŅŅŅŅ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("łłłłłłłłłł")
		collection.add("şşşşşşşşşş")
		collection.add("ùùùùùùùùùù")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("ģģģģģģģģģģ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("śśśśśśśśśś")
		collection.add("øøøøøøøøøø")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("òòòòòòòòòò")
		collection.add("ŤŤŤŤŤŤŤŤŤŤ")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ùùùùùùùùùù")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ŧŧŧŧŧŧŧŧŧŧ")
		collection.add("ğğğğğğğğğğ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("íííííííííí")
		collection.add("ĒĒĒĒĒĒĒĒĒĒ")
		collection.add("žžžžžžžžžž")
		collection.add("ČČČČČČČČČČ")
		collection.add("ÚÚÚÚÚÚÚÚÚÚ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("ääääääääää")
		collection.add("ĸĸĸĸĸĸĸĸĸĸ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("őőőőőőőőőő")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ãããããããããã")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ÓÓÓÓÓÓÓÓÓÓ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ĐĐĐĐĐĐĐĐĐĐ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("ŪŪŪŪŪŪŪŪŪŪ")
		collection.add("××××××××××")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ňňňňňňňňňň")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("ääääääääää")
		collection.add("ıııııııııı")
		collection.add("ăăăăăăăăăă")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("ŘŘŘŘŘŘŘŘŘŘ")
		collection.add("ţţţţţţţţţţ")
		collection.add("şşşşşşşşşş")
		collection.add("ŭŭŭŭŭŭŭŭŭŭ")
		collection.add("åååååååååå")
		collection.add("ēēēēēēēēēē")
		collection.add("ċċċċċċċċċċ")
		collection.add("ûûûûûûûûûû")
		collection.add("ðððððððððð")
		collection.add("ÿÿÿÿÿÿÿÿÿÿ")
		collection.add("ŸŸŸŸŸŸŸŸŸŸ")
		collection.add("ČČČČČČČČČČ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ĕĕĕĕĕĕĕĕĕĕ")
		collection.add("ßßßßßßßßßß")
		collection.add("ķķķķķķķķķķ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("ģģģģģģģģģģ")
		collection.add("şşşşşşşşşş")
		collection.add("ŎŎŎŎŎŎŎŎŎŎ")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("ıııııııııı")
		collection.add("ďďďďďďďďďď")
		collection.add("ĈĈĈĈĈĈĈĈĈĈ")
		collection.add("łłłłłłłłłł")
		collection.add("čččččččččč")
		collection.add("űűűűűűűűűű")
		collection.add("īīīīīīīīīī")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ŽŽŽŽŽŽŽŽŽŽ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("çççççççççç")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("ŗŗŗŗŗŗŗŗŗŗ")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ĞĞĞĞĞĞĞĞĞĞ")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("ĸĸĸĸĸĸĸĸĸĸ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("ńńńńńńńńńń")
		collection.add("ÖÖÖÖÖÖÖÖÖÖ")
		collection.add("šššššššššš")
		collection.add("ũũũũũũũũũũ")
		collection.add("şşşşşşşşşş")
		collection.add("ËËËËËËËËËË")
		collection.add("ŎŎŎŎŎŎŎŎŎŎ")
		collection.add("ŔŔŔŔŔŔŔŔŔŔ")
		collection.add("éééééééééé")
		collection.add("ËËËËËËËËËË")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("××××××××××")
		collection.add("ãããããããããã")
		collection.add("ſſſſſſſſſſ")
		collection.add("ýýýýýýýýýý")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ÖÖÖÖÖÖÖÖÖÖ")
		collection.add("ìììììììììì")
		collection.add("ÙÙÙÙÙÙÙÙÙÙ")
		collection.add("ěěěěěěěěěě")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("ĶĶĶĶĶĶĶĶĶĶ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ŦŦŦŦŦŦŦŦŦŦ")
		collection.add("ņņņņņņņņņņ")
		collection.add("ĎĎĎĎĎĎĎĎĎĎ")
		collection.add("ūūūūūūūūūū")
		collection.add("ËËËËËËËËËË")
		collection.add("űűűűűűűűűű")
		collection.add("åååååååååå")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ųųųųųųųųųų")
		collection.add("òòòòòòòòòò")
		collection.add("ćććććććććć")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("õõõõõõõõõõ")
		collection.add("ġġġġġġġġġġ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ăăăăăăăăăă")
		collection.add("ìììììììììì")
		collection.add("ôôôôôôôôôô")
		collection.add("œœœœœœœœœœ")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("ÉÉÉÉÉÉÉÉÉÉ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("åååååååååå")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("öööööööööö")
		collection.add("ŌŌŌŌŌŌŌŌŌŌ")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("ĒĒĒĒĒĒĒĒĒĒ")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("ƄƄƄƄƄƄƄƄƄƄ")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("ŪŪŪŪŪŪŪŪŪŪ")
		collection.add("ëëëëëëëëëë")
		collection.add("śśśśśśśśśś")
		collection.add("××××××××××")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("êêêêêêêêêê")
		collection.add("ŕŕŕŕŕŕŕŕŕŕ")
		collection.add("ţţţţţţţţţţ")
		collection.add("ķķķķķķķķķķ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ņņņņņņņņņņ")
		collection.add("ńńńńńńńńńń")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ÕÕÕÕÕÕÕÕÕÕ")
		collection.add("ķķķķķķķķķķ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("öööööööööö")
		collection.add("ęęęęęęęęęę")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ăăăăăăăăăă")
		collection.add("ĭĭĭĭĭĭĭĭĭĭ")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("ûûûûûûûûûû")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŤŤŤŤŤŤŤŤŤŤ")
		collection.add("ąąąąąąąąąą")
		collection.add("êêêêêêêêêê")
		collection.add("ŒŒŒŒŒŒŒŒŒŒ")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("üüüüüüüüüü")
		collection.add("ŲŲŲŲŲŲŲŲŲŲ")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ČČČČČČČČČČ")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("żżżżżżżżżż")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ňňňňňňňňňň")
		collection.add("áááááááááá")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("şşşşşşşşşş")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("ħħħħħħħħħħ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ıııııııııı")
		collection.add("ţţţţţţţţţţ")
		collection.add("đđđđđđđđđđ")
		collection.add("àààààààààà")
		collection.add("żżżżżżżżżż")
		collection.add("ƀƀƀƀƀƀƀƀƀƀ")
		collection.add("īīīīīīīīīī")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ŴŴŴŴŴŴŴŴŴŴ")
		collection.add("őőőőőőőőőő")
		collection.add("ŃŃŃŃŃŃŃŃŃŃ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ƏƏƏƏƏƏƏƏƏƏ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ĶĶĶĶĶĶĶĶĶĶ")
		collection.add("ŃŃŃŃŃŃŃŃŃŃ")
		collection.add("××××××××××")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ââââââââââ")
		collection.add("īīīīīīīīīī")
		collection.add("óóóóóóóóóó")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("åååååååååå")
		collection.add("ĈĈĈĈĈĈĈĈĈĈ")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("ıııııııııı")
		collection.add("ľľľľľľľľľľ")
		collection.add("èèèèèèèèèè")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("őőőőőőőőőő")
		collection.add("ťťťťťťťťťť")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ũũũũũũũũũũ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("ÊÊÊÊÊÊÊÊÊÊ")
		collection.add("ññññññññññ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ĺĺĺĺĺĺĺĺĺĺ")
		collection.add("ƍƍƍƍƍƍƍƍƍƍ")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("žžžžžžžžžž")
		collection.add("ËËËËËËËËËË")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ææææææææææ")
		collection.add("õõõõõõõõõõ")
		collection.add("ŔŔŔŔŔŔŔŔŔŔ")
		collection.add("ĕĕĕĕĕĕĕĕĕĕ")
		collection.add("İİİİİİİİİİ")
		collection.add("ƃƃƃƃƃƃƃƃƃƃ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ŗŗŗŗŗŗŗŗŗŗ")
		collection.add("ņņņņņņņņņņ")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ðððððððððð")
		collection.add("ĎĎĎĎĎĎĎĎĎĎ")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ēēēēēēēēēē")
		collection.add("àààààààààà")
		collection.add("ŘŘŘŘŘŘŘŘŘŘ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("åååååååååå")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("ļļļļļļļļļļ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("řřřřřřřřřř")
		collection.add("œœœœœœœœœœ")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("øøøøøøøøøø")
		collection.add("ƎƎƎƎƎƎƎƎƎƎ")
		collection.add("żżżżżżżżżż")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ũũũũũũũũũũ")
		collection.add("ĤĤĤĤĤĤĤĤĤĤ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ńńńńńńńńńń")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("éééééééééé")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("ėėėėėėėėėė")
		collection.add("İİİİİİİİİİ")
		collection.add("ûûûûûûûûûû")
		collection.add("ÛÛÛÛÛÛÛÛÛÛ")
		collection.add("ûûûûûûûûûû")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("ââââââââââ")
		collection.add("ÈÈÈÈÈÈÈÈÈÈ")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("ÑÑÑÑÑÑÑÑÑÑ")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("ńńńńńńńńńń")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ÙÙÙÙÙÙÙÙÙÙ")
		collection.add("åååååååååå")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("īīīīīīīīīī")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("İİİİİİİİİİ")
		collection.add("ƂƂƂƂƂƂƂƂƂƂ")
		collection.add("ËËËËËËËËËË")
		collection.add("ĜĜĜĜĜĜĜĜĜĜ")
		collection.add("ųųųųųųųųųų")
		collection.add("īīīīīīīīīī")
		collection.add("ĆĆĆĆĆĆĆĆĆĆ")
		collection.add("õõõõõõõõõõ")
		collection.add("ÕÕÕÕÕÕÕÕÕÕ")
		collection.add("ýýýýýýýýýý")
		collection.add("ƁƁƁƁƁƁƁƁƁƁ")
		collection.add("œœœœœœœœœœ")
		collection.add("ğğğğğğğğğğ")
		collection.add("šššššššššš")
		collection.add("óóóóóóóóóó")
		collection.add("ńńńńńńńńńń")
		collection.add("ģģģģģģģģģģ")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("İİİİİİİİİİ")
		collection.add("ïïïïïïïïïï")
		collection.add("ŞŞŞŞŞŞŞŞŞŞ")
		collection.add("ññññññññññ")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ÔÔÔÔÔÔÔÔÔÔ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("íííííííííí")
		collection.add("çççççççççç")
		collection.add("ĮĮĮĮĮĮĮĮĮĮ")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("ääääääääää")
		collection.add("ċċċċċċċċċċ")
		collection.add("őőőőőőőőőő")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("þþþþþþþþþþ")
		collection.add("źźźźźźźźźź")
		collection.add("ƊƊƊƊƊƊƊƊƊƊ")
		collection.add("įįįįįįįįįį")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ƇƇƇƇƇƇƇƇƇƇ")
		collection.add("úúúúúúúúúú")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("÷÷÷÷÷÷÷÷÷÷")
		collection.add("āāāāāāāāāā")
		collection.add("òòòòòòòòòò")
		collection.add("ìììììììììì")
		collection.add("þþþþþþþþþþ")
		collection.add("ċċċċċċċċċċ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("ŦŦŦŦŦŦŦŦŦŦ")
		collection.add("ųųųųųųųųųų")
		collection.add("íííííííííí")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŤŤŤŤŤŤŤŤŤŤ")
		collection.add("şşşşşşşşşş")
		collection.add("ėėėėėėėėėė")
		collection.add("āāāāāāāāāā")
		collection.add("ůůůůůůůůůů")
		collection.add("ƅƅƅƅƅƅƅƅƅƅ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ÈÈÈÈÈÈÈÈÈÈ")
		collection.add("ĵĵĵĵĵĵĵĵĵĵ")
		collection.add("ðððððððððð")
		collection.add("ŘŘŘŘŘŘŘŘŘŘ")
		collection.add("ĄĄĄĄĄĄĄĄĄĄ")
		collection.add("ĞĞĞĞĞĞĞĞĞĞ")
		collection.add("ŨŨŨŨŨŨŨŨŨŨ")
		collection.add("õõõõõõõõõõ")
		collection.add("ƃƃƃƃƃƃƃƃƃƃ")
		collection.add("éééééééééé")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("êêêêêêêêêê")
		collection.add("ææææææææææ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ĞĞĞĞĞĞĞĞĞĞ")
		collection.add("ľľľľľľľľľľ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ŜŜŜŜŜŜŜŜŜŜ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ƀƀƀƀƀƀƀƀƀƀ")
		collection.add("ąąąąąąąąąą")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ĐĐĐĐĐĐĐĐĐĐ")
		collection.add("ƅƅƅƅƅƅƅƅƅƅ")
		collection.add("ññññññññññ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ġġġġġġġġġġ")
		collection.add("ğğğğğğğğğğ")
		collection.add("ðððððððððð")
		collection.add("ƃƃƃƃƃƃƃƃƃƃ")
		collection.add("īīīīīīīīīī")
		collection.add("ĘĘĘĘĘĘĘĘĘĘ")
		collection.add("ŬŬŬŬŬŬŬŬŬŬ")
		collection.add("ƈƈƈƈƈƈƈƈƈƈ")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ÒÒÒÒÒÒÒÒÒÒ")
		collection.add("ŹŹŹŹŹŹŹŹŹŹ")
		collection.add("īīīīīīīīīī")
		collection.add("ƊƊƊƊƊƊƊƊƊƊ")
		collection.add("ŁŁŁŁŁŁŁŁŁŁ")
		collection.add("ãããããããããã")
		collection.add("ëëëëëëëëëë")
		collection.add("ıııııııııı")
		collection.add("ææææææææææ")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ųųųųųųųųųų")
		collection.add("őőőőőőőőőő")
		collection.add("ññññññññññ")
		collection.add("űűűűűűűűűű")
		collection.add("ĿĿĿĿĿĿĿĿĿĿ")
		collection.add("ŲŲŲŲŲŲŲŲŲŲ")
		collection.add("ŊŊŊŊŊŊŊŊŊŊ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("åååååååååå")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("ņņņņņņņņņņ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("øøøøøøøøøø")
		collection.add("ďďďďďďďďďď")
		collection.add("××××××××××")
		collection.add("ĦĦĦĦĦĦĦĦĦĦ")
		collection.add("ĒĒĒĒĒĒĒĒĒĒ")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("àààààààààà")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ƉƉƉƉƉƉƉƉƉƉ")
		collection.add("ëëëëëëëëëë")
		collection.add("úúúúúúúúúú")
		collection.add("āāāāāāāāāā")
		collection.add("ńńńńńńńńńń")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ŮŮŮŮŮŮŮŮŮŮ")
		collection.add("ÞÞÞÞÞÞÞÞÞÞ")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ıııııııııı")
		collection.add("ôôôôôôôôôô")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ŷŷŷŷŷŷŷŷŷŷ")
		collection.add("ŸŸŸŸŸŸŸŸŸŸ")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ØØØØØØØØØØ")
		collection.add("ðððððððððð")
		collection.add("ŒŒŒŒŒŒŒŒŒŒ")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ŐŐŐŐŐŐŐŐŐŐ")
		collection.add("ÉÉÉÉÉÉÉÉÉÉ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ìììììììììì")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("īīīīīīīīīī")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ĻĻĻĻĻĻĻĻĻĻ")
		collection.add("ŶŶŶŶŶŶŶŶŶŶ")
		collection.add("ŖŖŖŖŖŖŖŖŖŖ")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("úúúúúúúúúú")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("ŠŠŠŠŠŠŠŠŠŠ")
		collection.add("ĐĐĐĐĐĐĐĐĐĐ")
		collection.add("çççççççççç")
		collection.add("ěěěěěěěěěě")
		collection.add("ŖŖŖŖŖŖŖŖŖŖ")
		collection.add("ĩĩĩĩĩĩĩĩĩĩ")
		collection.add("čččččččččč")
		collection.add("āāāāāāāāāā")
		collection.add("ŧŧŧŧŧŧŧŧŧŧ")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ęęęęęęęęęę")
		collection.add("ïïïïïïïïïï")
		collection.add("ŒŒŒŒŒŒŒŒŒŒ")
		collection.add("çççççççççç")
		collection.add("őőőőőőőőőő")
		collection.add("İİİİİİİİİİ")
		collection.add("ĚĚĚĚĚĚĚĚĚĚ")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("ĴĴĴĴĴĴĴĴĴĴ")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("ăăăăăăăăăă")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ŋŋŋŋŋŋŋŋŋŋ")
		collection.add("ßßßßßßßßßß")
		collection.add("þþþþþþþþþþ")
		collection.add("ēēēēēēēēēē")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("İİİİİİİİİİ")
		collection.add("ëëëëëëëëëë")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("ýýýýýýýýýý")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ęęęęęęęęęę")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ĢĢĢĢĢĢĢĢĢĢ")
		collection.add("ĖĖĖĖĖĖĖĖĖĖ")
		collection.add("ťťťťťťťťťť")
		collection.add("ĂĂĂĂĂĂĂĂĂĂ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ŻŻŻŻŻŻŻŻŻŻ")
		collection.add("ĠĠĠĠĠĠĠĠĠĠ")
		collection.add("ĥĥĥĥĥĥĥĥĥĥ")
		collection.add("ƂƂƂƂƂƂƂƂƂƂ")
		collection.add("ĨĨĨĨĨĨĨĨĨĨ")
		collection.add("ŲŲŲŲŲŲŲŲŲŲ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ýýýýýýýýýý")
		collection.add("ÐÐÐÐÐÐÐÐÐÐ")
		collection.add("ƌƌƌƌƌƌƌƌƌƌ")
		collection.add("īīīīīīīīīī")
		collection.add("××××××××××")
		collection.add("čččččččččč")
		collection.add("ëëëëëëëëëë")
		collection.add("ññññññññññ")
		collection.add("üüüüüüüüüü")
		collection.add("ğğğğğğğğğğ")
		collection.add("ÝÝÝÝÝÝÝÝÝÝ")
		collection.add("řřřřřřřřřř")
		collection.add("ďďďďďďďďďď")
		collection.add("ğğğğğğğğğğ")
		collection.add("åååååååååå")
		collection.add("žžžžžžžžžž")
		collection.add("ČČČČČČČČČČ")
		collection.add("ùùùùùùùùùù")
		collection.add("õõõõõõõõõõ")
		collection.add("ħħħħħħħħħħ")
		collection.add("ĀĀĀĀĀĀĀĀĀĀ")
		collection.add("ĊĊĊĊĊĊĊĊĊĊ")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("čččččččččč")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ääääääääää")
		collection.add("ĲĲĲĲĲĲĲĲĲĲ")
		collection.add("ûûûûûûûûûû")
		collection.add("ťťťťťťťťťť")
		collection.add("ÌÌÌÌÌÌÌÌÌÌ")
		collection.add("ÜÜÜÜÜÜÜÜÜÜ")
		collection.add("ƋƋƋƋƋƋƋƋƋƋ")
		collection.add("ÏÏÏÏÏÏÏÏÏÏ")
		collection.add("śśśśśśśśśś")
		collection.add("ĐĐĐĐĐĐĐĐĐĐ")
		collection.add("ĵĵĵĵĵĵĵĵĵĵ")
		collection.add("ĉĉĉĉĉĉĉĉĉĉ")
		collection.add("ņņņņņņņņņņ")
		collection.add("āāāāāāāāāā")
		collection.add("ħħħħħħħħħħ")
		collection.add("żżżżżżżżżż")
		collection.add("ôôôôôôôôôô")
		collection.add("ŚŚŚŚŚŚŚŚŚŚ")
		collection.add("úúúúúúúúúú")
		collection.add("ÿÿÿÿÿÿÿÿÿÿ")
		collection.add("ŇŇŇŇŇŇŇŇŇŇ")
		collection.add("śśśśśśśśśś")
		collection.add("ķķķķķķķķķķ")
		collection.add("ŵŵŵŵŵŵŵŵŵŵ")
		collection.add("ſſſſſſſſſſ")
		collection.add("ŕŕŕŕŕŕŕŕŕŕ")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("ċċċċċċċċċċ")
		collection.add("ēēēēēēēēēē")
		collection.add("ųųųųųųųųųų")
		collection.add("ƅƅƅƅƅƅƅƅƅƅ")
		collection.add("ææææææææææ")
		collection.add("ģģģģģģģģģģ")
		collection.add("ćććććććććć")
		collection.add("ŢŢŢŢŢŢŢŢŢŢ")
		collection.add("ŃŃŃŃŃŃŃŃŃŃ")
		collection.add("ƆƆƆƆƆƆƆƆƆƆ")
		collection.add("ňňňňňňňňňň")
		collection.add("ÎÎÎÎÎÎÎÎÎÎ")
		collection.add("ŝŝŝŝŝŝŝŝŝŝ")
		collection.add("ôôôôôôôôôô")
		collection.add("ēēēēēēēēēē")
		collection.add("ÉÉÉÉÉÉÉÉÉÉ")
		collection.add("żżżżżżżżżż")
		collection.add("şşşşşşşşşş")
		collection.add("ĬĬĬĬĬĬĬĬĬĬ")
		collection.add("ŏŏŏŏŏŏŏŏŏŏ")
		collection.add("ģģģģģģģģģģ")
		collection.add("ãããããããããã")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("čččččččččč")
		collection.add("ŀŀŀŀŀŀŀŀŀŀ")
		collection.add("ŎŎŎŎŎŎŎŎŎŎ")
		collection.add("ĕĕĕĕĕĕĕĕĕĕ")
		collection.add("ÍÍÍÍÍÍÍÍÍÍ")
		collection.add("ĔĔĔĔĔĔĔĔĔĔ")
		collection.add("ĽĽĽĽĽĽĽĽĽĽ")
		collection.add("ïïïïïïïïïï")
		collection.add("żżżżżżżżżż")
		collection.add("üüüüüüüüüü")
	}
	@Benchmark
	@Fork(1)
	@Warmup(time=3)
	@Measurement(time=3,iterations=10)
	def STreeSet(bh: Blackhole): Unit = {
		collection = collection.union(mutable.HashSet[String]("ƅƅƅƅƅƅƅƅƅƅ","ËËËËËËËËËË","ŤŤŤŤŤŤŤŤŤŤ","ŬŬŬŬŬŬŬŬŬŬ"))
		bh.consume(collection.add("ĚĚĚĚĚĚĚĚĚĚ"))
		collection = collection.union(mutable.HashSet[String]("ĸĸĸĸĸĸĸĸĸĸ","ÔÔÔÔÔÔÔÔÔÔ","ĆĆĆĆĆĆĆĆĆĆ"))
		bh.consume(collection.add("ęęęęęęęęęę"))
		bh.consume(collection.add("ŦŦŦŦŦŦŦŦŦŦ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ØØØØØØØØØØ","ØØØØØØØØØØ","ĊĊĊĊĊĊĊĊĊĊ","ŦŦŦŦŦŦŦŦŦŦ")))
		collection = collection.diff(mutable.HashSet[String]("ÓÓÓÓÓÓÓÓÓÓ","ƃƃƃƃƃƃƃƃƃƃ","ÿÿÿÿÿÿÿÿÿÿ","ƂƂƂƂƂƂƂƂƂƂ"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ƏƏƏƏƏƏƏƏƏƏ","ƉƉƉƉƉƉƉƉƉƉ","ƈƈƈƈƈƈƈƈƈƈ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÎÎÎÎÎÎÎÎÎÎ","ĥĥĥĥĥĥĥĥĥĥ","őőőőőőőőőő")))
		collection = collection.union(mutable.HashSet[String]("ŚŚŚŚŚŚŚŚŚŚ","ƀƀƀƀƀƀƀƀƀƀ","îîîîîîîîîî"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ÜÜÜÜÜÜÜÜÜÜ","łłłłłłłłłł","ŋŋŋŋŋŋŋŋŋŋ"))
		collection = collection.union(mutable.HashSet[String]("žžžžžžžžžž","ÚÚÚÚÚÚÚÚÚÚ","ĽĽĽĽĽĽĽĽĽĽ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÎÎÎÎÎÎÎÎÎÎ","ÙÙÙÙÙÙÙÙÙÙ","ßßßßßßßßßß","żżżżżżżżżż")))
		collection = collection.union(mutable.HashSet[String]("ÜÜÜÜÜÜÜÜÜÜ","ŨŨŨŨŨŨŨŨŨŨ","ƈƈƈƈƈƈƈƈƈƈ","ƀƀƀƀƀƀƀƀƀƀ"))
		collection = collection.union(mutable.HashSet[String]("ŢŢŢŢŢŢŢŢŢŢ","ţţţţţţţţţţ","õõõõõõõõõõ","÷÷÷÷÷÷÷÷÷÷"))
		bh.consume(collection.add("õõõõõõõõõõ"))
		bh.consume(collection.add("ïïïïïïïïïï"))
		bh.consume(collection.add("ŝŝŝŝŝŝŝŝŝŝ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĭĭĭĭĭĭĭĭĭĭ","ųųųųųųųųųų","ĕĕĕĕĕĕĕĕĕĕ","ĐĐĐĐĐĐĐĐĐĐ")))
		collection = collection.diff(mutable.HashSet[String]("êêêêêêêêêê","ƋƋƋƋƋƋƋƋƋƋ","ŇŇŇŇŇŇŇŇŇŇ","ħħħħħħħħħħ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŧŧŧŧŧŧŧŧŧŧ"))
		collection = collection.union(mutable.HashSet[String]("ćććććććććć","ĲĲĲĲĲĲĲĲĲĲ","åååååååååå","ħħħħħħħħħħ"))
		collection = collection.union(mutable.HashSet[String]("ĬĬĬĬĬĬĬĬĬĬ","ŅŅŅŅŅŅŅŅŅŅ","ññññññññññ"))
		bh.consume(collection.add("ßßßßßßßßßß"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ėėėėėėėėėė","ŷŷŷŷŷŷŷŷŷŷ","ææææææææææ")))
		collection = collection.union(mutable.HashSet[String]("ŹŹŹŹŹŹŹŹŹŹ","ĐĐĐĐĐĐĐĐĐĐ","ŷŷŷŷŷŷŷŷŷŷ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ŝŝŝŝŝŝŝŝŝŝ","řřřřřřřřřř","ąąąąąąąąąą"))
		bh.consume(collection.remove("ŝŝŝŝŝŝŝŝŝŝ"))
		bh.consume(collection.contains("şşşşşşşşşş"))
		collection.toArray(classTag[String])
		bh.consume(collection.remove("ëëëëëëëëëë"))
		bh.consume(collection.add("ŰŰŰŰŰŰŰŰŰŰ"))
		collection = collection.union(mutable.HashSet[String]("ŀŀŀŀŀŀŀŀŀŀ","ĬĬĬĬĬĬĬĬĬĬ","ũũũũũũũũũũ"))
		bh.consume(collection.add("ėėėėėėėėėė"))
		bh.consume(collection.add("ÖÖÖÖÖÖÖÖÖÖ"))
		collection = collection.diff(mutable.HashSet[String]("îîîîîîîîîî","ĵĵĵĵĵĵĵĵĵĵ","ŲŲŲŲŲŲŲŲŲŲ","ĄĄĄĄĄĄĄĄĄĄ"))
		collection = collection.diff(mutable.HashSet[String]("ƄƄƄƄƄƄƄƄƄƄ","ÛÛÛÛÛÛÛÛÛÛ","ĮĮĮĮĮĮĮĮĮĮ","ƅƅƅƅƅƅƅƅƅƅ"))
		collection = collection.union(mutable.HashSet[String]("ŕŕŕŕŕŕŕŕŕŕ","ģģģģģģģģģģ","źźźźźźźźźź","ƎƎƎƎƎƎƎƎƎƎ"))
		collection = collection.union(mutable.HashSet[String]("øøøøøøøøøø","ŝŝŝŝŝŝŝŝŝŝ","ŕŕŕŕŕŕŕŕŕŕ"))
		bh.consume(collection.contains("ƊƊƊƊƊƊƊƊƊƊ"))
		bh.consume(collection.add("şşşşşşşşşş"))
		bh.consume(collection.add("ýýýýýýýýýý"))
		collection = collection.union(mutable.HashSet[String]("ēēēēēēēēēē","ŶŶŶŶŶŶŶŶŶŶ","ƂƂƂƂƂƂƂƂƂƂ","òòòòòòòòòò"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŤŤŤŤŤŤŤŤŤŤ"))
		bh.consume(collection.remove("ìììììììììì"))
		bh.consume(collection.add("ææææææææææ"))
		collection = collection.diff(mutable.HashSet[String]("ƆƆƆƆƆƆƆƆƆƆ","ÙÙÙÙÙÙÙÙÙÙ","őőőőőőőőőő"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ýýýýýýýýýý","ŸŸŸŸŸŸŸŸŸŸ","ďďďďďďďďďď","ŨŨŨŨŨŨŨŨŨŨ")))
		bh.consume(collection.add("ĄĄĄĄĄĄĄĄĄĄ"))
		collection = collection.union(mutable.HashSet[String]("ĺĺĺĺĺĺĺĺĺĺ","ŅŅŅŅŅŅŅŅŅŅ","ĖĖĖĖĖĖĖĖĖĖ","ññññññññññ"))
		collection = collection.diff(mutable.HashSet[String]("œœœœœœœœœœ","śśśśśśśśśś","ŬŬŬŬŬŬŬŬŬŬ"))
		bh.consume(collection.remove("ŗŗŗŗŗŗŗŗŗŗ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("śśśśśśśśśś"))
		bh.consume(collection.remove("ŁŁŁŁŁŁŁŁŁŁ"))
		collection = collection.diff(mutable.HashSet[String]("ƉƉƉƉƉƉƉƉƉƉ","ľľľľľľľľľľ","ūūūūūūūūūū","šššššššššš"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŒŒŒŒŒŒŒŒŒŒ","įįįįįįįįįį","ģģģģģģģģģģ")))
		collection = collection.union(mutable.HashSet[String]("òòòòòòòòòò","ĄĄĄĄĄĄĄĄĄĄ","ŜŜŜŜŜŜŜŜŜŜ","ĨĨĨĨĨĨĨĨĨĨ"))
		collection = collection.diff(mutable.HashSet[String]("ŒŒŒŒŒŒŒŒŒŒ","ÝÝÝÝÝÝÝÝÝÝ","ġġġġġġġġġġ","ĸĸĸĸĸĸĸĸĸĸ"))
		bh.consume(collection.add("ĨĨĨĨĨĨĨĨĨĨ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ƋƋƋƋƋƋƋƋƋƋ","ąąąąąąąąąą","××××××××××")))
		collection = collection.union(mutable.HashSet[String]("ŒŒŒŒŒŒŒŒŒŒ","ŒŒŒŒŒŒŒŒŒŒ","ĚĚĚĚĚĚĚĚĚĚ","ŠŠŠŠŠŠŠŠŠŠ"))
		collection = collection.union(mutable.HashSet[String]("ŋŋŋŋŋŋŋŋŋŋ","İİİİİİİİİİ","ħħħħħħħħħħ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ğğğğğğğğğğ","ēēēēēēēēēē","źźźźźźźźźź"))
		collection = collection.union(mutable.HashSet[String]("áááááááááá","ĀĀĀĀĀĀĀĀĀĀ","ĨĨĨĨĨĨĨĨĨĨ"))
		collection = collection.union(mutable.HashSet[String]("ÒÒÒÒÒÒÒÒÒÒ","ÞÞÞÞÞÞÞÞÞÞ","ďďďďďďďďďď"))
		bh.consume(collection.contains("ÙÙÙÙÙÙÙÙÙÙ"))
		bh.consume(collection.add("ļļļļļļļļļļ"))
		collection = collection.union(mutable.HashSet[String]("ēēēēēēēēēē","ŀŀŀŀŀŀŀŀŀŀ","ļļļļļļļļļļ","ƏƏƏƏƏƏƏƏƏƏ"))
		bh.consume(collection.add("ĂĂĂĂĂĂĂĂĂĂ"))
		bh.consume(collection.add("řřřřřřřřřř"))
		bh.consume(collection.remove("ĿĿĿĿĿĿĿĿĿĿ"))
		bh.consume(collection.remove("ƈƈƈƈƈƈƈƈƈƈ"))
		collection = collection.diff(mutable.HashSet[String]("őőőőőőőőőő","ġġġġġġġġġġ","ĥĥĥĥĥĥĥĥĥĥ","ÞÞÞÞÞÞÞÞÞÞ"))
		bh.consume(collection.add("ĴĴĴĴĴĴĴĴĴĴ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŕŕŕŕŕŕŕŕŕŕ","ÜÜÜÜÜÜÜÜÜÜ","éééééééééé","ĖĖĖĖĖĖĖĖĖĖ")))
		bh.consume(collection.add("ūūūūūūūūūū"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ææææææææææ","ĪĪĪĪĪĪĪĪĪĪ","ÈÈÈÈÈÈÈÈÈÈ","ŕŕŕŕŕŕŕŕŕŕ"))
		bh.consume(collection.remove("ıııııııııı"))
		bh.consume(collection.remove("üüüüüüüüüü"))
		bh.consume(collection.add("ľľľľľľľľľľ"))
		collection = collection.union(mutable.HashSet[String]("ėėėėėėėėėė","ëëëëëëëëëë","ćććććććććć"))
		bh.consume(collection.remove("ÜÜÜÜÜÜÜÜÜÜ"))
		bh.consume(collection.add("ŷŷŷŷŷŷŷŷŷŷ"))
		collection = collection.diff(mutable.HashSet[String]("ħħħħħħħħħħ","ęęęęęęęęęę","ËËËËËËËËËË"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŝŝŝŝŝŝŝŝŝŝ"))
		collection = collection.diff(mutable.HashSet[String]("ƇƇƇƇƇƇƇƇƇƇ","ŭŭŭŭŭŭŭŭŭŭ","ěěěěěěěěěě","śśśśśśśśśś"))
		collection = collection.diff(mutable.HashSet[String]("éééééééééé","ÊÊÊÊÊÊÊÊÊÊ","ĀĀĀĀĀĀĀĀĀĀ"))
		collection = collection.diff(mutable.HashSet[String]("ŎŎŎŎŎŎŎŎŎŎ","ĜĜĜĜĜĜĜĜĜĜ","ŧŧŧŧŧŧŧŧŧŧ"))
		collection = collection.union(mutable.HashSet[String]("ĦĦĦĦĦĦĦĦĦĦ","ĶĶĶĶĶĶĶĶĶĶ","ĂĂĂĂĂĂĂĂĂĂ"))
		bh.consume(collection.add("ņņņņņņņņņņ"))
		bh.consume(collection.add("őőőőőőőőőő"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ěěěěěěěěěě","××××××××××","ûûûûûûûûûû")))
		bh.consume(collection.remove("ųųųųųųųųųų"))
		bh.consume(collection.remove("öööööööööö"))
		collection = collection.union(mutable.HashSet[String]("áááááááááá","ŠŠŠŠŠŠŠŠŠŠ","ŘŘŘŘŘŘŘŘŘŘ","ĻĻĻĻĻĻĻĻĻĻ"))
		collection = collection.diff(mutable.HashSet[String]("ũũũũũũũũũũ","åååååååååå","ůůůůůůůůůů"))
		bh.consume(collection.add("ĹĹĹĹĹĹĹĹĹĹ"))
		collection = collection.union(mutable.HashSet[String]("ŝŝŝŝŝŝŝŝŝŝ","ĢĢĢĢĢĢĢĢĢĢ","ãããããããããã"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ÉÉÉÉÉÉÉÉÉÉ","ùùùùùùùùùù","ŐŐŐŐŐŐŐŐŐŐ"))
		bh.consume(collection.remove("ūūūūūūūūūū"))
		bh.consume(collection.contains("ąąąąąąąąąą"))
		bh.consume(collection.add("ĘĘĘĘĘĘĘĘĘĘ"))
		bh.consume(collection.add("ÞÞÞÞÞÞÞÞÞÞ"))
		bh.consume(collection.add("ïïïïïïïïïï"))
		bh.consume(collection.add("ŰŰŰŰŰŰŰŰŰŰ"))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ČČČČČČČČČČ","ēēēēēēēēēē","åååååååååå")))
		collection = collection.diff(mutable.HashSet[String]("ÊÊÊÊÊÊÊÊÊÊ","ŅŅŅŅŅŅŅŅŅŅ","××××××××××"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŴŴŴŴŴŴŴŴŴŴ","ĬĬĬĬĬĬĬĬĬĬ","ŃŃŃŃŃŃŃŃŃŃ","ƈƈƈƈƈƈƈƈƈƈ")))
		collection = collection.diff(mutable.HashSet[String]("ôôôôôôôôôô","óóóóóóóóóó","ļļļļļļļļļļ","ÉÉÉÉÉÉÉÉÉÉ"))
		bh.consume(collection.remove("ťťťťťťťťťť"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŉŉŉŉŉŉŉŉŉŉ","éééééééééé","ŃŃŃŃŃŃŃŃŃŃ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĘĘĘĘĘĘĘĘĘĘ","ææææææææææ","ġġġġġġġġġġ","ÌÌÌÌÌÌÌÌÌÌ")))
		bh.consume(collection.add("ÝÝÝÝÝÝÝÝÝÝ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ââââââââââ"))
		collection = collection.diff(mutable.HashSet[String]("ŪŪŪŪŪŪŪŪŪŪ","ÌÌÌÌÌÌÌÌÌÌ","ĝĝĝĝĝĝĝĝĝĝ","ûûûûûûûûûû"))
		bh.consume(collection.add("ěěěěěěěěěě"))
		bh.consume(collection.remove("áááááááááá"))
		collection = collection.diff(mutable.HashSet[String]("ƊƊƊƊƊƊƊƊƊƊ","śśśśśśśśśś","ƁƁƁƁƁƁƁƁƁƁ"))
		bh.consume(collection.add("åååååååååå"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("êêêêêêêêêê"))
		bh.consume(collection.add("ƍƍƍƍƍƍƍƍƍƍ"))
		bh.consume(collection.add("àààààààààà"))
		bh.consume(collection.contains("ŭŭŭŭŭŭŭŭŭŭ"))
		bh.consume(collection.remove("ÈÈÈÈÈÈÈÈÈÈ"))
		bh.consume(collection.add("ùùùùùùùùùù"))
		bh.consume(collection.add("××××××××××"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŁŁŁŁŁŁŁŁŁŁ","İİİİİİİİİİ","ŴŴŴŴŴŴŴŴŴŴ")))
		collection = collection.union(mutable.HashSet[String]("ģģģģģģģģģģ","ĞĞĞĞĞĞĞĞĞĞ","ÖÖÖÖÖÖÖÖÖÖ"))
		collection = collection.union(mutable.HashSet[String]("ĳĳĳĳĳĳĳĳĳĳ","îîîîîîîîîî","ŽŽŽŽŽŽŽŽŽŽ"))
		collection = collection.union(mutable.HashSet[String]("őőőőőőőőőő","ÓÓÓÓÓÓÓÓÓÓ","łłłłłłłłłł"))
		bh.consume(collection.add("ŉŉŉŉŉŉŉŉŉŉ"))
		collection = collection.union(mutable.HashSet[String]("ćććććććććć","ïïïïïïïïïï","èèèèèèèèèè"))
		bh.consume(collection.add("ðððððððððð"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ƄƄƄƄƄƄƄƄƄƄ","ĒĒĒĒĒĒĒĒĒĒ","ůůůůůůůůůů")))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĠĠĠĠĠĠĠĠĠĠ","ææææææææææ","ƅƅƅƅƅƅƅƅƅƅ","òòòòòòòòòò")))
		bh.consume(collection.add("ŴŴŴŴŴŴŴŴŴŴ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŸŸŸŸŸŸŸŸŸŸ","ÖÖÖÖÖÖÖÖÖÖ","ĎĎĎĎĎĎĎĎĎĎ","ıııııııııı")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŞŞŞŞŞŞŞŞŞŞ","ćććććććććć","ýýýýýýýýýý","ĀĀĀĀĀĀĀĀĀĀ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŲŲŲŲŲŲŲŲŲŲ","ņņņņņņņņņņ","ïïïïïïïïïï","ĮĮĮĮĮĮĮĮĮĮ")))
		bh.consume(collection.add("ŇŇŇŇŇŇŇŇŇŇ"))
		collection = collection.diff(mutable.HashSet[String]("ģģģģģģģģģģ","ßßßßßßßßßß","ŖŖŖŖŖŖŖŖŖŖ"))
		collection = collection.union(mutable.HashSet[String]("ÎÎÎÎÎÎÎÎÎÎ","ŊŊŊŊŊŊŊŊŊŊ","ťťťťťťťťťť"))
		collection = collection.diff(mutable.HashSet[String]("ëëëëëëëëëë","ŕŕŕŕŕŕŕŕŕŕ","đđđđđđđđđđ"))
		bh.consume(collection.add("ċċċċċċċċċċ"))
		collection = collection.diff(mutable.HashSet[String]("œœœœœœœœœœ","ËËËËËËËËËË","ÑÑÑÑÑÑÑÑÑÑ","úúúúúúúúúú"))
		bh.consume(collection.contains("ŸŸŸŸŸŸŸŸŸŸ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ƈƈƈƈƈƈƈƈƈƈ","ññññññññññ","řřřřřřřřřř","ĖĖĖĖĖĖĖĖĖĖ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("óóóóóóóóóó","İİİİİİİİİİ","žžžžžžžžžž")))
		bh.consume(collection.add("ŤŤŤŤŤŤŤŤŤŤ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ŽŽŽŽŽŽŽŽŽŽ","ĳĳĳĳĳĳĳĳĳĳ","ƄƄƄƄƄƄƄƄƄƄ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĢĢĢĢĢĢĢĢĢĢ","ņņņņņņņņņņ","ƍƍƍƍƍƍƍƍƍƍ","ØØØØØØØØØØ")))
		collection = collection.union(mutable.HashSet[String]("ÓÓÓÓÓÓÓÓÓÓ","ŁŁŁŁŁŁŁŁŁŁ","ÉÉÉÉÉÉÉÉÉÉ"))
		bh.consume(collection.contains("ŮŮŮŮŮŮŮŮŮŮ"))
		collection = collection.diff(mutable.HashSet[String]("ņņņņņņņņņņ","üüüüüüüüüü","áááááááááá"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĭĭĭĭĭĭĭĭĭĭ","ĂĂĂĂĂĂĂĂĂĂ","ĤĤĤĤĤĤĤĤĤĤ")))
		collection = collection.union(mutable.HashSet[String]("ņņņņņņņņņņ","ŢŢŢŢŢŢŢŢŢŢ","ŰŰŰŰŰŰŰŰŰŰ","ƅƅƅƅƅƅƅƅƅƅ"))
		bh.consume(collection.add("ęęęęęęęęęę"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĩĩĩĩĩĩĩĩĩĩ","éééééééééé","ĕĕĕĕĕĕĕĕĕĕ","ŁŁŁŁŁŁŁŁŁŁ")))
		bh.consume(collection.remove("ŮŮŮŮŮŮŮŮŮŮ"))
		collection = collection.union(mutable.HashSet[String]("ŶŶŶŶŶŶŶŶŶŶ","ƉƉƉƉƉƉƉƉƉƉ","ÑÑÑÑÑÑÑÑÑÑ","ƊƊƊƊƊƊƊƊƊƊ"))
		collection = collection.union(mutable.HashSet[String]("ŶŶŶŶŶŶŶŶŶŶ","ŢŢŢŢŢŢŢŢŢŢ","ŢŢŢŢŢŢŢŢŢŢ"))
		bh.consume(collection.add("èèèèèèèèèè"))
		collection = collection.diff(mutable.HashSet[String]("ĴĴĴĴĴĴĴĴĴĴ","ïïïïïïïïïï","ƈƈƈƈƈƈƈƈƈƈ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŗŗŗŗŗŗŗŗŗŗ","ÐÐÐÐÐÐÐÐÐÐ","ţţţţţţţţţţ","ŅŅŅŅŅŅŅŅŅŅ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("śśśśśśśśśś","ƆƆƆƆƆƆƆƆƆƆ","ůůůůůůůůůů","śśśśśśśśśś")))
		collection = collection.diff(mutable.HashSet[String]("ċċċċċċċċċċ","ŷŷŷŷŷŷŷŷŷŷ","ÎÎÎÎÎÎÎÎÎÎ","āāāāāāāāāā"))
		collection = collection.union(mutable.HashSet[String]("ęęęęęęęęęę","ĤĤĤĤĤĤĤĤĤĤ","ķķķķķķķķķķ"))
		collection = collection.union(mutable.HashSet[String]("ÌÌÌÌÌÌÌÌÌÌ","ňňňňňňňňňň","ŖŖŖŖŖŖŖŖŖŖ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ħħħħħħħħħħ","ĠĠĠĠĠĠĠĠĠĠ","ēēēēēēēēēē")))
		collection = collection.union(mutable.HashSet[String]("œœœœœœœœœœ","đđđđđđđđđđ","ŢŢŢŢŢŢŢŢŢŢ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÛÛÛÛÛÛÛÛÛÛ","űűűűűűűűűű","óóóóóóóóóó","ùùùùùùùùùù")))
		collection = collection.diff(mutable.HashSet[String]("ĲĲĲĲĲĲĲĲĲĲ","ææææææææææ","ĞĞĞĞĞĞĞĞĞĞ","ŎŎŎŎŎŎŎŎŎŎ"))
		bh.consume(collection.add("ĳĳĳĳĳĳĳĳĳĳ"))
		collection = collection.union(mutable.HashSet[String]("ŤŤŤŤŤŤŤŤŤŤ","ĻĻĻĻĻĻĻĻĻĻ","ŭŭŭŭŭŭŭŭŭŭ","āāāāāāāāāā"))
		collection = collection.union(mutable.HashSet[String]("ŗŗŗŗŗŗŗŗŗŗ","ďďďďďďďďďď","łłłłłłłłłł","ėėėėėėėėėė"))
		bh.consume(collection.add("ĪĪĪĪĪĪĪĪĪĪ"))
		bh.consume(collection.add("ĺĺĺĺĺĺĺĺĺĺ"))
		bh.consume(collection.add("ČČČČČČČČČČ"))
		collection = collection.union(mutable.HashSet[String]("ĸĸĸĸĸĸĸĸĸĸ","ŕŕŕŕŕŕŕŕŕŕ","ėėėėėėėėėė","ĩĩĩĩĩĩĩĩĩĩ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ƌƌƌƌƌƌƌƌƌƌ","ĶĶĶĶĶĶĶĶĶĶ","ŻŻŻŻŻŻŻŻŻŻ","ĒĒĒĒĒĒĒĒĒĒ")))
		bh.consume(collection.add("ŇŇŇŇŇŇŇŇŇŇ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŮŮŮŮŮŮŮŮŮŮ","ĒĒĒĒĒĒĒĒĒĒ","øøøøøøøøøø")))
		bh.consume(collection.add("ņņņņņņņņņņ"))
		collection = collection.union(mutable.HashSet[String]("ĿĿĿĿĿĿĿĿĿĿ","ĸĸĸĸĸĸĸĸĸĸ","ęęęęęęęęęę","ŐŐŐŐŐŐŐŐŐŐ"))
		bh.consume(collection.remove("ĴĴĴĴĴĴĴĴĴĴ"))
		collection = collection.union(mutable.HashSet[String]("ğğğğğğğğğğ","ğğğğğğğğğğ","ÑÑÑÑÑÑÑÑÑÑ","ËËËËËËËËËË"))
		collection = collection.diff(mutable.HashSet[String]("ſſſſſſſſſſ","ľľľľľľľľľľ","ææææææææææ","ÞÞÞÞÞÞÞÞÞÞ"))
		bh.consume(collection.remove("ĒĒĒĒĒĒĒĒĒĒ"))
		collection = collection.union(mutable.HashSet[String]("ËËËËËËËËËË","ťťťťťťťťťť","ķķķķķķķķķķ"))
		bh.consume(collection.remove("żżżżżżżżżż"))
		collection = collection.diff(mutable.HashSet[String]("ųųųųųųųųųų","ŧŧŧŧŧŧŧŧŧŧ","ƍƍƍƍƍƍƍƍƍƍ","ŎŎŎŎŎŎŎŎŎŎ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("õõõõõõõõõõ","ŗŗŗŗŗŗŗŗŗŗ","ƌƌƌƌƌƌƌƌƌƌ","ĺĺĺĺĺĺĺĺĺĺ"))
		bh.consume(collection.add("ÌÌÌÌÌÌÌÌÌÌ"))
		bh.consume(collection.add("ĆĆĆĆĆĆĆĆĆĆ"))
		collection = collection.union(mutable.HashSet[String]("ƏƏƏƏƏƏƏƏƏƏ","ļļļļļļļļļļ","ŒŒŒŒŒŒŒŒŒŒ","üüüüüüüüüü"))
		collection = collection.union(mutable.HashSet[String]("ĉĉĉĉĉĉĉĉĉĉ","ŨŨŨŨŨŨŨŨŨŨ","ûûûûûûûûûû"))
		bh.consume(collection.add("ŷŷŷŷŷŷŷŷŷŷ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŋŋŋŋŋŋŋŋŋŋ"))
		bh.consume(collection.add("ĀĀĀĀĀĀĀĀĀĀ"))
		collection = collection.union(mutable.HashSet[String]("ùùùùùùùùùù","ŷŷŷŷŷŷŷŷŷŷ","ƏƏƏƏƏƏƏƏƏƏ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("òòòòòòòòòò","ŋŋŋŋŋŋŋŋŋŋ","ÈÈÈÈÈÈÈÈÈÈ","ĬĬĬĬĬĬĬĬĬĬ")))
		collection = collection.union(mutable.HashSet[String]("ĭĭĭĭĭĭĭĭĭĭ","ŇŇŇŇŇŇŇŇŇŇ","ÛÛÛÛÛÛÛÛÛÛ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŤŤŤŤŤŤŤŤŤŤ","ĿĿĿĿĿĿĿĿĿĿ","łłłłłłłłłł")))
		collection = collection.diff(mutable.HashSet[String]("ćććććććććć","ĹĹĹĹĹĹĹĹĹĹ","ŐŐŐŐŐŐŐŐŐŐ"))
		bh.consume(collection.add("ŋŋŋŋŋŋŋŋŋŋ"))
		collection = collection.diff(mutable.HashSet[String]("÷÷÷÷÷÷÷÷÷÷","ĨĨĨĨĨĨĨĨĨĨ","ÿÿÿÿÿÿÿÿÿÿ","ĵĵĵĵĵĵĵĵĵĵ"))
		bh.consume(collection.contains("ŖŖŖŖŖŖŖŖŖŖ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ŽŽŽŽŽŽŽŽŽŽ","ĆĆĆĆĆĆĆĆĆĆ","ŤŤŤŤŤŤŤŤŤŤ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ęęęęęęęęęę"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ĲĲĲĲĲĲĲĲĲĲ","îîîîîîîîîî","ŕŕŕŕŕŕŕŕŕŕ","ÜÜÜÜÜÜÜÜÜÜ"))
		collection = collection.union(mutable.HashSet[String]("ƆƆƆƆƆƆƆƆƆƆ","œœœœœœœœœœ","ÝÝÝÝÝÝÝÝÝÝ","áááááááááá"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ĽĽĽĽĽĽĽĽĽĽ","ŵŵŵŵŵŵŵŵŵŵ","āāāāāāāāāā"))
		bh.consume(collection.add("õõõõõõõõõõ"))
		collection = collection.diff(mutable.HashSet[String]("þþþþþþþþþþ","řřřřřřřřřř","ÎÎÎÎÎÎÎÎÎÎ","ĤĤĤĤĤĤĤĤĤĤ"))
		collection = collection.union(mutable.HashSet[String]("āāāāāāāāāā","łłłłłłłłłł","çççççççççç","ĎĎĎĎĎĎĎĎĎĎ"))
		collection = collection.union(mutable.HashSet[String]("ĜĜĜĜĜĜĜĜĜĜ","ŪŪŪŪŪŪŪŪŪŪ","ąąąąąąąąąą","öööööööööö"))
		collection = collection.diff(mutable.HashSet[String]("ŅŅŅŅŅŅŅŅŅŅ","ÈÈÈÈÈÈÈÈÈÈ","óóóóóóóóóó"))
		bh.consume(collection.add("öööööööööö"))
		collection = collection.diff(mutable.HashSet[String]("ŧŧŧŧŧŧŧŧŧŧ","ŷŷŷŷŷŷŷŷŷŷ","ƇƇƇƇƇƇƇƇƇƇ","đđđđđđđđđđ"))
		collection = collection.diff(mutable.HashSet[String]("ľľľľľľľľľľ","ĴĴĴĴĴĴĴĴĴĴ","ðððððððððð"))
		collection = collection.diff(mutable.HashSet[String]("ĴĴĴĴĴĴĴĴĴĴ","ũũũũũũũũũũ","ăăăăăăăăăă","ññññññññññ"))
		bh.consume(collection.add("ŜŜŜŜŜŜŜŜŜŜ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÛÛÛÛÛÛÛÛÛÛ","ĠĠĠĠĠĠĠĠĠĠ","İİİİİİİİİİ")))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ÔÔÔÔÔÔÔÔÔÔ","ââââââââââ","ġġġġġġġġġġ","ŞŞŞŞŞŞŞŞŞŞ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÿÿÿÿÿÿÿÿÿÿ","ÊÊÊÊÊÊÊÊÊÊ","ýýýýýýýýýý","ĽĽĽĽĽĽĽĽĽĽ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("čččččččččč","ƌƌƌƌƌƌƌƌƌƌ","ßßßßßßßßßß")))
		bh.consume(collection.remove("üüüüüüüüüü"))
		collection = collection.union(mutable.HashSet[String]("ĊĊĊĊĊĊĊĊĊĊ","çççççççççç","ůůůůůůůůůů","ðððððððððð"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("àààààààààà","ēēēēēēēēēē","ËËËËËËËËËË")))
		bh.consume(collection.add("ğğğğğğğğğğ"))
		collection = collection.union(mutable.HashSet[String]("ĘĘĘĘĘĘĘĘĘĘ","őőőőőőőőőő","ÞÞÞÞÞÞÞÞÞÞ"))
		collection = collection.diff(mutable.HashSet[String]("ŦŦŦŦŦŦŦŦŦŦ","œœœœœœœœœœ","ĢĢĢĢĢĢĢĢĢĢ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("łłłłłłłłłł","ƀƀƀƀƀƀƀƀƀƀ","ŅŅŅŅŅŅŅŅŅŅ")))
		bh.consume(collection.add("ňňňňňňňňňň"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÛÛÛÛÛÛÛÛÛÛ","ĔĔĔĔĔĔĔĔĔĔ","åååååååååå","ƌƌƌƌƌƌƌƌƌƌ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ıııııııııı","éééééééééé","čččččččččč","ŬŬŬŬŬŬŬŬŬŬ")))
		bh.consume(collection.remove("ãããããããããã"))
		bh.consume(collection.add("òòòòòòòòòò"))
		collection = collection.union(mutable.HashSet[String]("ŬŬŬŬŬŬŬŬŬŬ","ŻŻŻŻŻŻŻŻŻŻ","łłłłłłłłłł"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÎÎÎÎÎÎÎÎÎÎ","ćććććććććć","ňňňňňňňňňň","ÎÎÎÎÎÎÎÎÎÎ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŀŀŀŀŀŀŀŀŀŀ","ĲĲĲĲĲĲĲĲĲĲ","ĐĐĐĐĐĐĐĐĐĐ","êêêêêêêêêê")))
		collection = collection.union(mutable.HashSet[String]("ÓÓÓÓÓÓÓÓÓÓ","ŰŰŰŰŰŰŰŰŰŰ","ýýýýýýýýýý","ŐŐŐŐŐŐŐŐŐŐ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("őőőőőőőőőő","þþþþþþþþþþ","ħħħħħħħħħħ","ĢĢĢĢĢĢĢĢĢĢ")))
		collection = collection.diff(mutable.HashSet[String]("ĂĂĂĂĂĂĂĂĂĂ","ƄƄƄƄƄƄƄƄƄƄ","ââââââââââ","ļļļļļļļļļļ"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŝŝŝŝŝŝŝŝŝŝ"))
		bh.consume(collection.add("ŽŽŽŽŽŽŽŽŽŽ"))
		bh.consume(collection.add("ĒĒĒĒĒĒĒĒĒĒ"))
		collection = collection.union(mutable.HashSet[String]("œœœœœœœœœœ","ĿĿĿĿĿĿĿĿĿĿ","ŤŤŤŤŤŤŤŤŤŤ","ğğğğğğğğğğ"))
		bh.consume(collection.remove("űűűűűűűűűű"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ŦŦŦŦŦŦŦŦŦŦ","ūūūūūūūūūū","öööööööööö"))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ďďďďďďďďďď","ųųųųųųųųųų","ĈĈĈĈĈĈĈĈĈĈ")))
		bh.consume(collection.add("ĒĒĒĒĒĒĒĒĒĒ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ƏƏƏƏƏƏƏƏƏƏ"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ÕÕÕÕÕÕÕÕÕÕ","ŃŃŃŃŃŃŃŃŃŃ","ĈĈĈĈĈĈĈĈĈĈ","ĄĄĄĄĄĄĄĄĄĄ"))
		bh.consume(collection.remove("œœœœœœœœœœ"))
		collection = collection.union(mutable.HashSet[String]("îîîîîîîîîî","ĊĊĊĊĊĊĊĊĊĊ","ĚĚĚĚĚĚĚĚĚĚ","řřřřřřřřřř"))
		bh.consume(collection.add("ÔÔÔÔÔÔÔÔÔÔ"))
		collection = collection.diff(mutable.HashSet[String]("ķķķķķķķķķķ","ŽŽŽŽŽŽŽŽŽŽ","ĴĴĴĴĴĴĴĴĴĴ","ÖÖÖÖÖÖÖÖÖÖ"))
		collection = collection.union(mutable.HashSet[String]("ÔÔÔÔÔÔÔÔÔÔ","ćććććććććć","àààààààààà","ÊÊÊÊÊÊÊÊÊÊ"))
		collection = collection.diff(mutable.HashSet[String]("ŪŪŪŪŪŪŪŪŪŪ","ſſſſſſſſſſ","ğğğğğğğğğğ"))
		collection = collection.union(mutable.HashSet[String]("ĩĩĩĩĩĩĩĩĩĩ","ĠĠĠĠĠĠĠĠĠĠ","İİİİİİİİİİ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĥĥĥĥĥĥĥĥĥĥ","ĹĹĹĹĹĹĹĹĹĹ","üüüüüüüüüü")))
		collection = collection.diff(mutable.HashSet[String]("ăăăăăăăăăă","öööööööööö","îîîîîîîîîî"))
		collection = collection.diff(mutable.HashSet[String]("ÙÙÙÙÙÙÙÙÙÙ","ŵŵŵŵŵŵŵŵŵŵ","ƃƃƃƃƃƃƃƃƃƃ","ðððððððððð"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ññññññññññ","ŐŐŐŐŐŐŐŐŐŐ","ĨĨĨĨĨĨĨĨĨĨ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("úúúúúúúúúú","ÙÙÙÙÙÙÙÙÙÙ","ĆĆĆĆĆĆĆĆĆĆ")))
		bh.consume(collection.add("ĔĔĔĔĔĔĔĔĔĔ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("îîîîîîîîîî","ęęęęęęęęęę","ťťťťťťťťťť")))
		bh.consume(collection.add("ĘĘĘĘĘĘĘĘĘĘ"))
		collection = collection.union(mutable.HashSet[String]("ľľľľľľľľľľ","ŞŞŞŞŞŞŞŞŞŞ","ëëëëëëëëëë"))
		bh.consume(collection.add("őőőőőőőőőő"))
		collection = collection.diff(mutable.HashSet[String]("ŕŕŕŕŕŕŕŕŕŕ","ŘŘŘŘŘŘŘŘŘŘ","ŹŹŹŹŹŹŹŹŹŹ","ÉÉÉÉÉÉÉÉÉÉ"))
		bh.consume(collection.add("ìììììììììì"))
		bh.consume(collection.add("ÍÍÍÍÍÍÍÍÍÍ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ƃƃƃƃƃƃƃƃƃƃ","ŏŏŏŏŏŏŏŏŏŏ","ÉÉÉÉÉÉÉÉÉÉ","ĺĺĺĺĺĺĺĺĺĺ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĠĠĠĠĠĠĠĠĠĠ","ÿÿÿÿÿÿÿÿÿÿ","ŬŬŬŬŬŬŬŬŬŬ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĕĕĕĕĕĕĕĕĕĕ","ŵŵŵŵŵŵŵŵŵŵ","ĮĮĮĮĮĮĮĮĮĮ")))
		bh.consume(collection.add("ôôôôôôôôôô"))
		bh.consume(collection.add("ŭŭŭŭŭŭŭŭŭŭ"))
		bh.consume(collection.add("ÐÐÐÐÐÐÐÐÐÐ"))
		bh.consume(collection.add("ääääääääää"))
		collection.toArray(classTag[String])
		bh.consume(collection.remove("ĀĀĀĀĀĀĀĀĀĀ"))
		bh.consume(collection.add("ďďďďďďďďďď"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("õõõõõõõõõõ","ÍÍÍÍÍÍÍÍÍÍ","ûûûûûûûûûû")))
		collection = collection.union(mutable.HashSet[String]("ññññññññññ","ĥĥĥĥĥĥĥĥĥĥ","ŢŢŢŢŢŢŢŢŢŢ"))
		bh.consume(collection.add("ņņņņņņņņņņ"))
		bh.consume(collection.add("ßßßßßßßßßß"))
		collection = collection.diff(mutable.HashSet[String]("ĭĭĭĭĭĭĭĭĭĭ","ľľľľľľľľľľ","ŭŭŭŭŭŭŭŭŭŭ"))
		bh.consume(collection.remove("ÞÞÞÞÞÞÞÞÞÞ"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("éééééééééé","ääääääääää","ģģģģģģģģģģ"))
		bh.consume(collection.add("ßßßßßßßßßß"))
		bh.consume(collection.add("ƁƁƁƁƁƁƁƁƁƁ"))
		bh.consume(collection.add("ĎĎĎĎĎĎĎĎĎĎ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ķķķķķķķķķķ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŞŞŞŞŞŞŞŞŞŞ","ūūūūūūūūūū","ÚÚÚÚÚÚÚÚÚÚ")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("đđđđđđđđđđ","ŵŵŵŵŵŵŵŵŵŵ","āāāāāāāāāā","ÙÙÙÙÙÙÙÙÙÙ")))
		collection = collection.diff(mutable.HashSet[String]("ÕÕÕÕÕÕÕÕÕÕ","ÖÖÖÖÖÖÖÖÖÖ","ŲŲŲŲŲŲŲŲŲŲ"))
		collection = collection.union(mutable.HashSet[String]("ĖĖĖĖĖĖĖĖĖĖ","ņņņņņņņņņņ","öööööööööö","ŘŘŘŘŘŘŘŘŘŘ"))
		collection = collection.diff(mutable.HashSet[String]("űűűűűűűűűű","ĶĶĶĶĶĶĶĶĶĶ","ŝŝŝŝŝŝŝŝŝŝ"))
		collection = collection.union(mutable.HashSet[String]("ņņņņņņņņņņ","ŰŰŰŰŰŰŰŰŰŰ","ŎŎŎŎŎŎŎŎŎŎ"))
		collection = collection.union(mutable.HashSet[String]("ĂĂĂĂĂĂĂĂĂĂ","ŘŘŘŘŘŘŘŘŘŘ","èèèèèèèèèè"))
		collection = collection.diff(mutable.HashSet[String]("ĻĻĻĻĻĻĻĻĻĻ","ŎŎŎŎŎŎŎŎŎŎ","ĵĵĵĵĵĵĵĵĵĵ","ŃŃŃŃŃŃŃŃŃŃ"))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ņņņņņņņņņņ","ææææææææææ","şşşşşşşşşş")))
		bh.consume(collection.add("ſſſſſſſſſſ"))
		bh.consume(collection.remove("ðððððððððð"))
		bh.consume(collection.remove("ĞĞĞĞĞĞĞĞĞĞ"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("žžžžžžžžžž","ŌŌŌŌŌŌŌŌŌŌ","çççççççççç","šššššššššš"))
		collection = collection.diff(mutable.HashSet[String]("űűűűűűűűűű","ŊŊŊŊŊŊŊŊŊŊ","őőőőőőőőőő"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ĵĵĵĵĵĵĵĵĵĵ"))
		collection = collection.diff(mutable.HashSet[String]("ĚĚĚĚĚĚĚĚĚĚ","èèèèèèèèèè","ėėėėėėėėėė"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ļļļļļļļļļļ","ƈƈƈƈƈƈƈƈƈƈ","źźźźźźźźźź")))
		collection = collection.union(mutable.HashSet[String]("ĳĳĳĳĳĳĳĳĳĳ","àààààààààà","ŐŐŐŐŐŐŐŐŐŐ","ĳĳĳĳĳĳĳĳĳĳ"))
		bh.consume(collection.add("ÜÜÜÜÜÜÜÜÜÜ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("úúúúúúúúúú","ůůůůůůůůůů","áááááááááá","ĄĄĄĄĄĄĄĄĄĄ")))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŝŝŝŝŝŝŝŝŝŝ","áááááááááá","ňňňňňňňňňň","ƂƂƂƂƂƂƂƂƂƂ")))
		collection = collection.union(mutable.HashSet[String]("ÈÈÈÈÈÈÈÈÈÈ","ŝŝŝŝŝŝŝŝŝŝ","ěěěěěěěěěě"))
		collection = collection.diff(mutable.HashSet[String]("ęęęęęęęęęę","ŚŚŚŚŚŚŚŚŚŚ","ĂĂĂĂĂĂĂĂĂĂ"))
		bh.consume(collection.remove("ďďďďďďďďďď"))
		collection = collection.diff(mutable.HashSet[String]("ŁŁŁŁŁŁŁŁŁŁ","ĔĔĔĔĔĔĔĔĔĔ","üüüüüüüüüü","ææææææææææ"))
		bh.consume(collection.remove("ƏƏƏƏƏƏƏƏƏƏ"))
		collection = collection.union(mutable.HashSet[String]("ÛÛÛÛÛÛÛÛÛÛ","áááááááááá","ŤŤŤŤŤŤŤŤŤŤ"))
		bh.consume(collection.remove("ÐÐÐÐÐÐÐÐÐÐ"))
		bh.consume(collection.add("ƅƅƅƅƅƅƅƅƅƅ"))
		collection = collection.union(mutable.HashSet[String]("ŝŝŝŝŝŝŝŝŝŝ","ıııııııııı","÷÷÷÷÷÷÷÷÷÷"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĆĆĆĆĆĆĆĆĆĆ","ĐĐĐĐĐĐĐĐĐĐ","ęęęęęęęęęę")))
		collection = collection.union(mutable.HashSet[String]("çççççççççç","ĐĐĐĐĐĐĐĐĐĐ","řřřřřřřřřř","ĞĞĞĞĞĞĞĞĞĞ"))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ųųųųųųųųųų","ŋŋŋŋŋŋŋŋŋŋ","ŎŎŎŎŎŎŎŎŎŎ")))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ĐĐĐĐĐĐĐĐĐĐ"))
		bh.consume(collection.add("ƉƉƉƉƉƉƉƉƉƉ"))
		bh.consume(collection.remove("øøøøøøøøøø"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ĮĮĮĮĮĮĮĮĮĮ","ĿĿĿĿĿĿĿĿĿĿ","ĢĢĢĢĢĢĢĢĢĢ"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ÓÓÓÓÓÓÓÓÓÓ","üüüüüüüüüü","áááááááááá"))
		bh.consume(collection.add("ÑÑÑÑÑÑÑÑÑÑ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("öööööööööö","ôôôôôôôôôô","ďďďďďďďďďď","ƉƉƉƉƉƉƉƉƉƉ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("þþþþþþþþþþ","òòòòòòòòòò","ƊƊƊƊƊƊƊƊƊƊ")))
		collection = collection.union(mutable.HashSet[String]("ÍÍÍÍÍÍÍÍÍÍ","ĮĮĮĮĮĮĮĮĮĮ","ĆĆĆĆĆĆĆĆĆĆ"))
		collection.toArray(classTag[String])
		collection = collection.diff(mutable.HashSet[String]("ċċċċċċċċċċ","ďďďďďďďďďď","ĔĔĔĔĔĔĔĔĔĔ"))
		bh.consume(collection.add("ĢĢĢĢĢĢĢĢĢĢ"))
		collection = collection.union(mutable.HashSet[String]("ÊÊÊÊÊÊÊÊÊÊ","ŹŹŹŹŹŹŹŹŹŹ","ƇƇƇƇƇƇƇƇƇƇ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ÖÖÖÖÖÖÖÖÖÖ","İİİİİİİİİİ","ËËËËËËËËËË","ŒŒŒŒŒŒŒŒŒŒ"))
		collection = collection.union(mutable.HashSet[String]("ĂĂĂĂĂĂĂĂĂĂ","ÉÉÉÉÉÉÉÉÉÉ","ƋƋƋƋƋƋƋƋƋƋ"))
		collection = collection.diff(mutable.HashSet[String]("ĳĳĳĳĳĳĳĳĳĳ","āāāāāāāāāā","ŏŏŏŏŏŏŏŏŏŏ"))
		bh.consume(collection.remove("ääääääääää"))
		collection = collection.diff(mutable.HashSet[String]("êêêêêêêêêê","åååååååååå","ÕÕÕÕÕÕÕÕÕÕ","ũũũũũũũũũũ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ææææææææææ","ÍÍÍÍÍÍÍÍÍÍ","šššššššššš")))
		bh.consume(collection.add("ïïïïïïïïïï"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ùùùùùùùùùù","ņņņņņņņņņņ","źźźźźźźźźź")))
		bh.consume(collection.add("āāāāāāāāāā"))
		collection = collection.union(mutable.HashSet[String]("ųųųųųųųųųų","ŵŵŵŵŵŵŵŵŵŵ","ĖĖĖĖĖĖĖĖĖĖ"))
		collection = collection.union(mutable.HashSet[String]("ĕĕĕĕĕĕĕĕĕĕ","İİİİİİİİİİ","ƅƅƅƅƅƅƅƅƅƅ","êêêêêêêêêê"))
		collection = collection.union(mutable.HashSet[String]("řřřřřřřřřř","ŅŅŅŅŅŅŅŅŅŅ","œœœœœœœœœœ","čččččččččč"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ąąąąąąąąąą","ÏÏÏÏÏÏÏÏÏÏ","ĿĿĿĿĿĿĿĿĿĿ")))
		collection = collection.union(mutable.HashSet[String]("ÊÊÊÊÊÊÊÊÊÊ","ƃƃƃƃƃƃƃƃƃƃ","××××××××××","ŠŠŠŠŠŠŠŠŠŠ"))
		bh.consume(collection.add("ÿÿÿÿÿÿÿÿÿÿ"))
		bh.consume(collection.add("ÔÔÔÔÔÔÔÔÔÔ"))
		collection = collection.diff(mutable.HashSet[String]("êêêêêêêêêê","ĠĠĠĠĠĠĠĠĠĠ","ŏŏŏŏŏŏŏŏŏŏ"))
		collection = collection.union(mutable.HashSet[String]("ĭĭĭĭĭĭĭĭĭĭ","ĢĢĢĢĢĢĢĢĢĢ","êêêêêêêêêê","ŊŊŊŊŊŊŊŊŊŊ"))
		bh.consume(collection.add("ąąąąąąąąąą"))
		bh.consume(collection.add("ĹĹĹĹĹĹĹĹĹĹ"))
		bh.consume(collection.add("ęęęęęęęęęę"))
		collection = collection.diff(mutable.HashSet[String]("ſſſſſſſſſſ","ŰŰŰŰŰŰŰŰŰŰ","ĵĵĵĵĵĵĵĵĵĵ","ïïïïïïïïïï"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("œœœœœœœœœœ","çççççççççç","ŊŊŊŊŊŊŊŊŊŊ")))
		bh.consume(collection.add("śśśśśśśśśś"))
		collection = collection.diff(mutable.HashSet[String]("ăăăăăăăăăă","ƂƂƂƂƂƂƂƂƂƂ","ŦŦŦŦŦŦŦŦŦŦ"))
		collection = collection.diff(mutable.HashSet[String]("ĸĸĸĸĸĸĸĸĸĸ","ĻĻĻĻĻĻĻĻĻĻ","ÕÕÕÕÕÕÕÕÕÕ"))
		collection = collection.union(mutable.HashSet[String]("ŰŰŰŰŰŰŰŰŰŰ","ąąąąąąąąąą","ŕŕŕŕŕŕŕŕŕŕ","ðððððððððð"))
		bh.consume(collection.add("ƇƇƇƇƇƇƇƇƇƇ"))
		collection = collection.diff(mutable.HashSet[String]("šššššššššš","ŚŚŚŚŚŚŚŚŚŚ","ŋŋŋŋŋŋŋŋŋŋ","ÒÒÒÒÒÒÒÒÒÒ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĖĖĖĖĖĖĖĖĖĖ","żżżżżżżżżż","ŠŠŠŠŠŠŠŠŠŠ")))
		bh.consume(collection.add("ţţţţţţţţţţ"))
		collection = collection.union(mutable.HashSet[String]("ƈƈƈƈƈƈƈƈƈƈ","ġġġġġġġġġġ","ųųųųųųųųųų"))
		collection = collection.union(mutable.HashSet[String]("ÏÏÏÏÏÏÏÏÏÏ","őőőőőőőőőő","ĭĭĭĭĭĭĭĭĭĭ","ŗŗŗŗŗŗŗŗŗŗ"))
		bh.consume(collection.add("ĺĺĺĺĺĺĺĺĺĺ"))
		collection = collection.diff(mutable.HashSet[String]("úúúúúúúúúú","ŠŠŠŠŠŠŠŠŠŠ","ŢŢŢŢŢŢŢŢŢŢ"))
		collection = collection.union(mutable.HashSet[String]("ĨĨĨĨĨĨĨĨĨĨ","ĖĖĖĖĖĖĖĖĖĖ","öööööööööö"))
		bh.consume(collection.add("ƋƋƋƋƋƋƋƋƋƋ"))
		collection = collection.diff(mutable.HashSet[String]("ĂĂĂĂĂĂĂĂĂĂ","ŧŧŧŧŧŧŧŧŧŧ","łłłłłłłłłł","ÍÍÍÍÍÍÍÍÍÍ"))
		collection = collection.union(mutable.HashSet[String]("ƈƈƈƈƈƈƈƈƈƈ","ėėėėėėėėėė","÷÷÷÷÷÷÷÷÷÷","ĳĳĳĳĳĳĳĳĳĳ"))
		collection = collection.union(mutable.HashSet[String]("ƇƇƇƇƇƇƇƇƇƇ","ĈĈĈĈĈĈĈĈĈĈ","ôôôôôôôôôô","öööööööööö"))
		bh.consume(collection.add("ĿĿĿĿĿĿĿĿĿĿ"))
		collection = collection.union(mutable.HashSet[String]("ŇŇŇŇŇŇŇŇŇŇ","ÎÎÎÎÎÎÎÎÎÎ","ƁƁƁƁƁƁƁƁƁƁ","ĻĻĻĻĻĻĻĻĻĻ"))
		bh.consume(collection.add("ĩĩĩĩĩĩĩĩĩĩ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("űűűűűűűűűű","ĺĺĺĺĺĺĺĺĺĺ","ŦŦŦŦŦŦŦŦŦŦ")))
		bh.consume(collection.add("öööööööööö"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("řřřřřřřřřř","ũũũũũũũũũũ","ńńńńńńńńńń")))
		collection = collection.union(mutable.HashSet[String]("éééééééééé","ĄĄĄĄĄĄĄĄĄĄ","ĿĿĿĿĿĿĿĿĿĿ"))
		bh.consume(collection.add("ŞŞŞŞŞŞŞŞŞŞ"))
		bh.consume(collection.add("ÜÜÜÜÜÜÜÜÜÜ"))
		collection = collection.union(mutable.HashSet[String]("ĹĹĹĹĹĹĹĹĹĹ","ÔÔÔÔÔÔÔÔÔÔ","ĒĒĒĒĒĒĒĒĒĒ"))
		bh.consume(collection.remove("××××××××××"))
		collection = collection.union(mutable.HashSet[String]("ĪĪĪĪĪĪĪĪĪĪ","ŻŻŻŻŻŻŻŻŻŻ","ŕŕŕŕŕŕŕŕŕŕ"))
		collection = collection.union(mutable.HashSet[String]("īīīīīīīīīī","ÜÜÜÜÜÜÜÜÜÜ","ËËËËËËËËËË","ĻĻĻĻĻĻĻĻĻĻ"))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŪŪŪŪŪŪŪŪŪŪ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("öööööööööö","ăăăăăăăăăă","ŦŦŦŦŦŦŦŦŦŦ")))
		collection = collection.union(mutable.HashSet[String]("êêêêêêêêêê","ĽĽĽĽĽĽĽĽĽĽ","úúúúúúúúúú","čččččččččč"))
		bh.consume(collection.add("ŘŘŘŘŘŘŘŘŘŘ"))
		bh.consume(collection.add("ÉÉÉÉÉÉÉÉÉÉ"))
		collection = collection.union(mutable.HashSet[String]("ĠĠĠĠĠĠĠĠĠĠ","ŗŗŗŗŗŗŗŗŗŗ","œœœœœœœœœœ"))
		collection = collection.union(mutable.HashSet[String]("őőőőőőőőőő","ðððððððððð","ÝÝÝÝÝÝÝÝÝÝ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("śśśśśśśśśś","ſſſſſſſſſſ","őőőőőőőőőő")))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŵŵŵŵŵŵŵŵŵŵ","ŵŵŵŵŵŵŵŵŵŵ","ƇƇƇƇƇƇƇƇƇƇ")))
		bh.consume(collection.add("ôôôôôôôôôô"))
		collection = collection.union(mutable.HashSet[String]("ăăăăăăăăăă","őőőőőőőőőő","ÐÐÐÐÐÐÐÐÐÐ"))
		bh.consume(collection.add("ƀƀƀƀƀƀƀƀƀƀ"))
		collection.toArray(classTag[String])
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ññññññññññ","ÖÖÖÖÖÖÖÖÖÖ","ŗŗŗŗŗŗŗŗŗŗ","ĿĿĿĿĿĿĿĿĿĿ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŠŠŠŠŠŠŠŠŠŠ","ēēēēēēēēēē","ČČČČČČČČČČ","ŎŎŎŎŎŎŎŎŎŎ")))
		collection = collection.union(mutable.HashSet[String]("ĳĳĳĳĳĳĳĳĳĳ","ÊÊÊÊÊÊÊÊÊÊ","ƅƅƅƅƅƅƅƅƅƅ"))
		bh.consume(collection.add("ſſſſſſſſſſ"))
		collection = collection.diff(mutable.HashSet[String]("ŜŜŜŜŜŜŜŜŜŜ","ŕŕŕŕŕŕŕŕŕŕ","ƉƉƉƉƉƉƉƉƉƉ","ŭŭŭŭŭŭŭŭŭŭ"))
		collection.toArray(classTag[String])
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŔŔŔŔŔŔŔŔŔŔ","ŒŒŒŒŒŒŒŒŒŒ","ðððððððððð")))
		collection = collection.diff(mutable.HashSet[String]("ċċċċċċċċċċ","ƄƄƄƄƄƄƄƄƄƄ","ĳĳĳĳĳĳĳĳĳĳ","ħħħħħħħħħħ"))
		bh.consume(collection.add("ÈÈÈÈÈÈÈÈÈÈ"))
		collection = collection.diff(mutable.HashSet[String]("òòòòòòòòòò","ĹĹĹĹĹĹĹĹĹĹ","áááááááááá","ìììììììììì"))
		collection = collection.union(mutable.HashSet[String]("ÖÖÖÖÖÖÖÖÖÖ","ŜŜŜŜŜŜŜŜŜŜ","ĝĝĝĝĝĝĝĝĝĝ","ęęęęęęęęęę"))
		bh.consume(collection.remove("úúúúúúúúúú"))
		bh.consume(collection.add("ĻĻĻĻĻĻĻĻĻĻ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĮĮĮĮĮĮĮĮĮĮ","ƋƋƋƋƋƋƋƋƋƋ","ƍƍƍƍƍƍƍƍƍƍ")))
		bh.consume(collection.add("ÓÓÓÓÓÓÓÓÓÓ"))
		collection.toArray(classTag[String])
		collection = collection.union(mutable.HashSet[String]("ŦŦŦŦŦŦŦŦŦŦ","õõõõõõõõõõ","ıııııııııı","ƂƂƂƂƂƂƂƂƂƂ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ŌŌŌŌŌŌŌŌŌŌ","ŜŜŜŜŜŜŜŜŜŜ","ŰŰŰŰŰŰŰŰŰŰ")))
		collection = collection.union(mutable.HashSet[String]("ääääääääää","ĚĚĚĚĚĚĚĚĚĚ","ŉŉŉŉŉŉŉŉŉŉ","ŤŤŤŤŤŤŤŤŤŤ"))
		collection = collection.union(mutable.HashSet[String]("ĻĻĻĻĻĻĻĻĻĻ","ěěěěěěěěěě","ūūūūūūūūūū","ęęęęęęęęęę"))
		bh.consume(collection.add("şşşşşşşşşş"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("űűűűűűűűűű","ġġġġġġġġġġ","òòòòòòòòòò")))
		collection = collection.union(mutable.HashSet[String]("ĊĊĊĊĊĊĊĊĊĊ","ůůůůůůůůůů","ĴĴĴĴĴĴĴĴĴĴ","ģģģģģģģģģģ"))
		collection = collection.diff(mutable.HashSet[String]("ƊƊƊƊƊƊƊƊƊƊ","řřřřřřřřřř","ƂƂƂƂƂƂƂƂƂƂ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("íííííííííí","ĞĞĞĞĞĞĞĞĞĞ","ŔŔŔŔŔŔŔŔŔŔ")))
		bh.consume(collection.add("ƁƁƁƁƁƁƁƁƁƁ"))
		collection = collection.union(mutable.HashSet[String]("êêêêêêêêêê","ŁŁŁŁŁŁŁŁŁŁ","ĪĪĪĪĪĪĪĪĪĪ","żżżżżżżżżż"))
		bh.consume(collection.add("ƂƂƂƂƂƂƂƂƂƂ"))
		collection = collection.union(mutable.HashSet[String]("ƂƂƂƂƂƂƂƂƂƂ","ėėėėėėėėėė","ÒÒÒÒÒÒÒÒÒÒ","őőőőőőőőőő"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("łłłłłłłłłł","ķķķķķķķķķķ","ČČČČČČČČČČ","ŰŰŰŰŰŰŰŰŰŰ")))
		bh.consume(collection.add("žžžžžžžžžž"))
		collection = collection.diff(mutable.HashSet[String]("÷÷÷÷÷÷÷÷÷÷","ťťťťťťťťťť","××××××××××","ÊÊÊÊÊÊÊÊÊÊ"))
		bh.consume(collection.add("ÒÒÒÒÒÒÒÒÒÒ"))
		bh.consume(collection.add("řřřřřřřřřř"))
		collection = collection.union(mutable.HashSet[String]("ëëëëëëëëëë","ŸŸŸŸŸŸŸŸŸŸ","ĊĊĊĊĊĊĊĊĊĊ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĕĕĕĕĕĕĕĕĕĕ","ŲŲŲŲŲŲŲŲŲŲ","ĖĖĖĖĖĖĖĖĖĖ")))
		collection.toArray(classTag[String])
		bh.consume(collection.add("ŒŒŒŒŒŒŒŒŒŒ"))
		collection = collection.diff(mutable.HashSet[String]("ðððððððððð","ćććććććććć","ėėėėėėėėėė"))
		bh.consume(collection.add("ÍÍÍÍÍÍÍÍÍÍ"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ÕÕÕÕÕÕÕÕÕÕ","ĩĩĩĩĩĩĩĩĩĩ","ĝĝĝĝĝĝĝĝĝĝ")))
		collection = collection.union(mutable.HashSet[String]("žžžžžžžžžž","şşşşşşşşşş","ûûûûûûûûûû","öööööööööö"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("İİİİİİİİİİ","ŴŴŴŴŴŴŴŴŴŴ","ŃŃŃŃŃŃŃŃŃŃ","ĖĖĖĖĖĖĖĖĖĖ")))
		bh.consume(collection.add("åååååååååå"))
		bh.consume(collection.addAll(mutable.ArrayBuffer[String]("ĩĩĩĩĩĩĩĩĩĩ","èèèèèèèèèè","ŚŚŚŚŚŚŚŚŚŚ","ĪĪĪĪĪĪĪĪĪĪ")))
	}
}
